import { defineStore } from 'pinia'
import { ref, watch } from 'vue'

export type Language = 'en' | 'uk' | 'es' | 'fr'
export type Role = 'manager' | 'driver' | 'mechanic' | 'admin' | null

const translations: Record<Language, Record<string, string>> = {
  en: {
    // App
    appName: 'FleetCheck Pro',
    tagline: 'Digital vehicle inspections for safer fleets',
    getStarted: 'Get Started',
    companyLogin: 'Company Login',
    driverRegistration: 'Driver Registration',

    // Nav
    dashboard: 'Dashboard',
    vehicles: 'Vehicles',
    drivers: 'Drivers',
    inspections: 'Inspections',
    reports: 'Reports',
    issues: 'Issues',
    repairs: 'Repairs',
    settings: 'Settings',
    home: 'Home',
    inspect: 'Inspect',
    profile: 'Profile',
    profilePhoto: 'Profile Photo',
    businessAccess: 'Business Access',
    switchBusiness: 'Switch business',
    joinAnotherBusiness: 'Join another business',
    enterBusinessCode: 'Enter business code',
    joinBusiness: 'Join business',
    businessJoined: 'Business joined successfully.',
    driverProfileUpdated: 'Driver profile updated.',
    joinBusinessDriverOnly: 'You must be signed in as a driver to join another business.',
    differentOwnerAccountError: 'This driver account is already linked to a different business owner.',
    driverProfileNotFound: 'Driver profile not found.',
    driverProfileSaveFailed: 'Unable to save driver profile.',
    driverDocumentsUploadFailed: 'Unable to upload driver documents.',
    joinBusinessFailed: 'Unable to join business.',
    signInAndJoinBusiness: 'Sign in and join this business',
    driverDocumentsMustDiffer: 'License photo and medical card photo must be different files.',
    driverRemovedFromBusiness: 'Driver removed from this business.',
    uploadSignature: 'Upload signature',
    signatureUploadHint: 'Save one clear signature image so it can be reused on future digital forms.',
    signatureRequired: 'Driver signature is required to complete registration.',
    pendingDueExpiredDocuments: 'Pending until expired documents are renewed.',
    streetAddress: 'Street Address',
    postalCode: 'ZIP / Postal Code',
    useCurrentLocation: 'Use current location',
    detectingLocation: 'Detecting location...',
    locationAutofillFailed: 'Unable to detect your address from this device. Enter it manually.',
    completeHighlightedFields: 'Complete the highlighted fields.',
    phoneMustMatchBusinessCountry: 'Phone number must match the business country format.',
    driverMustBe21ForCommercial: 'Drivers with CDL truck classes must be at least 21 years old.',
    driverMustBe18: 'Driver must be at least 18 years old.',
    medicalCardMustBeFuture: 'Medical card expiry must be later than today.',
    medicalCardMaxTwoYearsUs: 'For U.S. businesses, medical card expiry cannot be more than 2 years from today.',
    medicalCardExpiryRuleUs: 'For U.S. businesses, the medical card must expire after today and within 2 years.',
    medicalCardExpiryRuleGeneric: 'Medical card expiry must be later than today.',
    hireDateCannotBeFuture: 'Hire date cannot be in the future.',
    hireDateHint: 'Enter the date when the driver started working for this business.',
    businessPhoneHint: 'Phone format follows the business country:',

    // Nav back links
    backToDrivers: 'Back to Drivers',
    backToFleet: 'Back to Fleet',
    backToLogin: 'Back to Login',
    backToInspection: 'Back to Inspection',
    backToIssues: 'Back to Issues',
    backToRepairs: 'Back to Repairs',
    backToDashboard: 'Back to Dashboard',

    // Auth
    login: 'Sign in',
    logout: 'Logout',
    signIn: 'Sign in',
    signUp: 'Sign up',
    createAccount: 'Create Account',
    forgotPassword: 'Forgot password?',
    alreadyHaveAccount: 'Already have an account?',
    signInWithGoogle: 'Sign in with Google',
    signUpWithGoogle: 'Sign up with Google',
    companyAccountRegistration: 'Company account registration',
    createYourCompanyAccount: 'Create your company account',
    signInToYourAccount: 'Sign in to your account',
    enterLoginCredentials: 'Enter your login credentials to get started.',
    or: 'or',
    atLeast8Chars: 'At least 8 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordsMatch: 'Passwords match',

    // Buttons
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    edit: 'Edit',
    delete: 'Delete',
    saveChanges: 'Save Changes',
    saveDriver: 'Save Driver',
    editDriver: 'Edit Driver',
    addDriver: 'Add Driver',
    addVehicle: 'Add Vehicle',
    addPhoto: 'Add Photo',
    removePhoto: 'Remove photo',
    editVehicle: 'Edit Vehicle',
    editRepair: 'Edit Repair',
    newRepairRequest: 'New Repair Request',
    newRequest: 'New Request',
    submitRequest: 'Submit Request',
    saveReview: 'Save Review',
    review: 'Review',
    markAllOk: 'Mark all OK',
    saveDraft: 'Save Draft',
    sendToRepair: 'Send to Repair',
    rejectIssue: 'Reject Issue',
    blockVehicle: 'Block Vehicle',
    markAsFixed: 'Mark as Fixed',
    viewFullReport: 'View Full Report',
    fixAndResubmit: 'Fix & Resubmit',
    viewAll: 'View all',
    openVehicleCard: 'Open Vehicle Card',
    goToLogin: 'Go to Login',
    backToHome: 'Back to Home',
    goToDashboard: 'Go to Dashboard',
    outOfService: 'Out of Service',
    restoreService: 'Restore Service',
    signOut: 'Sign Out',
    reportProblem: 'Report Problem',
    viewAllNotifications: 'View all notifications',
    notifications: 'Notifications',
    new: 'new',
    approveOk: 'Approve — OK',
    flagIssue: 'Flag Issue',
    reviewInspection: 'Review Inspection',
    createDriverAccount: 'Create Driver Account',
    download: 'Download',
    pdf: 'PDF',
    csv: 'CSV',
    email: 'Email',

    // Form fields
    emailField: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    dateOfBirth: 'Date of Birth',
    homeAddress: 'Home Address',
    address: 'Address',
    companyName: 'Company Name',
    industryType: 'Industry Type',
    country: 'Country',
    stateProvince: 'State / Province',
    city: 'City',
    licenseNumber: 'License #',
    licenseClass: 'License Class',
    expiryDate: 'Expiry Date',
    medicalCardNumber: 'Medical Card #',
    medicalCardPhoto: 'Medical Card Photo',
    licensePhoto: 'License Photo',
    hireDate: 'Hire Date',
    driverAuthManagedByDriver: 'Email and password are managed from the driver account.',
    notProvided: 'Not provided',
    canBeAddedLater: 'Can be added later by the owner or admin.',
    documentNotUploadedYet: 'Document not uploaded yet.',
    temporaryPassword: 'Temporary Password',
    contactName: 'Contact Name',
    contactPhone: 'Contact Phone',
    vehicleNumber: 'Vehicle Number',
    type: 'Type',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    plateNumber: 'Plate Number',
    vin: 'VIN',
    odometer: 'Odometer (mi)',
    engineHours: 'Engine Hours',
    vehiclePhoto: 'Vehicle Photo',
    repairTitle: 'Repair Title',
    description: 'Description',
    issueCategory: 'Issue Category',
    driver: 'Driver',
    relatedIssue: 'Related Issue',
    startedAt: 'Started At',
    completedAt: 'Completed At',
    managersDecision: "Manager's Decision",
    managersNote: "Manager's Note",
    managerNotes: 'Manager Notes',
    invitationCode: 'Invitation Code',
    cardNumber: 'Card #',
    class: 'Class',
    language: 'Language',
    theme: 'Theme',
    search: 'Search...',
    createdAt: 'Created At',
    view: 'View',
    inspectionLabel: 'Inspection',
    chooseLanguage: 'Choose the display language for the application.',
    customizeAppearance: 'Customize how FleetCheck Pro looks on your device.',
    driverDashboard: 'Dashboard',
    checked: 'checked',
    okLabel: 'OK',
    issuesLabel: 'Issues',
    describeIssue: 'Describe the issue…',
    driverSignature: 'Driver Signature',
    documentsLabel: 'Documents',
    duration: 'Duration',
    photosTaken: 'Photos taken',
    fixResubmit: 'Fix & Resubmit',
    searchDrivers: 'Search drivers...',
    searchVehicles: 'Search vehicles...',
    searchRepairs: 'Search repairs...',
    searchIssues: 'Search issues...',

    // Section titles
    reportsCompliance: 'Reports & Compliance',
    myReports: 'My Reports',
    fleetVehicles: 'Fleet Vehicles',
    repairRequests: 'Repair Requests',
    inspectionResult: 'Inspection Result',
    issueDetails: 'Issue Details',
    driverProfile: 'Driver Profile',
    vehicleDetail: 'Vehicle Detail',
    personalInformation: 'Personal Information',
    emergencyContact: 'Emergency Contact',
    driverLicense: 'Driver License',
    medicalCard: 'Medical Card',
    employment: 'Employment',
    companyProfile: 'Company Profile',
    fleetManager: 'Fleet Manager',
    companyInformation: 'Company Information',
    languageSettings: 'Language Settings',
    appearance: 'Appearance',
    repairInformation: 'Repair Information',
    basicInformation: 'Basic Information',
    issueInformation: 'Issue Information',
    photos: 'Photos',
    statusHistory: 'Status History',
    inspectionSummary: 'Inspection Summary',
    failedItems: 'Failed Items',
    vehiclePhotos: 'Vehicle Photos',
    inspectionHistory: 'Inspection History',
    repairHistory: 'Repair History',
    recentInspections: 'Recent Inspections',
    availableVehicles: 'Available Vehicles',
    recentReports: 'Recent Reports',
    inspectionsPendingReview: 'Inspections Pending Review',
    inspectionsThisWeek: 'Inspections This Week',
    issuesByCategory: 'Issues by Category',
    repairStatus: 'Repair Status',
    startInspection: 'Start Inspection',
    allowedVehicleTypes: 'Allowed Vehicle Types',

    // Table headers
    date: 'Date',
    vehicle: 'Vehicle',
    result: 'Result',
    reviewStatus: 'Review Status',
    actions: 'Actions',
    status: 'Status',
    priority: 'Priority',
    reportedBy: 'Reported By',
    signature: 'Signature',
    severity: 'Severity',
    unit: 'Unit',
    time: 'Time',
    plate: 'Plate',
    category: 'Category',
    issue: 'Issue',
    licenseHash: 'License #',
    licExpiry: 'Lic. Expiry',
    medExpiry: 'Med. Expiry',
    allowedVehicles: 'Allowed Vehicles',
    inspectionType: 'Inspection Type',
    inspectionDate: 'Inspection Date',
    issueDate: 'Issue Date',
    currentStatus: 'Current Status',

    // Statuses
    statusActive: 'Active',
    statusPending: 'Pending',
    statusInactive: 'Inactive',
    statusNeedsAttention: 'Needs Attention',
    statusBlocked: 'Blocked',
    statusInRepair: 'In Repair',
    statusDraft: 'Draft',
    statusSubmitted: 'Submitted',
    statusOpen: 'Open',
    statusInProgress: 'In Progress',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    statusUnderReview: 'Under Review',
    statusFixed: 'Fixed',
    statusRejected: 'Rejected',
    statusNeedsReview: 'Needs Review',
    statusReviewedOk: 'Reviewed OK',
    statusFlagged: 'Flagged',
    statusPassed: 'Passed',
    statusFailed: 'Failed',

    // Priority / Severity
    priorityHigh: 'High',
    priorityMedium: 'Medium',
    priorityLow: 'Low',

    // Filter dropdowns
    allStatus: 'All Status',
    allTypes: 'All Types',
    allResults: 'All Results',
    allPriority: 'All Priority',
    allSeverity: 'All Severity',
    all: 'All',
    fraudFlagged: 'Fraud Flagged',
    clean: 'Clean',
    selectType: 'Select type',
    selectClass: 'Select class',
    selectCategory: 'Select category',
    selectVehicle: 'Select vehicle',
    none: 'None',
    preTrip: 'Pre-Trip',
    postTrip: 'Post-Trip',

    // Inspections
    preTripInspection: 'Pre-Trip Inspection',
    postTripInspection: 'Post-Trip Inspection',
    pass: 'Pass',
    fail: 'Fail',
    na: 'N/A',
    addComment: 'Add Comment',
    signHere: 'Sign here',
    submitInspection: 'Submit Inspection',
    inspectionPassed: 'Inspection Passed',
    inspectionFailed: 'Issues Found',
    vehicleReadyForOperation: 'Vehicle is ready for operation. All inspection items passed.',
    issuesFoundMessage: 'issue(s) found. Manager review required before operating this vehicle.',
    completedBeforeDeparting: 'Complete before departing',
    completedAfterArriving: 'Complete after arriving',

    // Checklist categories
    tiresWheels: 'Tires & Wheels',
    lightsSignals: 'Lights & Signals',
    brakes: 'Brakes',
    fluidLevels: 'Fluid Levels',
    safetyEquipment: 'Safety Equipment',
    documents: 'Documents',

    // Repair categories
    tires: 'Tires',
    lights: 'Lights',
    fluids: 'Fluids',
    engine: 'Engine',
    exterior: 'Exterior',
    steering: 'Steering',
    other: 'Other',

    // Repair / Issue actions
    createRepairRequest: 'Create Repair Request',
    notifyManager: 'Notify Manager',

    // Pending
    pendingApproval: 'Registration Pending Approval',
    pendingMessage: 'Your registration has been submitted. Please wait for manager approval.',
    whatHappensNext: 'What happens next?',
    managerWillReview: 'Your manager will review your registration',
    youllReceiveEmail: "You'll receive an email when approved",
    onceApprovedLogin: 'Once approved, you can log in and start inspections',

    // IssueDetail
    fraudFlaggedLabel: 'Fraud Flagged',
    vehicleBlockedLabel: 'Vehicle Blocked',

    // Driver dashboard stats
    tripsThisMonth: 'Trips This Month',
    inspectionsPassed: 'Inspections Passed',
    openIssues: 'Open Issues',
    fuelEfficiency: 'Fuel Efficiency',
    submitRepairRequest: 'Submit repair request',
    logOutOfApp: 'Log out of app',

    // Empty states
    noDriversFound: 'No drivers found.',
    noVehiclesFound: 'No vehicles found.',
    noRepairsFound: 'No repairs found.',
    noReportsFound: 'No reports found.',
    noIssuesFound: 'No issues found.',
    issueNotFound: 'Issue not found.',
    noneAssigned: 'None assigned',
    noPhotosAttached: 'No photos attached to this issue',

    // Misc
    showing: 'Showing',
    of: 'of',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    selectLanguage: 'Select Language',
    english: 'English',
    ukrainian: 'Ukrainian',
    spanish: 'Spanish',
    french: 'French',

    // Registration
    workspaceReady: 'Your workspace is ready!',
    workspaceSetupSuccess: 'Your company workspace has been set up successfully.',
    workspaceSetupInfo: 'You can now add vehicles, invite drivers, and start managing inspections.',
    createYourAccount: 'Create Your Account',
    driverRegSubtitle: 'Create your driver account using your company invitation code.',
    noGoogleAccountHint: 'No Google account? Create a workspace with your email and password, then sign in here with the same email.',
    createAccountWithEmail: 'Create account with email',
    alreadyCreatedWorkspaceWithEmail: 'No company account yet?',
    createItHere: 'Create it here',
    verifyInvite: 'Verify',
    checkingInvite: 'Checking...',
    invitationFoundFor: 'Invitation found for',
    creating: 'Creating...',
    inviteDriver: 'Invite driver',
    activeBusiness: 'Active business',
    driverInvitations: 'Driver invitations',
    inviteDriversTo: 'Invite drivers to',
    driverInvitationsHelp: 'Drivers use one code for the selected business. Rotate it any time if you need to replace the current code.',
    businessInviteCode: 'Business invite code',
    businessInviteCodeHelp: 'Share this code or the registration link with drivers who should join this business.',
    driverRegistrationLink: 'Driver registration link',
    openRegistrationPage: 'Open registration page',
    approveDriver: 'Approve driver',
    rejectDriver: 'Reject driver',
    driverApproved: 'Driver approved.',
    driverRejected: 'Driver rejected.',
    generateBusinessCode: 'Generate code',
    rotateBusinessCode: 'Rotate code',
    noBusinessInviteCode: 'This business does not have an invite code yet.',
    businessInviteCodeCreated: 'Business invite code created.',
    businessInviteCodeUpdated: 'Business invite code updated.',
    newInvite: 'New invite',
    noDriverInvites: 'No driver invite code yet for this business.',
    invitationCodeLabel: 'Invitation code',
    openInvitationForAnyEmail: 'Open invitation for any driver email',
    expires: 'Expires',
    withoutExpiry: 'without expiry',
    copyCode: 'Copy code',
    copyLink: 'Copy link',
    createDriverInvite: 'Create driver invite',
    driverEmail: 'Driver email',
    inviteEmailHint: 'Leave empty if you want a reusable code for any driver you trust to join this business.',
    inviteExpiresIn: 'Expires in',
    sevenDays: '7 days',
    fourteenDays: '14 days',
    thirtyDays: '30 days',
    inviteCodeCopied: 'Invite code copied.',
    inviteLinkCopied: 'Invite link copied.',
    lastBusinessDeleteWarning: 'This is your last business. After deletion, your workspace will stay active but will have no companies until you create a new one.',
    deleteBusinessAccessWarning: 'Make sure no one still needs access to this business before you remove it.',
    statusExpired: 'Expired',
    availability: 'Availability',
    availabilityAvailable: 'Available',
    availabilityBusy: 'Busy',
    availabilityReadyHint: 'Ready to be assigned in the current business.',
    availabilityBusiness: 'Business',
    availabilityVehicle: 'Vehicle',
    availabilityService: 'Service',
    availabilityAssignedElsewhere: 'Currently assigned to another active trip.',
    uploadDriverLicensePhoto: 'Upload Driver License Photo',
    frontSide: 'Front Side',
    backSide: 'Back Side',
    iAgreeToThe: 'I agree to the',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    iConfirmAccurate: 'I confirm that all information provided is accurate.',
    askManagerForCode: 'Ask your fleet manager for the company invitation code.',
    min8Chars: 'Min 8 characters',
    repeatPassword: 'Repeat password',
    clickToUpload: 'Click to upload or drag & drop',
    pngJpgUpTo10mb: 'PNG, JPG up to 10 MB',
    jpgPng: 'JPG, PNG',

    // Landing page
    fleetOverview: 'Fleet Overview',
    preTripDone: 'Pre-Trip Done',
    allItemsPassed: 'All items passed',
    highPriority: 'High Priority',
    everythingYourFleetNeeds: 'Everything your fleet needs',
    fleetManagementSaasPlatform: 'Fleet Management SaaS Platform',
    landingSubtitle: 'Streamline pre-trip and post-trip inspections, manage your fleet, track vehicle conditions, photos, repairs, and stay compliant — all from one platform.',
    landingFeaturesIntro: 'From daily driver checklists to compliance reports, FleetCheck Pro keeps your entire fleet operation running smoothly.',
    inspectionsDaily: 'Inspections Daily',
    companies: 'Companies',
    uptime: 'Uptime',
    countries: 'Countries',
    digitalInspections: 'Digital Inspections',
    digitalInspectionsDesc: 'Pre-trip and post-trip checklists with photo capture and digital signatures.',
    fleetManagement: 'Fleet Management',
    fleetManagementDesc: 'Track all vehicles, equipment, and assets in one centralized dashboard.',
    complianceReady: 'Compliance Ready',
    complianceReadyDesc: 'DOT-compliant reports, driver logs, and exportable documentation.',
    photoEvidence: 'Photo Evidence',
    photoEvidenceDesc: 'Capture and store vehicle condition photos with duplicate detection.',
    repairTracking: 'Repair Tracking',
    repairTrackingDesc: 'Log issues, assign mechanics, and track repairs to completion.',
    analyticsReports: 'Analytics & Reports',
    analyticsReportsDesc: 'Actionable insights on fleet health, driver performance, and trends.',
    footerCopyright: '© 2026 FleetCheck Pro. All rights reserved.',

    // Industry types
    truckingCompany: 'Trucking Company',
    truckingCompanyDesc: 'Long-haul & regional trucking fleets',
    constructionEquipment: 'Construction Equipment',
    constructionEquipmentDesc: 'Excavators, bulldozers & heavy machinery',
    boomLiftRental: 'Boom Lift Rental',
    boomLiftRentalDesc: 'Aerial work platforms & lift equipment',
    deliveryFleet: 'Delivery Fleet',
    deliveryFleetDesc: 'Last-mile & courier delivery vehicles',
    taxiPassenger: 'Taxi / Passenger',
    taxiPassengerDesc: 'Ride-share & passenger transport fleets',
    serviceVehicles: 'Service Vehicles',
    serviceVehiclesDesc: 'Utility, maintenance & service fleets',
    otherFleet: 'Other',
    otherFleetDesc: 'Custom fleet type or mixed operations',
  },
  uk: {
    // App
    appName: 'FleetCheck Pro',
    tagline: 'Цифрові огляди транспортних засобів для безпечних автопарків',
    getStarted: 'Розпочати',
    companyLogin: 'Вхід для компанії',
    driverRegistration: 'Реєстрація водія',

    // Nav
    dashboard: 'Панель',
    vehicles: 'Транспорт',
    drivers: 'Водії',
    inspections: 'Огляди',
    reports: 'Звіти',
    issues: 'Проблеми',
    repairs: 'Ремонти',
    settings: 'Налаштування',
    home: 'Головна',
    inspect: 'Огляд',
    profile: 'Профіль',
    profilePhoto: 'Фото профілю',
    businessAccess: 'Доступ до бізнесів',
    switchBusiness: 'Перемкнути бізнес',
    joinAnotherBusiness: 'Приєднатися до іншого бізнесу',
    enterBusinessCode: 'Введіть код бізнесу',
    joinBusiness: 'Приєднатися до бізнесу',
    businessJoined: 'Бізнес успішно додано.',
    driverProfileUpdated: 'Профіль водія оновлено.',
    joinBusinessDriverOnly: 'Щоб приєднатися до іншого бізнесу, потрібно увійти як водій.',
    differentOwnerAccountError: 'Цей акаунт водія вже прив’язаний до іншого власника бізнесу.',
    driverProfileNotFound: 'Профіль водія не знайдено.',
    driverProfileSaveFailed: 'Не вдалося зберегти профіль водія.',
    driverDocumentsUploadFailed: 'Не вдалося завантажити документи водія.',
    joinBusinessFailed: 'Не вдалося приєднатися до бізнесу.',
    signInAndJoinBusiness: 'Увійти і приєднатися до цього бізнесу',
    driverDocumentsMustDiffer: 'Фото посвідчення і фото медичної картки мають бути різними файлами.',
    driverRemovedFromBusiness: 'Водія видалено з цього бізнесу.',
    uploadSignature: 'Завантажити підпис',
    signatureUploadHint: 'Збережіть чітке зображення підпису, щоб надалі використовувати його в цифрових формах.',
    signatureRequired: 'Щоб завершити реєстрацію, потрібно завантажити підпис водія.',
    pendingDueExpiredDocuments: 'Статус очікує, доки не буде оновлено протерміновані документи.',
    streetAddress: 'Вулиця та номер будинку',
    postalCode: 'ZIP / Поштовий індекс',
    useCurrentLocation: 'Використати поточне місцезнаходження',
    detectingLocation: 'Визначаємо місцезнаходження...',
    locationAutofillFailed: 'Не вдалося визначити адресу з цього пристрою. Введіть її вручну.',
    completeHighlightedFields: 'Заповніть підсвічені поля.',
    phoneMustMatchBusinessCountry: 'Номер телефону має відповідати формату країни бізнесу.',
    driverMustBe21ForCommercial: 'Для вантажних CDL-категорій водій має бути не молодше 21 року.',
    driverMustBe18: 'Водій має бути не молодше 18 років.',
    medicalCardMustBeFuture: 'Термін дії медичної картки має бути пізніше сьогоднішньої дати.',
    medicalCardMaxTwoYearsUs: 'Для бізнесів у США медична картка не може бути дійсною більш ніж на 2 роки від сьогодні.',
    medicalCardExpiryRuleUs: 'Для бізнесів у США медична картка має бути дійсною після сьогоднішньої дати і не більш ніж на 2 роки вперед.',
    medicalCardExpiryRuleGeneric: 'Термін дії медичної картки має бути пізніше сьогоднішньої дати.',
    hireDateCannotBeFuture: 'Дата прийому на роботу не може бути в майбутньому.',
    hireDateHint: 'Вкажіть дату, коли водій почав працювати в цьому бізнесі.',
    businessPhoneHint: 'Формат телефону відповідає країні бізнесу:',

    // Nav back links
    backToDrivers: 'До водіїв',
    backToFleet: 'До автопарку',
    backToLogin: 'До входу',
    backToInspection: 'До огляду',
    backToIssues: 'До проблем',
    backToRepairs: 'До ремонтів',
    backToDashboard: 'До панелі',

    // Auth
    login: 'Увійти',
    logout: 'Вийти',
    signIn: 'Увійти',
    signUp: 'Зареєструватись',
    createAccount: 'Створити акаунт',
    forgotPassword: 'Забули пароль?',
    alreadyHaveAccount: 'Вже є акаунт?',
    signInWithGoogle: 'Увійти через Google',
    signUpWithGoogle: 'Зареєструватись через Google',
    companyAccountRegistration: 'Реєстрація акаунту компанії',
    createYourCompanyAccount: 'Створіть акаунт компанії',
    signInToYourAccount: 'Увійдіть у свій акаунт',
    enterLoginCredentials: 'Введіть дані для входу.',
    or: 'або',
    atLeast8Chars: 'Мінімум 8 символів',
    passwordsDoNotMatch: 'Паролі не збігаються',
    passwordsMatch: 'Паролі збігаються',

    // Buttons
    save: 'Зберегти',
    cancel: 'Скасувати',
    submit: 'Надіслати',
    next: 'Далі',
    back: 'Назад',
    finish: 'Завершити',
    edit: 'Редагувати',
    delete: 'Видалити',
    saveChanges: 'Зберегти зміни',
    saveDriver: 'Зберегти водія',
    editDriver: 'Редагувати водія',
    addDriver: 'Додати водія',
    addVehicle: 'Додати транспорт',
    addPhoto: 'Додати фото',
    removePhoto: 'Видалити фото',
    editVehicle: 'Редагувати транспорт',
    editRepair: 'Редагувати ремонт',
    newRepairRequest: 'Нова заявка на ремонт',
    newRequest: 'Нова заявка',
    submitRequest: 'Подати заявку',
    saveReview: 'Зберегти перевірку',
    review: 'Перевірити',
    markAllOk: 'Позначити все OK',
    saveDraft: 'Зберегти чернетку',
    sendToRepair: 'Відправити в ремонт',
    rejectIssue: 'Відхилити проблему',
    blockVehicle: 'Заблокувати транспорт',
    markAsFixed: 'Позначити як виправлено',
    viewFullReport: 'Переглянути повний звіт',
    fixAndResubmit: 'Виправити та повторно надіслати',
    viewAll: 'Переглянути всі',
    openVehicleCard: 'Відкрити картку транспорту',
    goToLogin: 'До входу',
    backToHome: 'На головну',
    goToDashboard: 'До панелі',
    outOfService: 'Поза службою',
    restoreService: 'Відновити службу',
    signOut: 'Вийти',
    reportProblem: 'Повідомити про проблему',
    viewAllNotifications: 'Усі сповіщення',
    notifications: 'Сповіщення',
    new: 'нових',
    approveOk: 'Схвалити — OK',
    flagIssue: 'Позначити проблему',
    reviewInspection: 'Перевірити огляд',
    createDriverAccount: 'Створити акаунт водія',
    download: 'Завантажити',
    pdf: 'PDF',
    csv: 'CSV',
    email: 'Ел. пошта',

    // Form fields
    emailField: 'Ел. пошта',
    password: 'Пароль',
    confirmPassword: 'Підтвердити пароль',
    firstName: "Ім'я",
    lastName: 'Прізвище',
    phone: 'Телефон',
    dateOfBirth: 'Дата народження',
    homeAddress: 'Домашня адреса',
    address: 'Адреса',
    companyName: 'Назва компанії',
    industryType: 'Тип галузі',
    country: 'Країна',
    stateProvince: 'Область / Провінція',
    city: 'Місто',
    licenseNumber: 'Посвідчення №',
    licenseClass: 'Клас посвідчення',
    expiryDate: 'Дата закінчення',
    medicalCardNumber: 'Медична картка №',
    medicalCardPhoto: 'Фото медичної картки',
    licensePhoto: 'Фото посвідчення',
    hireDate: 'Дата прийому',
    driverAuthManagedByDriver: 'Email і пароль керуються з облікового запису водія.',
    notProvided: 'Не вказано',
    canBeAddedLater: 'Це поле власник або адміністратор може додати пізніше.',
    documentNotUploadedYet: 'Документ ще не завантажено.',
    temporaryPassword: 'Тимчасовий пароль',
    contactName: 'Контактна особа',
    contactPhone: 'Контактний телефон',
    vehicleNumber: 'Номер ТЗ',
    type: 'Тип',
    make: 'Марка',
    model: 'Модель',
    year: 'Рік',
    plateNumber: 'Номерний знак',
    vin: 'VIN',
    odometer: 'Одометр (км)',
    engineHours: 'Мотогодини',
    vehiclePhoto: 'Фото транспорту',
    repairTitle: 'Назва ремонту',
    description: 'Опис',
    issueCategory: 'Категорія проблеми',
    driver: 'Водій',
    relatedIssue: 'Пов\'язана проблема',
    startedAt: 'Розпочато',
    completedAt: 'Завершено',
    managersDecision: 'Рішення менеджера',
    managersNote: 'Примітка менеджера',
    managerNotes: 'Нотатки менеджера',
    invitationCode: 'Код запрошення',
    cardNumber: 'Картка №',
    class: 'Клас',
    language: 'Мова',
    theme: 'Тема',
    search: 'Пошук...',
    createdAt: 'Створено',
    view: 'Переглянути',
    inspectionLabel: 'Огляд',
    chooseLanguage: 'Оберіть мову відображення застосунку.',
    customizeAppearance: 'Налаштуйте вигляд FleetCheck Pro на вашому пристрої.',
    driverDashboard: 'Панель',
    checked: 'перевірено',
    okLabel: 'OK',
    issuesLabel: 'Проблеми',
    describeIssue: 'Опишіть проблему…',
    driverSignature: 'Підпис водія',
    documentsLabel: 'Документи',
    duration: 'Тривалість',
    photosTaken: 'Фото зроблено',
    fixResubmit: 'Виправити та подати',
    searchDrivers: 'Пошук водіїв...',
    searchVehicles: 'Пошук транспорту...',
    searchRepairs: 'Пошук ремонтів...',
    searchIssues: 'Пошук проблем...',

    // Section titles
    reportsCompliance: 'Звіти та відповідність',
    myReports: 'Мої звіти',
    fleetVehicles: 'Транспорт автопарку',
    repairRequests: 'Заявки на ремонт',
    inspectionResult: 'Результат огляду',
    issueDetails: 'Деталі проблеми',
    driverProfile: 'Профіль водія',
    vehicleDetail: 'Деталі транспорту',
    personalInformation: 'Особисті дані',
    emergencyContact: 'Екстрений контакт',
    driverLicense: 'Водійське посвідчення',
    medicalCard: 'Медична картка',
    employment: 'Зайнятість',
    companyProfile: 'Профіль компанії',
    fleetManager: 'Менеджер автопарку',
    companyInformation: 'Інформація про компанію',
    languageSettings: 'Налаштування мови',
    appearance: 'Зовнішній вигляд',
    repairInformation: 'Інформація про ремонт',
    basicInformation: 'Основна інформація',
    issueInformation: 'Інформація про проблему',
    photos: 'Фото',
    statusHistory: 'Історія статусів',
    inspectionSummary: 'Зведення огляду',
    failedItems: 'Виявлені проблеми',
    vehiclePhotos: 'Фото транспорту',
    inspectionHistory: 'Історія оглядів',
    repairHistory: 'Історія ремонтів',
    recentInspections: 'Останні огляди',
    availableVehicles: 'Доступний транспорт',
    recentReports: 'Останні звіти',
    inspectionsPendingReview: 'Огляди на перевірку',
    inspectionsThisWeek: 'Огляди цього тижня',
    issuesByCategory: 'Проблеми за категоріями',
    repairStatus: 'Статус ремонтів',
    startInspection: 'Почати огляд',
    allowedVehicleTypes: 'Дозволені типи транспорту',

    // Table headers
    date: 'Дата',
    vehicle: 'Транспорт',
    result: 'Результат',
    reviewStatus: 'Статус перевірки',
    actions: 'Дії',
    status: 'Статус',
    priority: 'Пріоритет',
    reportedBy: 'Хто повідомив',
    signature: 'Підпис',
    severity: 'Серйозність',
    unit: 'Одиниця',
    time: 'Час',
    plate: 'Номер',
    category: 'Категорія',
    issue: 'Проблема',
    licenseHash: 'Посвідчення №',
    licExpiry: 'Посвідчення до',
    medExpiry: 'Мед. картка до',
    allowedVehicles: 'Дозволений транспорт',
    inspectionType: 'Тип огляду',
    inspectionDate: 'Дата огляду',
    issueDate: 'Дата проблеми',
    currentStatus: 'Поточний статус',

    // Statuses
    statusActive: 'Активний',
    statusPending: 'Очікує',
    statusInactive: 'Неактивний',
    statusNeedsAttention: 'Потребує уваги',
    statusBlocked: 'Заблокований',
    statusInRepair: 'В ремонті',
    statusDraft: 'Чернетка',
    statusSubmitted: 'Надіслано',
    statusOpen: 'Відкрито',
    statusInProgress: 'В процесі',
    statusCompleted: 'Завершено',
    statusCancelled: 'Скасовано',
    statusUnderReview: 'На перевірці',
    statusFixed: 'Виправлено',
    statusRejected: 'Відхилено',
    statusNeedsReview: 'Потребує перевірки',
    statusReviewedOk: 'Перевірено OK',
    statusFlagged: 'Позначено',
    statusPassed: 'Пройдено',
    statusFailed: 'Не пройдено',

    // Priority / Severity
    priorityHigh: 'Високий',
    priorityMedium: 'Середній',
    priorityLow: 'Низький',

    // Filter dropdowns
    allStatus: 'Всі статуси',
    allTypes: 'Всі типи',
    allResults: 'Всі результати',
    allPriority: 'Всі пріоритети',
    allSeverity: 'Всі ступені',
    all: 'Всі',
    fraudFlagged: 'Підозра на шахрайство',
    clean: 'Чисто',
    selectType: 'Оберіть тип',
    selectClass: 'Оберіть клас',
    selectCategory: 'Оберіть категорію',
    selectVehicle: 'Оберіть транспорт',
    none: 'Немає',
    preTrip: 'До поїздки',
    postTrip: 'Після поїздки',

    // Inspections
    preTripInspection: 'Огляд до поїздки',
    postTripInspection: 'Огляд після поїздки',
    pass: 'Пройдено',
    fail: 'Не пройдено',
    na: 'Н/Д',
    addComment: 'Додати коментар',
    signHere: 'Підписати тут',
    submitInspection: 'Надіслати огляд',
    inspectionPassed: 'Огляд пройдено',
    inspectionFailed: 'Знайдено проблеми',
    vehicleReadyForOperation: 'Транспорт готовий до роботи. Усі пункти огляду пройдено.',
    issuesFoundMessage: 'проблем(и) виявлено. Потрібна перевірка менеджером перед використанням транспорту.',
    completedBeforeDeparting: 'Завершити до відправлення',
    completedAfterArriving: 'Завершити після прибуття',

    // Checklist categories
    tiresWheels: 'Шини та колеса',
    lightsSignals: 'Освітлення та сигнали',
    brakes: 'Гальма',
    fluidLevels: 'Рівень рідин',
    safetyEquipment: 'Засоби безпеки',
    documents: 'Документи',

    // Repair categories
    tires: 'Шини',
    lights: 'Освітлення',
    fluids: 'Рідини',
    engine: 'Двигун',
    exterior: 'Зовнішній вигляд',
    steering: 'Кермо',
    other: 'Інше',

    // Repair / Issue actions
    createRepairRequest: 'Створити заявку на ремонт',
    notifyManager: 'Повідомити менеджера',

    // Pending
    pendingApproval: 'Реєстрація очікує підтвердження',
    pendingMessage: 'Вашу реєстрацію подано. Очікуйте підтвердження менеджера.',
    whatHappensNext: 'Що далі?',
    managerWillReview: 'Менеджер перевірить вашу реєстрацію',
    youllReceiveEmail: 'Ви отримаєте email після схвалення',
    onceApprovedLogin: 'Після схвалення ви зможете увійти та починати огляди',

    // IssueDetail
    fraudFlaggedLabel: 'Підозра на шахрайство',
    vehicleBlockedLabel: 'Транспорт заблоковано',

    // Driver dashboard stats
    tripsThisMonth: 'Поїздок цього місяця',
    inspectionsPassed: 'Оглядів пройдено',
    openIssues: 'Відкриті проблеми',
    fuelEfficiency: 'Витрата пального',
    submitRepairRequest: 'Подати заявку на ремонт',
    logOutOfApp: 'Вийти з додатку',

    // Empty states
    noDriversFound: 'Водіїв не знайдено.',
    noVehiclesFound: 'Транспорт не знайдено.',
    noRepairsFound: 'Ремонтів не знайдено.',
    noReportsFound: 'Звітів не знайдено.',
    noIssuesFound: 'Проблем не знайдено.',
    issueNotFound: 'Проблему не знайдено.',
    noneAssigned: 'Не призначено',
    noPhotosAttached: 'Фото до цієї проблеми не додано',

    // Misc
    showing: 'Показано',
    of: 'з',
    lightMode: 'Світла тема',
    darkMode: 'Темна тема',
    selectLanguage: 'Оберіть мову',
    english: 'Англійська',
    ukrainian: 'Українська',
    spanish: 'Іспанська',
    french: 'Французька',

    // Registration
    workspaceReady: 'Ваш простір готовий!',
    workspaceSetupSuccess: 'Простір вашої компанії успішно налаштовано.',
    workspaceSetupInfo: 'Тепер ви можете додавати транспорт, запрошувати водіїв та керувати оглядами.',
    createYourAccount: 'Створіть акаунт',
    driverRegSubtitle: 'Створіть акаунт водія за допомогою коду запрошення компанії.',
    noGoogleAccountHint: 'Немає Google-акаунта? Створіть workspace через email і пароль, а потім входьте тут з тією ж поштою.',
    createAccountWithEmail: 'Створити акаунт через email',
    alreadyCreatedWorkspaceWithEmail: 'Ще немає акаунта компанії?',
    createItHere: 'Створити тут',
    verifyInvite: 'Перевірити',
    checkingInvite: 'Перевіряємо...',
    invitationFoundFor: 'Запрошення знайдено для',
    creating: 'Створення...',
    inviteDriver: 'Запросити водія',
    activeBusiness: 'Активний бізнес',
    driverInvitations: 'Запрошення водіїв',
    inviteDriversTo: 'Запросити водіїв до',
    driverInvitationsHelp: 'Водії використовують один код для вибраного бізнесу. За потреби ви можете змінити його в будь-який момент.',
    businessInviteCode: 'Код запрошення бізнесу',
    businessInviteCodeHelp: 'Надішліть цей код або посилання на реєстрацію водіям, які мають приєднатися до цього бізнесу.',
    driverRegistrationLink: 'Посилання на реєстрацію водія',
    openRegistrationPage: 'Відкрити сторінку реєстрації',
    approveDriver: 'Підтвердити водія',
    rejectDriver: 'Відхилити водія',
    driverApproved: 'Водія підтверджено.',
    driverRejected: 'Водія відхилено.',
    generateBusinessCode: 'Згенерувати код',
    rotateBusinessCode: 'Змінити код',
    noBusinessInviteCode: 'У цього бізнесу ще немає коду запрошення.',
    businessInviteCodeCreated: 'Код запрошення бізнесу створено.',
    businessInviteCodeUpdated: 'Код запрошення бізнесу оновлено.',
    newInvite: 'Нове запрошення',
    noDriverInvites: 'Для цього бізнесу ще немає коду запрошення.',
    invitationCodeLabel: 'Код запрошення',
    openInvitationForAnyEmail: 'Відкрите запрошення для будь-якої email-адреси водія',
    expires: 'Діє до',
    withoutExpiry: 'без строку дії',
    copyCode: 'Скопіювати код',
    copyLink: 'Скопіювати посилання',
    createDriverInvite: 'Створити запрошення водію',
    driverEmail: 'Email водія',
    inviteEmailHint: 'Залиште порожнім, якщо хочете створити багаторазовий код для будь-якого водія, якому довіряєте приєднатися до цього бізнесу.',
    inviteExpiresIn: 'Термін дії',
    sevenDays: '7 днів',
    fourteenDays: '14 днів',
    thirtyDays: '30 днів',
    inviteCodeCopied: 'Код запрошення скопійовано.',
    inviteLinkCopied: 'Посилання запрошення скопійовано.',
    lastBusinessDeleteWarning: 'Це ваш останній бізнес. Після видалення workspace залишиться активним, але без компаній, поки ви не створите нову.',
    deleteBusinessAccessWarning: 'Переконайтеся, що нікому більше не потрібен доступ до цього бізнесу перед видаленням.',
    statusExpired: 'Протерміновано',
    availability: 'Доступність',
    availabilityAvailable: 'Доступний',
    availabilityBusy: 'Зайнятий',
    availabilityReadyHint: 'Готовий до призначення в поточному бізнесі.',
    availabilityBusiness: 'Бізнес',
    availabilityVehicle: 'Транспорт',
    availabilityService: 'Сервіс',
    availabilityAssignedElsewhere: 'Зараз призначений на інший активний рейс.',
    uploadDriverLicensePhoto: 'Завантажте фото посвідчення водія',
    frontSide: 'Лицьова сторона',
    backSide: 'Зворотна сторона',
    iAgreeToThe: 'Я погоджуюсь з',
    termsOfService: 'Умовами використання',
    privacyPolicy: 'Політикою конфіденційності',
    iConfirmAccurate: 'Я підтверджую, що всі надані дані є точними.',
    askManagerForCode: 'Запитайте у менеджера автопарку код запрошення компанії.',
    min8Chars: 'Мін. 8 символів',
    repeatPassword: 'Повторіть пароль',
    clickToUpload: 'Натисніть або перетягніть файл',
    pngJpgUpTo10mb: 'PNG, JPG до 10 МБ',
    jpgPng: 'JPG, PNG',

    // Landing page
    fleetOverview: 'Огляд автопарку',
    preTripDone: 'Огляд виконано',
    allItemsPassed: 'Всі пункти пройдено',
    highPriority: 'Високий пріоритет',
    everythingYourFleetNeeds: 'Все, що потрібно вашому автопарку',
    fleetManagementSaasPlatform: 'SaaS-платформа для управління автопарком',
    landingSubtitle: 'Спростіть огляди до та після поїздок, керуйте автопарком, відстежуйте стан транспорту, фото, ремонти та залишайтесь відповідними — все в одній платформі.',
    landingFeaturesIntro: 'Від щоденних чеклістів водіїв до звітів про відповідність — FleetCheck Pro забезпечує безперебійну роботу всього вашого автопарку.',
    inspectionsDaily: 'Оглядів щодня',
    companies: 'Компаній',
    uptime: 'Безвідмовність',
    countries: 'Країн',
    digitalInspections: 'Цифрові огляди',
    digitalInspectionsDesc: 'Чеклісти до та після поїздок із фото та цифровими підписами.',
    fleetManagement: 'Управління автопарком',
    fleetManagementDesc: 'Відстежуйте всі транспортні засоби, обладнання та активи в одній централізованій панелі.',
    complianceReady: 'Відповідність вимогам',
    complianceReadyDesc: 'Звіти, що відповідають вимогам DOT, журнали водіїв та документація для експорту.',
    photoEvidence: 'Фотодокументація',
    photoEvidenceDesc: 'Знімайте та зберігайте фото стану транспорту з виявленням дублікатів.',
    repairTracking: 'Відстеження ремонтів',
    repairTrackingDesc: 'Фіксуйте проблеми, призначайте механіків та відстежуйте ремонти до завершення.',
    analyticsReports: 'Аналітика та звіти',
    analyticsReportsDesc: 'Практичні висновки про стан автопарку, продуктивність водіїв та тенденції.',
    footerCopyright: '© 2026 FleetCheck Pro. Всі права захищені.',

    // Industry types
    truckingCompany: 'Вантажні перевезення',
    truckingCompanyDesc: 'Далекобійні та регіональні вантажні автопарки',
    constructionEquipment: 'Будівельна техніка',
    constructionEquipmentDesc: 'Екскаватори, бульдозери та важка техніка',
    boomLiftRental: 'Оренда підйомників',
    boomLiftRentalDesc: 'Платформи для роботи на висоті та підйомне обладнання',
    deliveryFleet: 'Служба доставки',
    deliveryFleetDesc: 'Транспорт для доставки на останній милі та кур\'єрські служби',
    taxiPassenger: 'Таксі / Пасажирські',
    taxiPassengerDesc: 'Автопарки для таксі та пасажирських перевезень',
    serviceVehicles: 'Сервісні транспортні засоби',
    serviceVehiclesDesc: 'Комунальні, технічні та сервісні автопарки',
    otherFleet: 'Інше',
    otherFleetDesc: 'Нестандартний тип або змішані операції',
  },
  es: {
    // App
    appName: 'FleetCheck Pro',
    tagline: 'Inspecciones digitales de vehículos para flotas más seguras',
    getStarted: 'Comenzar',
    companyLogin: 'Acceso Empresa',
    driverRegistration: 'Registro de Conductor',

    // Nav
    dashboard: 'Panel',
    vehicles: 'Vehículos',
    drivers: 'Conductores',
    inspections: 'Inspecciones',
    reports: 'Reportes',
    issues: 'Problemas',
    repairs: 'Reparaciones',
    settings: 'Configuración',
    home: 'Inicio',
    inspect: 'Inspeccionar',
    profile: 'Perfil',
    profilePhoto: 'Foto de perfil',
    businessAccess: 'Acceso a negocios',
    switchBusiness: 'Cambiar negocio',
    joinAnotherBusiness: 'Unirse a otro negocio',
    enterBusinessCode: 'Ingrese el código del negocio',
    joinBusiness: 'Unirse al negocio',
    businessJoined: 'Negocio agregado correctamente.',
    driverProfileUpdated: 'Perfil del conductor actualizado.',
    joinBusinessDriverOnly: 'Debe iniciar sesión como conductor para unirse a otro negocio.',
    differentOwnerAccountError: 'Esta cuenta de conductor ya está vinculada a otro propietario.',
    driverProfileNotFound: 'Perfil del conductor no encontrado.',
    driverProfileSaveFailed: 'No se pudo guardar el perfil del conductor.',
    driverDocumentsUploadFailed: 'No se pudieron subir los documentos del conductor.',
    joinBusinessFailed: 'No se pudo unir al negocio.',
    signInAndJoinBusiness: 'Iniciar sesión y unirse a este negocio',
    driverDocumentsMustDiffer: 'La foto de la licencia y la foto de la tarjeta médica deben ser archivos distintos.',
    driverRemovedFromBusiness: 'El conductor fue eliminado de este negocio.',
    uploadSignature: 'Subir firma',
    signatureUploadHint: 'Guarde una imagen clara de la firma para reutilizarla en futuros formularios digitales.',
    signatureRequired: 'La firma del conductor es obligatoria para completar el registro.',
    pendingDueExpiredDocuments: 'Pendiente hasta que se renueven los documentos vencidos.',
    streetAddress: 'Dirección',
    postalCode: 'Código postal',
    useCurrentLocation: 'Usar ubicación actual',
    detectingLocation: 'Detectando ubicación...',
    locationAutofillFailed: 'No se pudo detectar su dirección desde este dispositivo. Ingrésela manualmente.',
    completeHighlightedFields: 'Complete los campos resaltados.',
    phoneMustMatchBusinessCountry: 'El número debe coincidir con el formato del país del negocio.',
    driverMustBe21ForCommercial: 'Los conductores con licencias CDL de camión deben tener al menos 21 años.',
    driverMustBe18: 'El conductor debe tener al menos 18 años.',
    medicalCardMustBeFuture: 'La fecha de vencimiento de la tarjeta médica debe ser posterior a hoy.',
    medicalCardMaxTwoYearsUs: 'Para empresas de EE. UU., la tarjeta médica no puede vencer más de 2 años desde hoy.',
    medicalCardExpiryRuleUs: 'Para empresas de EE. UU., la tarjeta médica debe vencer después de hoy y dentro de 2 años.',
    medicalCardExpiryRuleGeneric: 'La fecha de vencimiento de la tarjeta médica debe ser posterior a hoy.',
    hireDateCannotBeFuture: 'La fecha de contratación no puede estar en el futuro.',
    hireDateHint: 'Indique la fecha en que el conductor empezó a trabajar para esta empresa.',
    businessPhoneHint: 'El formato del teléfono sigue el país del negocio:',

    // Nav back links
    backToDrivers: 'Volver a Conductores',
    backToFleet: 'Volver a la Flota',
    backToLogin: 'Volver al Inicio de Sesión',
    backToInspection: 'Volver a Inspección',
    backToIssues: 'Volver a Problemas',
    backToRepairs: 'Volver a Reparaciones',
    backToDashboard: 'Volver al Panel',

    // Auth
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    createAccount: 'Crear Cuenta',
    forgotPassword: '¿Olvidó su contraseña?',
    alreadyHaveAccount: '¿Ya tiene una cuenta?',
    signInWithGoogle: 'Iniciar sesión con Google',
    signUpWithGoogle: 'Registrarse con Google',
    companyAccountRegistration: 'Registro de cuenta empresarial',
    createYourCompanyAccount: 'Cree su cuenta empresarial',
    signInToYourAccount: 'Inicie sesión en su cuenta',
    enterLoginCredentials: 'Ingrese sus credenciales para comenzar.',
    or: 'o',
    atLeast8Chars: 'Al menos 8 caracteres',
    passwordsDoNotMatch: 'Las contraseñas no coinciden',
    passwordsMatch: 'Las contraseñas coinciden',

    // Buttons
    save: 'Guardar',
    cancel: 'Cancelar',
    submit: 'Enviar',
    next: 'Siguiente',
    back: 'Atrás',
    finish: 'Finalizar',
    edit: 'Editar',
    delete: 'Eliminar',
    saveChanges: 'Guardar Cambios',
    saveDriver: 'Guardar Conductor',
    editDriver: 'Editar Conductor',
    addDriver: 'Agregar Conductor',
    addVehicle: 'Agregar Vehículo',
    addPhoto: 'Agregar Foto',
    removePhoto: 'Eliminar foto',
    editVehicle: 'Editar Vehículo',
    editRepair: 'Editar Reparación',
    newRepairRequest: 'Nueva Solicitud de Reparación',
    newRequest: 'Nueva Solicitud',
    submitRequest: 'Enviar Solicitud',
    saveReview: 'Guardar Revisión',
    review: 'Revisar',
    markAllOk: 'Marcar todo OK',
    saveDraft: 'Guardar Borrador',
    sendToRepair: 'Enviar a Reparación',
    rejectIssue: 'Rechazar Problema',
    blockVehicle: 'Bloquear Vehículo',
    markAsFixed: 'Marcar como Reparado',
    viewFullReport: 'Ver Reporte Completo',
    fixAndResubmit: 'Corregir y Reenviar',
    viewAll: 'Ver todos',
    openVehicleCard: 'Abrir Ficha del Vehículo',
    goToLogin: 'Ir al Inicio de Sesión',
    backToHome: 'Volver al Inicio',
    goToDashboard: 'Ir al Panel',
    outOfService: 'Fuera de Servicio',
    restoreService: 'Restaurar Servicio',
    signOut: 'Cerrar Sesión',
    reportProblem: 'Reportar Problema',
    viewAllNotifications: 'Ver todas las notificaciones',
    notifications: 'Notificaciones',
    new: 'nuevas',
    approveOk: 'Aprobar — OK',
    flagIssue: 'Marcar Problema',
    reviewInspection: 'Revisar Inspección',
    createDriverAccount: 'Crear Cuenta de Conductor',
    download: 'Descargar',
    pdf: 'PDF',
    csv: 'CSV',
    email: 'Correo electrónico',

    // Form fields
    emailField: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    dateOfBirth: 'Fecha de Nacimiento',
    homeAddress: 'Dirección de Casa',
    address: 'Dirección',
    companyName: 'Nombre de la Empresa',
    industryType: 'Tipo de Industria',
    country: 'País',
    stateProvince: 'Estado / Provincia',
    city: 'Ciudad',
    licenseNumber: 'Licencia №',
    licenseClass: 'Clase de Licencia',
    expiryDate: 'Fecha de Vencimiento',
    medicalCardNumber: 'Tarjeta Médica №',
    medicalCardPhoto: 'Foto de Tarjeta Médica',
    licensePhoto: 'Foto de Licencia',
    hireDate: 'Fecha de Contratación',
    driverAuthManagedByDriver: 'El correo y la contraseña se gestionan desde la cuenta del conductor.',
    notProvided: 'No especificado',
    canBeAddedLater: 'El propietario o administrador puede agregarlo más tarde.',
    documentNotUploadedYet: 'El documento aún no se ha subido.',
    temporaryPassword: 'Contraseña Temporal',
    contactName: 'Nombre de Contacto',
    contactPhone: 'Teléfono de Contacto',
    vehicleNumber: 'Número de Vehículo',
    type: 'Tipo',
    make: 'Marca',
    model: 'Modelo',
    year: 'Año',
    plateNumber: 'Número de Placa',
    vin: 'VIN',
    odometer: 'Odómetro (mi)',
    engineHours: 'Horas de Motor',
    vehiclePhoto: 'Foto del Vehículo',
    repairTitle: 'Título de Reparación',
    description: 'Descripción',
    issueCategory: 'Categoría del Problema',
    driver: 'Conductor',
    relatedIssue: 'Problema Relacionado',
    startedAt: 'Iniciado En',
    completedAt: 'Completado En',
    managersDecision: 'Decisión del Gerente',
    managersNote: 'Nota del Gerente',
    managerNotes: 'Notas del Gerente',
    invitationCode: 'Código de Invitación',
    cardNumber: 'Tarjeta №',
    class: 'Clase',
    language: 'Idioma',
    theme: 'Tema',
    search: 'Buscar...',
    createdAt: 'Creado El',
    view: 'Ver',
    inspectionLabel: 'Inspección',
    chooseLanguage: 'Elige el idioma de visualización de la aplicación.',
    customizeAppearance: 'Personaliza cómo se ve FleetCheck Pro en tu dispositivo.',
    driverDashboard: 'Panel',
    checked: 'verificados',
    okLabel: 'OK',
    issuesLabel: 'Problemas',
    describeIssue: 'Describe el problema…',
    driverSignature: 'Firma del Conductor',
    documentsLabel: 'Documentos',
    duration: 'Duración',
    photosTaken: 'Fotos tomadas',
    fixResubmit: 'Corregir y Reenviar',
    searchDrivers: 'Buscar conductores...',
    searchVehicles: 'Buscar vehículos...',
    searchRepairs: 'Buscar reparaciones...',
    searchIssues: 'Buscar problemas...',

    // Section titles
    reportsCompliance: 'Reportes y Cumplimiento',
    myReports: 'Mis Reportes',
    fleetVehicles: 'Vehículos de la Flota',
    repairRequests: 'Solicitudes de Reparación',
    inspectionResult: 'Resultado de Inspección',
    issueDetails: 'Detalles del Problema',
    driverProfile: 'Perfil del Conductor',
    vehicleDetail: 'Detalle del Vehículo',
    personalInformation: 'Información Personal',
    emergencyContact: 'Contacto de Emergencia',
    driverLicense: 'Licencia de Conducir',
    medicalCard: 'Tarjeta Médica',
    employment: 'Empleo',
    companyProfile: 'Perfil de la Empresa',
    fleetManager: 'Gerente de Flota',
    companyInformation: 'Información de la Empresa',
    languageSettings: 'Configuración de Idioma',
    appearance: 'Apariencia',
    repairInformation: 'Información de Reparación',
    basicInformation: 'Información Básica',
    issueInformation: 'Información del Problema',
    photos: 'Fotos',
    statusHistory: 'Historial de Estado',
    inspectionSummary: 'Resumen de Inspección',
    failedItems: 'Elementos Fallidos',
    vehiclePhotos: 'Fotos del Vehículo',
    inspectionHistory: 'Historial de Inspecciones',
    repairHistory: 'Historial de Reparaciones',
    recentInspections: 'Inspecciones Recientes',
    availableVehicles: 'Vehículos Disponibles',
    recentReports: 'Reportes Recientes',
    inspectionsPendingReview: 'Inspecciones Pendientes de Revisión',
    inspectionsThisWeek: 'Inspecciones Esta Semana',
    issuesByCategory: 'Problemas por Categoría',
    repairStatus: 'Estado de Reparaciones',
    startInspection: 'Iniciar Inspección',
    allowedVehicleTypes: 'Tipos de Vehículos Permitidos',

    // Table headers
    date: 'Fecha',
    vehicle: 'Vehículo',
    result: 'Resultado',
    reviewStatus: 'Estado de Revisión',
    actions: 'Acciones',
    status: 'Estado',
    priority: 'Prioridad',
    reportedBy: 'Reportado Por',
    signature: 'Firma',
    severity: 'Severidad',
    unit: 'Unidad',
    time: 'Hora',
    plate: 'Placa',
    category: 'Categoría',
    issue: 'Problema',
    licenseHash: 'Licencia №',
    licExpiry: 'Venc. Licencia',
    medExpiry: 'Venc. Médico',
    allowedVehicles: 'Vehículos Permitidos',
    inspectionType: 'Tipo de Inspección',
    inspectionDate: 'Fecha de Inspección',
    issueDate: 'Fecha del Problema',
    currentStatus: 'Estado Actual',

    // Statuses
    statusActive: 'Activo',
    statusPending: 'Pendiente',
    statusInactive: 'Inactivo',
    statusNeedsAttention: 'Necesita Atención',
    statusBlocked: 'Bloqueado',
    statusInRepair: 'En Reparación',
    statusDraft: 'Borrador',
    statusSubmitted: 'Enviado',
    statusOpen: 'Abierto',
    statusInProgress: 'En Progreso',
    statusCompleted: 'Completado',
    statusCancelled: 'Cancelado',
    statusUnderReview: 'En Revisión',
    statusFixed: 'Reparado',
    statusRejected: 'Rechazado',
    statusNeedsReview: 'Necesita Revisión',
    statusReviewedOk: 'Revisado OK',
    statusFlagged: 'Marcado',
    statusPassed: 'Aprobado',
    statusFailed: 'Fallido',

    // Priority / Severity
    priorityHigh: 'Alto',
    priorityMedium: 'Medio',
    priorityLow: 'Bajo',

    // Filter dropdowns
    allStatus: 'Todos los Estados',
    allTypes: 'Todos los Tipos',
    allResults: 'Todos los Resultados',
    allPriority: 'Todas las Prioridades',
    allSeverity: 'Todas las Severidades',
    all: 'Todos',
    fraudFlagged: 'Fraude Marcado',
    clean: 'Limpio',
    selectType: 'Seleccionar tipo',
    selectClass: 'Seleccionar clase',
    selectCategory: 'Seleccionar categoría',
    selectVehicle: 'Seleccionar vehículo',
    none: 'Ninguno',
    preTrip: 'Pre-Viaje',
    postTrip: 'Post-Viaje',

    // Inspections
    preTripInspection: 'Inspección Pre-Viaje',
    postTripInspection: 'Inspección Post-Viaje',
    pass: 'Aprobado',
    fail: 'Fallido',
    na: 'N/A',
    addComment: 'Agregar Comentario',
    signHere: 'Firmar aquí',
    submitInspection: 'Enviar Inspección',
    inspectionPassed: 'Inspección Aprobada',
    inspectionFailed: 'Problemas Encontrados',
    vehicleReadyForOperation: 'El vehículo está listo para operar. Todos los elementos de inspección aprobados.',
    issuesFoundMessage: 'problema(s) encontrado(s). Se requiere revisión del gerente antes de operar este vehículo.',
    completedBeforeDeparting: 'Completar antes de salir',
    completedAfterArriving: 'Completar al llegar',

    // Checklist categories
    tiresWheels: 'Neumáticos y Ruedas',
    lightsSignals: 'Luces y Señales',
    brakes: 'Frenos',
    fluidLevels: 'Niveles de Fluidos',
    safetyEquipment: 'Equipo de Seguridad',
    documents: 'Documentos',

    // Repair categories
    tires: 'Neumáticos',
    lights: 'Luces',
    fluids: 'Fluidos',
    engine: 'Motor',
    exterior: 'Exterior',
    steering: 'Dirección',
    other: 'Otro',

    // Repair / Issue actions
    createRepairRequest: 'Crear Solicitud de Reparación',
    notifyManager: 'Notificar al Gerente',

    // Pending
    pendingApproval: 'Registro Pendiente de Aprobación',
    pendingMessage: 'Su registro ha sido enviado. Espere la aprobación del gerente.',
    whatHappensNext: '¿Qué sigue?',
    managerWillReview: 'Su gerente revisará su registro',
    youllReceiveEmail: 'Recibirá un correo cuando sea aprobado',
    onceApprovedLogin: 'Una vez aprobado, puede iniciar sesión y comenzar inspecciones',

    // IssueDetail
    fraudFlaggedLabel: 'Fraude Marcado',
    vehicleBlockedLabel: 'Vehículo Bloqueado',

    // Driver dashboard stats
    tripsThisMonth: 'Viajes Este Mes',
    inspectionsPassed: 'Inspecciones Aprobadas',
    openIssues: 'Problemas Abiertos',
    fuelEfficiency: 'Eficiencia de Combustible',
    submitRepairRequest: 'Enviar solicitud de reparación',
    logOutOfApp: 'Cerrar sesión de la app',

    // Empty states
    noDriversFound: 'No se encontraron conductores.',
    noVehiclesFound: 'No se encontraron vehículos.',
    noRepairsFound: 'No se encontraron reparaciones.',
    noReportsFound: 'No se encontraron reportes.',
    noIssuesFound: 'No se encontraron problemas.',
    issueNotFound: 'Problema no encontrado.',
    noneAssigned: 'Ninguno asignado',
    noPhotosAttached: 'No hay fotos adjuntas a este problema',

    // Misc
    showing: 'Mostrando',
    of: 'de',
    lightMode: 'Modo Claro',
    darkMode: 'Modo Oscuro',
    selectLanguage: 'Seleccionar idioma',
    english: 'Inglés',
    ukrainian: 'Ucraniano',
    spanish: 'Español',
    french: 'Francés',

    // Registration
    workspaceReady: '¡Su espacio está listo!',
    workspaceSetupSuccess: 'Su espacio empresarial ha sido configurado exitosamente.',
    workspaceSetupInfo: 'Ahora puede agregar vehículos, invitar conductores y comenzar a gestionar inspecciones.',
    createYourAccount: 'Cree Su Cuenta',
    driverRegSubtitle: 'Cree su cuenta de conductor usando el código de invitación de su empresa.',
    noGoogleAccountHint: '¿No tiene cuenta de Google? Cree un espacio de trabajo con su correo y contraseña, y luego inicie sesión aquí con ese mismo correo.',
    createAccountWithEmail: 'Crear cuenta con correo',
    alreadyCreatedWorkspaceWithEmail: '¿Aún no tiene cuenta de empresa?',
    createItHere: 'Créela aquí',
    verifyInvite: 'Verificar',
    checkingInvite: 'Verificando...',
    invitationFoundFor: 'Invitación encontrada para',
    creating: 'Creando...',
    inviteDriver: 'Invitar conductor',
    activeBusiness: 'Negocio activo',
    driverInvitations: 'Invitaciones de conductores',
    inviteDriversTo: 'Invitar conductores a',
    driverInvitationsHelp: 'Los conductores usan un solo código para el negocio seleccionado. Puede cambiarlo en cualquier momento si necesita reemplazar el actual.',
    businessInviteCode: 'Código de invitación del negocio',
    businessInviteCodeHelp: 'Comparta este código o el enlace de registro con los conductores que deben unirse a este negocio.',
    driverRegistrationLink: 'Enlace de registro del conductor',
    openRegistrationPage: 'Abrir página de registro',
    approveDriver: 'Aprobar conductor',
    rejectDriver: 'Rechazar conductor',
    driverApproved: 'Conductor aprobado.',
    driverRejected: 'Conductor rechazado.',
    generateBusinessCode: 'Generar código',
    rotateBusinessCode: 'Cambiar código',
    noBusinessInviteCode: 'Este negocio todavía no tiene código de invitación.',
    businessInviteCodeCreated: 'Código de invitación del negocio creado.',
    businessInviteCodeUpdated: 'Código de invitación del negocio actualizado.',
    newInvite: 'Nueva invitación',
    noDriverInvites: 'Todavía no hay código de invitación para este negocio.',
    invitationCodeLabel: 'Código de invitación',
    openInvitationForAnyEmail: 'Invitación abierta para cualquier correo de conductor',
    expires: 'Expira',
    withoutExpiry: 'sin vencimiento',
    copyCode: 'Copiar código',
    copyLink: 'Copiar enlace',
    createDriverInvite: 'Crear invitación de conductor',
    driverEmail: 'Correo del conductor',
    inviteEmailHint: 'Déjelo vacío si desea un código reutilizable para cualquier conductor de confianza que se una a este negocio.',
    inviteExpiresIn: 'Vence en',
    sevenDays: '7 días',
    fourteenDays: '14 días',
    thirtyDays: '30 días',
    inviteCodeCopied: 'Código de invitación copiado.',
    inviteLinkCopied: 'Enlace de invitación copiado.',
    lastBusinessDeleteWarning: 'Este es su último negocio. Después de eliminarlo, su espacio de trabajo seguirá activo pero sin empresas hasta que cree una nueva.',
    deleteBusinessAccessWarning: 'Asegúrese de que nadie más necesite acceso a este negocio antes de eliminarlo.',
    statusExpired: 'Vencido',
    availability: 'Disponibilidad',
    availabilityAvailable: 'Disponible',
    availabilityBusy: 'Ocupado',
    availabilityReadyHint: 'Listo para ser asignado en el negocio actual.',
    availabilityBusiness: 'Negocio',
    availabilityVehicle: 'Vehículo',
    availabilityService: 'Servicio',
    availabilityAssignedElsewhere: 'Actualmente asignado a otro viaje activo.',
    uploadDriverLicensePhoto: 'Subir Foto de Licencia de Conducir',
    frontSide: 'Lado Frontal',
    backSide: 'Lado Trasero',
    iAgreeToThe: 'Acepto los',
    termsOfService: 'Términos de Servicio',
    privacyPolicy: 'Política de Privacidad',
    iConfirmAccurate: 'Confirmo que toda la información proporcionada es precisa.',
    askManagerForCode: 'Solicite a su gerente de flota el código de invitación de la empresa.',
    min8Chars: 'Mín. 8 caracteres',
    repeatPassword: 'Repetir contraseña',
    clickToUpload: 'Haga clic para subir o arrastre y suelte',
    pngJpgUpTo10mb: 'PNG, JPG hasta 10 MB',
    jpgPng: 'JPG, PNG',

    // Landing page
    fleetOverview: 'Resumen de Flota',
    preTripDone: 'Pre-Viaje Completado',
    allItemsPassed: 'Todos los elementos aprobados',
    highPriority: 'Alta Prioridad',
    everythingYourFleetNeeds: 'Todo lo que su flota necesita',
    fleetManagementSaasPlatform: 'Plataforma SaaS de Gestión de Flotas',
    landingSubtitle: 'Simplifique las inspecciones pre y post viaje, gestione su flota, rastree condiciones de vehículos, fotos, reparaciones y manténgase en cumplimiento — todo en una plataforma.',
    landingFeaturesIntro: 'Desde listas de verificación diarias de conductores hasta informes de cumplimiento, FleetCheck Pro mantiene toda su operación de flota funcionando sin problemas.',
    inspectionsDaily: 'Inspecciones Diarias',
    companies: 'Empresas',
    uptime: 'Disponibilidad',
    countries: 'Países',
    digitalInspections: 'Inspecciones Digitales',
    digitalInspectionsDesc: 'Listas de verificación pre y post viaje con captura de fotos y firmas digitales.',
    fleetManagement: 'Gestión de Flota',
    fleetManagementDesc: 'Rastree todos los vehículos, equipos y activos en un panel centralizado.',
    complianceReady: 'Listo para el Cumplimiento',
    complianceReadyDesc: 'Reportes conformes con DOT, registros de conductores y documentación exportable.',
    photoEvidence: 'Evidencia Fotográfica',
    photoEvidenceDesc: 'Capture y almacene fotos del estado del vehículo con detección de duplicados.',
    repairTracking: 'Seguimiento de Reparaciones',
    repairTrackingDesc: 'Registre problemas, asigne mecánicos y rastree reparaciones hasta su finalización.',
    analyticsReports: 'Analítica e Informes',
    analyticsReportsDesc: 'Información procesable sobre la salud de la flota, rendimiento de conductores y tendencias.',
    footerCopyright: '© 2026 FleetCheck Pro. Todos los derechos reservados.',

    // Industry types
    truckingCompany: 'Empresa de Transporte',
    truckingCompanyDesc: 'Flotas de camiones de larga distancia y regionales',
    constructionEquipment: 'Equipo de Construcción',
    constructionEquipmentDesc: 'Excavadoras, bulldozers y maquinaria pesada',
    boomLiftRental: 'Alquiler de Elevadores',
    boomLiftRentalDesc: 'Plataformas de trabajo aéreo y equipos de elevación',
    deliveryFleet: 'Flota de Entregas',
    deliveryFleetDesc: 'Vehículos de entrega de última milla y servicio de mensajería',
    taxiPassenger: 'Taxi / Pasajeros',
    taxiPassengerDesc: 'Flotas de transporte compartido y de pasajeros',
    serviceVehicles: 'Vehículos de Servicio',
    serviceVehiclesDesc: 'Flotas utilitarias, de mantenimiento y servicio',
    otherFleet: 'Otro',
    otherFleetDesc: 'Tipo de flota personalizado u operaciones mixtas',
  },
  fr: {
    // App
    appName: 'FleetCheck Pro',
    tagline: 'Inspections numériques de véhicules pour des flottes plus sûres',
    getStarted: 'Commencer',
    companyLogin: 'Connexion Entreprise',
    driverRegistration: 'Inscription Conducteur',

    // Nav
    dashboard: 'Tableau de bord',
    vehicles: 'Véhicules',
    drivers: 'Conducteurs',
    inspections: 'Inspections',
    reports: 'Rapports',
    issues: 'Problèmes',
    repairs: 'Réparations',
    settings: 'Paramètres',
    home: 'Accueil',
    inspect: 'Inspecter',
    profile: 'Profil',
    profilePhoto: 'Photo de profil',
    businessAccess: 'Accès aux entreprises',
    switchBusiness: 'Changer d’entreprise',
    joinAnotherBusiness: 'Rejoindre une autre entreprise',
    enterBusinessCode: "Entrez le code de l'entreprise",
    joinBusiness: "Rejoindre l'entreprise",
    businessJoined: "Entreprise ajoutée avec succès.",
    driverProfileUpdated: 'Profil du conducteur mis à jour.',
    joinBusinessDriverOnly: "Vous devez être connecté en tant que conducteur pour rejoindre une autre entreprise.",
    differentOwnerAccountError: "Ce compte conducteur est déjà lié à un autre propriétaire d'entreprise.",
    driverProfileNotFound: 'Profil du conducteur introuvable.',
    driverProfileSaveFailed: 'Impossible d’enregistrer le profil du conducteur.',
    driverDocumentsUploadFailed: 'Impossible de téléverser les documents du conducteur.',
    joinBusinessFailed: 'Impossible de rejoindre cette entreprise.',
    signInAndJoinBusiness: 'Se connecter et rejoindre cette entreprise',
    driverDocumentsMustDiffer: 'La photo du permis et la photo de la carte médicale doivent être des fichiers différents.',
    driverRemovedFromBusiness: 'Le conducteur a été retiré de cette entreprise.',
    uploadSignature: 'Téléverser la signature',
    signatureUploadHint: 'Enregistrez une image de signature claire pour la réutiliser sur les futurs formulaires numériques.',
    signatureRequired: 'La signature du conducteur est requise pour finaliser l’inscription.',
    pendingDueExpiredDocuments: 'En attente jusqu’au renouvellement des documents expirés.',
    streetAddress: 'Adresse',
    postalCode: 'Code postal',
    useCurrentLocation: 'Utiliser la position actuelle',
    detectingLocation: 'Localisation en cours...',
    locationAutofillFailed: 'Impossible de détecter votre adresse depuis cet appareil. Saisissez-la manuellement.',
    completeHighlightedFields: 'Complétez les champs surlignés.',
    phoneMustMatchBusinessCountry: 'Le numéro doit respecter le format du pays de l’entreprise.',
    driverMustBe21ForCommercial: 'Les conducteurs avec une catégorie camion CDL doivent avoir au moins 21 ans.',
    driverMustBe18: 'Le conducteur doit avoir au moins 18 ans.',
    medicalCardMustBeFuture: 'La date d’expiration de la carte médicale doit être postérieure à aujourd’hui.',
    medicalCardMaxTwoYearsUs: 'Pour les entreprises américaines, la carte médicale ne peut pas dépasser 2 ans à partir d’aujourd’hui.',
    medicalCardExpiryRuleUs: 'Pour les entreprises américaines, la carte médicale doit expirer après aujourd’hui et dans un délai maximal de 2 ans.',
    medicalCardExpiryRuleGeneric: 'La date d’expiration de la carte médicale doit être postérieure à aujourd’hui.',
    hireDateCannotBeFuture: 'La date d’embauche ne peut pas être dans le futur.',
    hireDateHint: 'Indiquez la date à laquelle le conducteur a commencé à travailler pour cette entreprise.',
    businessPhoneHint: 'Le format du téléphone suit le pays de l’entreprise :',

    // Nav back links
    backToDrivers: 'Retour aux Conducteurs',
    backToFleet: 'Retour à la Flotte',
    backToLogin: 'Retour à la Connexion',
    backToInspection: "Retour à l'Inspection",
    backToIssues: 'Retour aux Problèmes',
    backToRepairs: 'Retour aux Réparations',
    backToDashboard: 'Retour au Tableau de bord',

    // Auth
    login: 'Connexion',
    logout: 'Déconnexion',
    signIn: 'Se connecter',
    signUp: "S'inscrire",
    createAccount: 'Créer un Compte',
    forgotPassword: 'Mot de passe oublié?',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    signInWithGoogle: 'Se connecter avec Google',
    signUpWithGoogle: "S'inscrire avec Google",
    companyAccountRegistration: 'Inscription compte entreprise',
    createYourCompanyAccount: 'Créez votre compte entreprise',
    signInToYourAccount: 'Connectez-vous à votre compte',
    enterLoginCredentials: 'Entrez vos identifiants pour commencer.',
    or: 'ou',
    atLeast8Chars: 'Au moins 8 caractères',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    passwordsMatch: 'Les mots de passe correspondent',

    // Buttons
    save: 'Enregistrer',
    cancel: 'Annuler',
    submit: 'Soumettre',
    next: 'Suivant',
    back: 'Retour',
    finish: 'Terminer',
    edit: 'Modifier',
    delete: 'Supprimer',
    saveChanges: 'Enregistrer les Modifications',
    saveDriver: 'Enregistrer le Conducteur',
    editDriver: 'Modifier le Conducteur',
    addDriver: 'Ajouter un Conducteur',
    addVehicle: 'Ajouter un Véhicule',
    addPhoto: 'Ajouter une Photo',
    removePhoto: 'Supprimer la photo',
    editVehicle: 'Modifier le Véhicule',
    editRepair: 'Modifier la Réparation',
    newRepairRequest: 'Nouvelle Demande de Réparation',
    newRequest: 'Nouvelle Demande',
    submitRequest: 'Soumettre la Demande',
    saveReview: 'Enregistrer la Révision',
    review: 'Réviser',
    markAllOk: 'Tout marquer OK',
    saveDraft: 'Enregistrer le Brouillon',
    sendToRepair: 'Envoyer en Réparation',
    rejectIssue: 'Rejeter le Problème',
    blockVehicle: 'Bloquer le Véhicule',
    markAsFixed: 'Marquer comme Réparé',
    viewFullReport: 'Voir le Rapport Complet',
    fixAndResubmit: 'Corriger et Resoumettre',
    viewAll: 'Voir tout',
    openVehicleCard: 'Ouvrir la Fiche du Véhicule',
    goToLogin: 'Aller à la Connexion',
    backToHome: "Retour à l'Accueil",
    goToDashboard: 'Aller au Tableau de bord',
    outOfService: 'Hors Service',
    restoreService: 'Restaurer le Service',
    signOut: 'Se Déconnecter',
    reportProblem: 'Signaler un Problème',
    viewAllNotifications: 'Voir toutes les notifications',
    notifications: 'Notifications',
    new: 'nouvelles',
    approveOk: 'Approuver — OK',
    flagIssue: 'Signaler le Problème',
    reviewInspection: "Réviser l'Inspection",
    createDriverAccount: 'Créer un Compte Conducteur',
    download: 'Télécharger',
    pdf: 'PDF',
    csv: 'CSV',
    email: 'E-mail',

    // Form fields
    emailField: 'E-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le Mot de passe',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    phone: 'Téléphone',
    dateOfBirth: 'Date de Naissance',
    homeAddress: 'Adresse du Domicile',
    address: 'Adresse',
    companyName: "Nom de l'Entreprise",
    industryType: "Type d'Industrie",
    country: 'Pays',
    stateProvince: 'État / Province',
    city: 'Ville',
    licenseNumber: 'Permis №',
    licenseClass: 'Classe de Permis',
    expiryDate: "Date d'Expiration",
    medicalCardNumber: 'Carte Médicale №',
    medicalCardPhoto: 'Photo de Carte Médicale',
    licensePhoto: 'Photo du Permis',
    hireDate: "Date d'Embauche",
    driverAuthManagedByDriver: 'L’e-mail et le mot de passe sont gérés depuis le compte du conducteur.',
    notProvided: 'Non renseigné',
    canBeAddedLater: "Le propriétaire ou l'administrateur peut l'ajouter plus tard.",
    documentNotUploadedYet: 'Document non téléversé pour le moment.',
    temporaryPassword: 'Mot de passe Temporaire',
    contactName: 'Nom du Contact',
    contactPhone: 'Téléphone du Contact',
    vehicleNumber: 'Numéro du Véhicule',
    type: 'Type',
    make: 'Marque',
    model: 'Modèle',
    year: 'Année',
    plateNumber: "Numéro d'Immatriculation",
    vin: 'NIV',
    odometer: 'Odomètre (km)',
    engineHours: 'Heures Moteur',
    vehiclePhoto: 'Photo du Véhicule',
    repairTitle: 'Titre de la Réparation',
    description: 'Description',
    issueCategory: 'Catégorie du Problème',
    driver: 'Conducteur',
    relatedIssue: 'Problème Associé',
    startedAt: 'Commencé le',
    completedAt: 'Terminé le',
    managersDecision: 'Décision du Gestionnaire',
    managersNote: 'Note du Gestionnaire',
    managerNotes: 'Notes du Gestionnaire',
    invitationCode: "Code d'Invitation",
    cardNumber: 'Carte №',
    class: 'Classe',
    language: 'Langue',
    theme: 'Thème',
    search: 'Rechercher...',
    createdAt: 'Créé le',
    view: 'Voir',
    inspectionLabel: 'Inspection',
    chooseLanguage: "Choisissez la langue d'affichage de l'application.",
    customizeAppearance: "Personnalisez l'apparence de FleetCheck Pro sur votre appareil.",
    driverDashboard: 'Tableau de bord',
    checked: 'vérifiés',
    okLabel: 'OK',
    issuesLabel: 'Problèmes',
    describeIssue: 'Décrivez le problème…',
    driverSignature: 'Signature du Conducteur',
    documentsLabel: 'Documents',
    duration: 'Durée',
    photosTaken: 'Photos prises',
    fixResubmit: 'Corriger et Soumettre',
    searchDrivers: 'Rechercher des conducteurs...',
    searchVehicles: 'Rechercher des véhicules...',
    searchRepairs: 'Rechercher des réparations...',
    searchIssues: 'Rechercher des problèmes...',

    // Section titles
    reportsCompliance: 'Rapports et Conformité',
    myReports: 'Mes Rapports',
    fleetVehicles: 'Véhicules de la Flotte',
    repairRequests: 'Demandes de Réparation',
    inspectionResult: "Résultat de l'Inspection",
    issueDetails: 'Détails du Problème',
    driverProfile: 'Profil du Conducteur',
    vehicleDetail: 'Détail du Véhicule',
    personalInformation: 'Informations Personnelles',
    emergencyContact: "Contact d'Urgence",
    driverLicense: 'Permis de Conduire',
    medicalCard: 'Carte Médicale',
    employment: 'Emploi',
    companyProfile: "Profil de l'Entreprise",
    fleetManager: 'Gestionnaire de Flotte',
    companyInformation: "Informations sur l'Entreprise",
    languageSettings: 'Paramètres de Langue',
    appearance: 'Apparence',
    repairInformation: 'Informations sur la Réparation',
    basicInformation: 'Informations de Base',
    issueInformation: 'Informations sur le Problème',
    photos: 'Photos',
    statusHistory: 'Historique des Statuts',
    inspectionSummary: "Résumé de l'Inspection",
    failedItems: 'Éléments Échoués',
    vehiclePhotos: 'Photos du Véhicule',
    inspectionHistory: 'Historique des Inspections',
    repairHistory: 'Historique des Réparations',
    recentInspections: 'Inspections Récentes',
    availableVehicles: 'Véhicules Disponibles',
    recentReports: 'Rapports Récents',
    inspectionsPendingReview: 'Inspections en Attente de Révision',
    inspectionsThisWeek: 'Inspections Cette Semaine',
    issuesByCategory: 'Problèmes par Catégorie',
    repairStatus: 'État des Réparations',
    startInspection: "Démarrer l'Inspection",
    allowedVehicleTypes: 'Types de Véhicules Autorisés',

    // Table headers
    date: 'Date',
    vehicle: 'Véhicule',
    result: 'Résultat',
    reviewStatus: 'Statut de Révision',
    actions: 'Actions',
    status: 'Statut',
    priority: 'Priorité',
    reportedBy: 'Signalé Par',
    signature: 'Signature',
    severity: 'Gravité',
    unit: 'Unité',
    time: 'Heure',
    plate: 'Plaque',
    category: 'Catégorie',
    issue: 'Problème',
    licenseHash: 'Permis №',
    licExpiry: 'Exp. Permis',
    medExpiry: 'Exp. Médical',
    allowedVehicles: 'Véhicules Autorisés',
    inspectionType: "Type d'Inspection",
    inspectionDate: "Date d'Inspection",
    issueDate: 'Date du Problème',
    currentStatus: 'Statut Actuel',

    // Statuses
    statusActive: 'Actif',
    statusPending: 'En Attente',
    statusInactive: 'Inactif',
    statusNeedsAttention: "Besoin d'Attention",
    statusBlocked: 'Bloqué',
    statusInRepair: 'En Réparation',
    statusDraft: 'Brouillon',
    statusSubmitted: 'Soumis',
    statusOpen: 'Ouvert',
    statusInProgress: 'En Cours',
    statusCompleted: 'Terminé',
    statusCancelled: 'Annulé',
    statusUnderReview: 'En Révision',
    statusFixed: 'Réparé',
    statusRejected: 'Rejeté',
    statusNeedsReview: 'Révision Requise',
    statusReviewedOk: 'Révisé OK',
    statusFlagged: 'Signalé',
    statusPassed: 'Réussi',
    statusFailed: 'Échoué',

    // Priority / Severity
    priorityHigh: 'Élevé',
    priorityMedium: 'Moyen',
    priorityLow: 'Faible',

    // Filter dropdowns
    allStatus: 'Tous les Statuts',
    allTypes: 'Tous les Types',
    allResults: 'Tous les Résultats',
    allPriority: 'Toutes les Priorités',
    allSeverity: 'Toutes les Gravités',
    all: 'Tous',
    fraudFlagged: 'Fraude Signalée',
    clean: 'Propre',
    selectType: 'Sélectionner le type',
    selectClass: 'Sélectionner la classe',
    selectCategory: 'Sélectionner la catégorie',
    selectVehicle: 'Sélectionner le véhicule',
    none: 'Aucun',
    preTrip: 'Pré-Voyage',
    postTrip: 'Post-Voyage',

    // Inspections
    preTripInspection: 'Inspection Pré-Voyage',
    postTripInspection: 'Inspection Post-Voyage',
    pass: 'Réussi',
    fail: 'Échoué',
    na: 'N/A',
    addComment: 'Ajouter un Commentaire',
    signHere: 'Signer ici',
    submitInspection: "Soumettre l'Inspection",
    inspectionPassed: 'Inspection Réussie',
    inspectionFailed: 'Problèmes Trouvés',
    vehicleReadyForOperation: "Le véhicule est prêt pour l'opération. Tous les éléments d'inspection ont réussi.",
    issuesFoundMessage: "problème(s) trouvé(s). Révision du gestionnaire requise avant d'opérer ce véhicule.",
    completedBeforeDeparting: 'À compléter avant le départ',
    completedAfterArriving: "À compléter à l'arrivée",

    // Checklist categories
    tiresWheels: 'Pneus et Roues',
    lightsSignals: 'Lumières et Signaux',
    brakes: 'Freins',
    fluidLevels: 'Niveaux de Fluides',
    safetyEquipment: 'Équipement de Sécurité',
    documents: 'Documents',

    // Repair categories
    tires: 'Pneus',
    lights: 'Lumières',
    fluids: 'Fluides',
    engine: 'Moteur',
    exterior: 'Extérieur',
    steering: 'Direction',
    other: 'Autre',

    // Repair / Issue actions
    createRepairRequest: 'Créer une Demande de Réparation',
    notifyManager: 'Notifier le Gestionnaire',

    // Pending
    pendingApproval: "Inscription en attente d'approbation",
    pendingMessage: "Votre inscription a été soumise. Veuillez attendre l'approbation du gestionnaire.",
    whatHappensNext: 'Que se passe-t-il ensuite?',
    managerWillReview: 'Votre gestionnaire examinera votre inscription',
    youllReceiveEmail: 'Vous recevrez un e-mail lors de votre approbation',
    onceApprovedLogin: 'Une fois approuvé, vous pouvez vous connecter et commencer les inspections',

    // IssueDetail
    fraudFlaggedLabel: 'Fraude Signalée',
    vehicleBlockedLabel: 'Véhicule Bloqué',

    // Driver dashboard stats
    tripsThisMonth: 'Voyages Ce Mois',
    inspectionsPassed: 'Inspections Réussies',
    openIssues: 'Problèmes Ouverts',
    fuelEfficiency: 'Efficacité Carburant',
    submitRepairRequest: 'Soumettre une demande de réparation',
    logOutOfApp: "Se déconnecter de l'application",

    // Empty states
    noDriversFound: 'Aucun conducteur trouvé.',
    noVehiclesFound: 'Aucun véhicule trouvé.',
    noRepairsFound: 'Aucune réparation trouvée.',
    noReportsFound: 'Aucun rapport trouvé.',
    noIssuesFound: 'Aucun problème trouvé.',
    issueNotFound: 'Problème non trouvé.',
    noneAssigned: 'Aucun assigné',
    noPhotosAttached: 'Aucune photo jointe à ce problème',

    // Misc
    showing: 'Affichage',
    of: 'de',
    lightMode: 'Mode Clair',
    darkMode: 'Mode Sombre',
    selectLanguage: 'Sélectionner la langue',
    english: 'Anglais',
    ukrainian: 'Ukrainien',
    spanish: 'Espagnol',
    french: 'Français',

    // Registration
    workspaceReady: 'Votre espace est prêt!',
    workspaceSetupSuccess: 'Votre espace entreprise a été configuré avec succès.',
    workspaceSetupInfo: "Vous pouvez maintenant ajouter des véhicules, inviter des conducteurs et commencer à gérer les inspections.",
    createYourAccount: 'Créez Votre Compte',
    driverRegSubtitle: "Créez votre compte conducteur en utilisant le code d'invitation de votre entreprise.",
    noGoogleAccountHint: 'Pas de compte Google ? Créez un espace de travail avec votre e-mail et votre mot de passe, puis connectez-vous ici avec cette même adresse.',
    createAccountWithEmail: 'Créer un compte par e-mail',
    alreadyCreatedWorkspaceWithEmail: 'Pas encore de compte entreprise ?',
    createItHere: 'Créez-le ici',
    verifyInvite: 'Vérifier',
    checkingInvite: 'Vérification...',
    invitationFoundFor: 'Invitation trouvée pour',
    creating: 'Création...',
    inviteDriver: 'Inviter un conducteur',
    activeBusiness: 'Entreprise active',
    driverInvitations: 'Invitations des conducteurs',
    inviteDriversTo: 'Inviter des conducteurs à',
    driverInvitationsHelp: "Les conducteurs utilisent un seul code pour l'entreprise sélectionnée. Vous pouvez le renouveler à tout moment si vous devez remplacer le code actuel.",
    businessInviteCode: "Code d'invitation de l'entreprise",
    businessInviteCodeHelp: "Partagez ce code ou le lien d'inscription avec les conducteurs qui doivent rejoindre cette entreprise.",
    driverRegistrationLink: "Lien d'inscription conducteur",
    openRegistrationPage: "Ouvrir la page d'inscription",
    approveDriver: 'Approuver le conducteur',
    rejectDriver: 'Refuser le conducteur',
    driverApproved: 'Conducteur approuvé.',
    driverRejected: 'Conducteur refusé.',
    generateBusinessCode: 'Générer un code',
    rotateBusinessCode: 'Renouveler le code',
    noBusinessInviteCode: "Cette entreprise n'a pas encore de code d'invitation.",
    businessInviteCodeCreated: "Code d'invitation de l'entreprise créé.",
    businessInviteCodeUpdated: "Code d'invitation de l'entreprise mis à jour.",
    newInvite: 'Nouvelle invitation',
    noDriverInvites: "Aucun code d'invitation pour cette entreprise pour l'instant.",
    invitationCodeLabel: "Code d'invitation",
    openInvitationForAnyEmail: 'Invitation ouverte pour toute adresse e-mail de conducteur',
    expires: 'Expire le',
    withoutExpiry: 'sans expiration',
    copyCode: 'Copier le code',
    copyLink: 'Copier le lien',
    createDriverInvite: 'Créer une invitation conducteur',
    driverEmail: 'E-mail du conducteur',
    inviteEmailHint: "Laissez vide si vous voulez un code réutilisable pour tout conducteur de confiance rejoignant cette entreprise.",
    inviteExpiresIn: 'Expire dans',
    sevenDays: '7 jours',
    fourteenDays: '14 jours',
    thirtyDays: '30 jours',
    inviteCodeCopied: "Code d'invitation copié.",
    inviteLinkCopied: "Lien d'invitation copié.",
    lastBusinessDeleteWarning: "Il s'agit de votre dernière entreprise. Après sa suppression, votre espace restera actif mais sans entreprise jusqu'à ce que vous en créiez une nouvelle.",
    deleteBusinessAccessWarning: "Assurez-vous que personne n'a encore besoin d'accéder à cette entreprise avant de la supprimer.",
    statusExpired: 'Expiré',
    availability: 'Disponibilité',
    availabilityAvailable: 'Disponible',
    availabilityBusy: 'Occupé',
    availabilityReadyHint: "Prêt à être affecté dans l'entreprise actuelle.",
    availabilityBusiness: 'Entreprise',
    availabilityVehicle: 'Véhicule',
    availabilityService: 'Service',
    availabilityAssignedElsewhere: 'Actuellement affecté à un autre trajet actif.',
    uploadDriverLicensePhoto: 'Télécharger la Photo du Permis de Conduire',
    frontSide: 'Face Avant',
    backSide: 'Face Arrière',
    iAgreeToThe: "J'accepte les",
    termsOfService: "Conditions d'Utilisation",
    privacyPolicy: 'Politique de Confidentialité',
    iConfirmAccurate: 'Je confirme que toutes les informations fournies sont exactes.',
    askManagerForCode: "Demandez à votre gestionnaire de flotte le code d'invitation de l'entreprise.",
    min8Chars: 'Min. 8 caractères',
    repeatPassword: 'Répéter le mot de passe',
    clickToUpload: 'Cliquez pour télécharger ou glisser-déposer',
    pngJpgUpTo10mb: 'PNG, JPG jusqu\'à 10 Mo',
    jpgPng: 'JPG, PNG',

    // Landing page
    fleetOverview: 'Aperçu de la Flotte',
    preTripDone: 'Pré-Voyage Terminé',
    allItemsPassed: 'Tous les éléments réussis',
    highPriority: 'Haute Priorité',
    everythingYourFleetNeeds: 'Tout ce dont votre flotte a besoin',
    fleetManagementSaasPlatform: 'Plateforme SaaS de Gestion de Flotte',
    landingSubtitle: 'Simplifiez les inspections pré et post-voyage, gérez votre flotte, suivez les conditions des véhicules, photos, réparations et restez conforme — tout sur une seule plateforme.',
    landingFeaturesIntro: 'Des listes de contrôle quotidiennes des conducteurs aux rapports de conformité, FleetCheck Pro maintient toute votre opération de flotte en bon état de fonctionnement.',
    inspectionsDaily: 'Inspections Quotidiennes',
    companies: 'Entreprises',
    uptime: 'Disponibilité',
    countries: 'Pays',
    digitalInspections: 'Inspections Numériques',
    digitalInspectionsDesc: 'Listes de contrôle pré et post-voyage avec capture photo et signatures numériques.',
    fleetManagement: 'Gestion de Flotte',
    fleetManagementDesc: 'Suivez tous les véhicules, équipements et actifs dans un tableau de bord centralisé.',
    complianceReady: 'Prêt pour la Conformité',
    complianceReadyDesc: 'Rapports conformes DOT, journaux de bord des conducteurs et documentation exportable.',
    photoEvidence: 'Preuves Photographiques',
    photoEvidenceDesc: "Capturez et stockez des photos de l'état du véhicule avec détection des doublons.",
    repairTracking: 'Suivi des Réparations',
    repairTrackingDesc: "Enregistrez les problèmes, assignez des mécaniciens et suivez les réparations jusqu'à leur achèvement.",
    analyticsReports: 'Analytique et Rapports',
    analyticsReportsDesc: "Informations exploitables sur la santé de la flotte, la performance des conducteurs et les tendances.",
    footerCopyright: '© 2026 FleetCheck Pro. Tous droits réservés.',

    // Industry types
    truckingCompany: 'Entreprise de Transport',
    truckingCompanyDesc: 'Flottes de camions longue distance et régionales',
    constructionEquipment: 'Équipement de Construction',
    constructionEquipmentDesc: 'Excavatrices, bulldozers et machinerie lourde',
    boomLiftRental: 'Location de Nacelles',
    boomLiftRentalDesc: "Plateformes de travail aérien et équipements de levage",
    deliveryFleet: 'Flotte de Livraison',
    deliveryFleetDesc: 'Véhicules de livraison du dernier kilomètre et service de messagerie',
    taxiPassenger: 'Taxi / Passagers',
    taxiPassengerDesc: 'Flottes de covoiturage et de transport de passagers',
    serviceVehicles: 'Véhicules de Service',
    serviceVehiclesDesc: 'Flottes utilitaires, de maintenance et de service',
    otherFleet: 'Autre',
    otherFleetDesc: 'Type de flotte personnalisé ou opérations mixtes',
  },
}

export const useAppStore = defineStore('app', () => {
  const savedTheme = localStorage.getItem('theme') as 'light' | 'dark' | null
  const prefDark = window.matchMedia('(prefers-color-scheme: dark)').matches
  const theme = ref<'light' | 'dark'>(savedTheme ?? (prefDark ? 'dark' : 'light'))
  const language = ref<Language>((localStorage.getItem('lang') as Language) ?? 'en')
  const role = ref<Role>(null)
  const inspectionResult = ref<'pass' | 'fail' | null>(null)

  watch(theme, (val) => {
    const root = document.documentElement
    if (val === 'dark') root.classList.add('dark')
    else root.classList.remove('dark')
    localStorage.setItem('theme', val)
  }, { immediate: true })

  watch(language, (val) => {
    localStorage.setItem('lang', val)
  })

  function toggleTheme() {
    theme.value = theme.value === 'light' ? 'dark' : 'light'
  }

  function setLanguage(lang: Language) {
    language.value = lang
  }

  function setRole(r: Role) {
    role.value = r
  }

  function setInspectionResult(r: 'pass' | 'fail') {
    inspectionResult.value = r
  }

  function t(key: string): string {
    return translations[language.value][key] ?? translations['en'][key] ?? key
  }

  return { theme, language, role, inspectionResult, toggleTheme, setLanguage, setRole, setInspectionResult, t }
})
