import { defineStore } from 'pinia'
import { ref, watch } from 'vue'

export type Language = 'en' | 'uk' | 'es' | 'fr'
export type Role = 'manager' | 'driver' | 'admin' | null

const supportedLanguages: Language[] = ['en', 'uk', 'es', 'fr']

function normalizeLanguage(value?: string | null): Language {
  return supportedLanguages.includes(value as Language) ? (value as Language) : 'en'
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // App
    appName: 'FleetCheck Pro',
    tagline: 'Digital vehicle inspections for safer fleets',
    getStarted: 'Get Started',
    companyLogin: 'Company Login',
    driverRegistration: 'Driver Registration',

    // Nav
    dashboard: 'Dashboard',
    vehicles: 'Vehicles',
    drivers: 'Drivers',
    inspections: 'Inspections',
    inspectionTemplates: 'Inspection Templates',
    myVehicles: 'Vehicles',
    reports: 'Reports',
    issues: 'Issues',
    repairs: 'Repairs',
    settings: 'Settings',
    home: 'Home',
    inspect: 'Inspect',
    profile: 'Profile',

    // Nav back links
    backToDrivers: 'Back to Drivers',
    backToFleet: 'Back to Vehicles',
    backToLogin: 'Back to Login',
    backToInspection: 'Back to Inspection',
    backToIssues: 'Back to Issues',
    backToRepairs: 'Back to Repairs',
    backToDashboard: 'Back to Dashboard',

    // Auth
    login: 'Sign in',
    logout: 'Logout',
    signIn: 'Sign in',
    signUp: 'Sign up',
    createAccount: 'Create Account',
    forgotPassword: 'Forgot password?',
    alreadyHaveAccount: 'Already have an account?',
    signInWithGoogle: 'Sign in with Google',
    signUpWithGoogle: 'Sign up with Google',
    companyAccountRegistration: 'Company account registration',
    createYourCompanyAccount: 'Create your company account',
    signInToYourAccount: 'Sign in to your account',
    enterLoginCredentials: 'Enter your login credentials to get started.',
    or: 'or',
    atLeast8Chars: 'At least 8 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordsMatch: 'Passwords match',

    // Buttons
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    edit: 'Edit',
    delete: 'Delete',
    saveChanges: 'Save Changes',
    saveDriver: 'Save Driver',
    editDriver: 'Edit Driver',
    addDriver: 'Add Driver',
    addVehicle: 'Add Vehicle',
    addPhoto: 'Add Photo',
    fromGallery: 'From Gallery',
    removePhoto: 'Remove photo',
    itemTitle: 'Item title',
    checklistItemPlaceholder: 'Check service brakes',
    createTemplateCategoriesFirst: 'Create categories in Settings first',
    moveUp: 'Move up',
    moveDown: 'Move down',
    removeItem: 'Remove item',
    requiredLabel: 'Required',
    requiresPhotoLabel: 'Requires photo',
    driverInstructionsPlaceholder: 'Driver instructions for this check.',
    uploadReferencePhoto: 'Upload reference photo',
    referencePhoto: 'Reference photo',
    uploading: 'Uploading...',
    openDetails: 'Open details',
    hideDetails: 'Hide details',
    requiresPhotoBeforeSubmit: 'This item requires at least one photo before submit.',
    referencePhotoUploadFailed: 'Reference photo upload failed.',
    editVehicle: 'Edit Vehicle',
    editRepair: 'Edit Repair',
    newRepairRequest: 'New Repair',
    newRequest: 'New Request',
    submitRequest: 'Submit Request',
    saveReview: 'Save Review',
    review: 'Review',
    markAllOk: 'Mark all OK',
    saveDraft: 'Save Draft',
    sendToRepair: 'Send to Repair',
    rejectIssue: 'Reject Issue',
    blockVehicle: 'Block Vehicle',
    markAsFixed: 'Mark as Fixed',
    viewFullReport: 'View Full Report',
    fixAndResubmit: 'Fix & Resubmit',
    viewAll: 'View all',
    openVehicleCard: 'Open Vehicle',
    goToLogin: 'Go to Login',
    backToHome: 'Back to Home',
    goToDashboard: 'Go to Dashboard',
    outOfService: 'Out of Service',
    restoreService: 'Restore Service',
    signOut: 'Sign Out',
    reportProblem: 'Report Problem',
    viewAllNotifications: 'View all notifications',
    notifications: 'Notifications',
    new: 'new',
    approveOk: 'Approve — OK',
    flagIssue: 'Flag Issue',
    reviewInspection: 'Review Inspection',
    createDriverAccount: 'Create Driver Account',
    download: 'Download',
    pdf: 'PDF',
    email: 'Email',

    // Form fields
    emailField: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    dateOfBirth: 'Date of Birth',
    homeAddress: 'Home Address',
    address: 'Address',
    companyName: 'Company Name',
    industryType: 'Industry Type',
    country: 'Country',
    stateProvince: 'State / Province',
    city: 'City',
    licenseNumber: 'License #',
    licenseClass: 'License Class',
    expiryDate: 'Expiry Date',
    medicalCardNumber: 'Medical Card #',
    medicalCardPhoto: 'Medical Card Photo',
    licensePhoto: 'License Photo',
    hireDate: 'Hire Date',
    temporaryPassword: 'Temporary Password',
    contactName: 'Contact Name',
    contactPhone: 'Contact Phone',
    vehicleNumber: 'Vehicle Number',
    type: 'Type',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    plateNumber: 'Plate Number',
    vin: 'VIN',
    odometer: 'Odometer',
    dateLabel: 'Date',
    engineHours: 'Engine Hours',
    vehiclePhoto: 'Vehicle Photo',
    repairTitle: 'Repair Title',
    description: 'Description',
    issueCategory: 'Issue Category',
    driver: 'Driver',
    relatedIssue: 'Related Issue',
    startedAt: 'Started At',
    completedAt: 'Completed At',
    managersDecision: "Manager's Decision",
    managersNote: "Manager's Note",
    managerNotes: 'Manager Notes',
    invitationCode: 'Invitation Code',
    cardNumber: 'Card #',
    class: 'Class',
    language: 'Language',
    theme: 'Theme',
    search: 'Search...',
    createdAt: 'Created At',
    view: 'View',
    inspectionLabel: 'Inspection',
    chooseLanguage: 'Choose the display language for the application.',
    customizeAppearance: 'Customize how FleetCheck Pro looks on your device.',
    driverDashboard: 'Dashboard',
    checked: 'checked',
    okLabel: 'OK',
    issuesLabel: 'Issues',
    describeIssue: 'Describe the issue…',
    driverSignature: 'Driver Signature',
    documentsLabel: 'Documents',
    duration: 'Duration',
    photosTaken: 'Photos taken',
    fixResubmit: 'Fix & Resubmit',
    searchDrivers: 'Search drivers...',
    searchVehicles: 'Search vehicles...',
    searchRepairs: 'Search repairs...',
    searchIssues: 'Search issues...',
    from: 'From',
    to: 'To',

    // Section titles
    reportsCompliance: 'Reports',
    myReports: 'Reports',
    fleetVehicles: 'Vehicles',
    repairRequests: 'Repairs',
    inspectionResult: 'Report Details',
    issueDetails: 'Issue Details',
    driverProfile: 'Driver Details',
    vehicleDetail: 'Vehicle Details',
    personalInformation: 'Personal Information',
    emergencyContact: 'Emergency Contact',
    driverLicense: 'Driver License',
    medicalCard: 'Medical Card',
    employment: 'Employment',
    companyProfile: 'Company Profile',
    fleetManager: 'Fleet Manager',
    companyInformation: 'Company Information',
    languageSettings: 'Language Settings',
    appearance: 'Appearance',
    repairInformation: 'Repair Information',
    basicInformation: 'Basic Information',
    issueInformation: 'Issue Information',
    photos: 'Photos',
    statusHistory: 'Status History',
    inspectionSummary: 'Inspection Summary',
    failedItems: 'Failed Items',
    vehiclePhotos: 'Vehicle Photos',
    inspectionHistory: 'Inspection History',
    repairHistory: 'Repair History',
    recentInspections: 'Recent Inspections',
    availableVehicles: 'Available Vehicles',
    recentReports: 'Recent Reports',
    inspectionsPendingReview: 'Inspections Pending Review',
    inspectionsThisWeek: 'Inspections This Week',
    issuesByCategory: 'Issues by Category',
    repairStatus: 'Repair Status',
    startInspection: 'Start Inspection',
    allowedVehicleTypes: 'Allowed Vehicle Types',

    // Table headers
    date: 'Date',
    vehicle: 'Vehicle',
    result: 'Result',
    reviewStatus: 'Review Status',
    actions: 'Actions',
    status: 'Status',
    priority: 'Priority',
    reportedBy: 'Reported By',
    signature: 'Signature',
    severity: 'Severity',
    unit: 'Unit',
    time: 'Time',
    plate: 'Plate',
    category: 'Category',
    issue: 'Issue',
    licenseHash: 'License #',
    licExpiry: 'Lic. Expiry',
    medExpiry: 'Med. Expiry',
    allowedVehicles: 'Allowed Vehicles',
    inspectionType: 'Inspection Type',
    inspectionDate: 'Inspection Date',
    issueDate: 'Issue Date',
    currentStatus: 'Current Status',

    // Statuses
    statusActive: 'Active',
    statusPending: 'Pending',
    statusInactive: 'Inactive',
    statusNeedsAttention: 'Needs Attention',
    statusBlocked: 'Blocked',
    statusInRepair: 'In Repair',
    statusDraft: 'Draft',
    statusSubmitted: 'Submitted',
    statusOpen: 'Open',
    statusInProgress: 'In Progress',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    statusUnderReview: 'Under Review',
    statusFixed: 'Fixed',
    statusRejected: 'Rejected',
    statusNeedsReview: 'Needs Review',
    statusReviewedOk: 'Reviewed OK',
    statusFlagged: 'Flagged',
    statusPassed: 'Passed',
    statusFailed: 'Failed',

    // Priority / Severity
    priorityHigh: 'High',
    priorityMedium: 'Medium',
    priorityLow: 'Low',

    // Filter dropdowns
    allStatus: 'All Status',
    allTypes: 'All Types',
    allResults: 'All Results',
    allPriority: 'All Priority',
    allSeverity: 'All Severity',
    all: 'All',
    fraudFlagged: 'Fraud Flagged',
    clean: 'Clean',
    selectType: 'Select type',
    selectClass: 'Select class',
    selectCategory: 'Select category',
    selectVehicle: 'Select vehicle',
    none: 'None',
    preTrip: 'Pre-Trip',
    postTrip: 'Post-Trip',

    // Inspections
    preTripInspection: 'Pre-Trip Inspection',
    postTripInspection: 'Post-Trip Inspection',
    pass: 'Pass',
    fail: 'Fail',
    na: 'N/A',
    addComment: 'Add Comment',
    signHere: 'Sign here',
    submitInspection: 'Submit Inspection',
    submittingInspection: 'Submitting...',
    previewPdf: 'Preview PDF',
    shareCopy: 'Share copy',
    opening: 'Opening...',
    sharing: 'Sharing...',
    preparingPdf: 'Preparing PDF...',
    reportPdfActionFailed: 'Report PDF action failed.',
    inspectionPassed: 'Inspection Passed',
    inspectionFailed: 'Issues Found',
    vehicleReadyForOperation: 'Vehicle is ready for operation. All inspection items passed.',
    issuesFoundMessage: 'issue(s) found. Manager review required before operating this vehicle.',
    completedBeforeDeparting: 'Complete before departing',
    completedAfterArriving: 'Complete after arriving',

    // Checklist categories
    tiresWheels: 'Tires & Wheels',
    lightsSignals: 'Lights & Signals',
    brakes: 'Brakes',
    fluidLevels: 'Fluid Levels',
    safetyEquipment: 'Safety Equipment',
    documents: 'Documents',

    // Repair categories
    tires: 'Tires',
    lights: 'Lights',
    fluids: 'Fluids',
    engine: 'Engine',
    exterior: 'Exterior',
    steering: 'Steering',
    other: 'Other',

    // Repair / Issue actions
    createRepairRequest: 'Create Repair',
    notifyManager: 'Notify Manager',

    // Pending
    pendingApproval: 'Registration Pending Approval',
    pendingMessage: 'Your registration has been submitted. Please wait for manager approval.',
    whatHappensNext: 'What happens next?',
    managerWillReview: 'Your manager will review your registration',
    youllReceiveEmail: "You'll receive an email when approved",
    onceApprovedLogin: 'Once approved, you can log in and start inspections',

    // IssueDetail
    fraudFlaggedLabel: 'Fraud Flagged',
    vehicleBlockedLabel: 'Vehicle Blocked',

    // Anti-Fraud Module (Photo Verification)
    antiFraudRisk: 'Risk',
    antiFraudSummaryTitle: 'Anti-Fraud Summary',
    antiFraudSummaryHint: 'Automated authenticity checks for uploaded photos.',
    antiFraudAnalyzed: 'analyzed',
    inspectionReportTitle: 'Inspection Report',
    checklistItems: 'Checklist',
    photosHint: 'Click any photo to enlarge.',
    submitted: 'Submitted',
    exifMissing: 'no EXIF date',
    deviceUnknown: 'unknown device',
    gpsMissing: 'no GPS',
    antiFraudNoRecords: 'No anti-fraud records found for this report yet.',
    antiFraudMaxRisk: 'Max risk',
    antiFraudHighRisk: 'High Risk',
    antiFraudSuspicious: 'Suspicious',
    antiFraudNeedsReview: 'Needs Review',
    antiFraudOk: 'OK',
    antiFraudTopReasons: 'Top reasons',
    antiFraudMostSuspiciousPhotos: 'Most suspicious photos',
    antiFraudPreviousVsCurrent: 'Previous vs Current photo comparison',
    antiFraudExactDuplicate: 'Exact duplicate',
    antiFraudVisualDuplicate: 'Visual duplicate',
    antiFraudPreviousPhoto: 'Previous photo',
    antiFraudCurrentPhoto: 'Current photo',
    antiFraudFlagExactDuplicate: 'Photo was used before (exact file match)',
    antiFraudFlagVisualDuplicate: 'Photo is visually similar to previous report',
    antiFraudFlagOldExif: 'Photo date is older than current inspection',
    antiFraudFlagDeviceChanged: 'Device model changed from previous inspections',
    antiFraudFlagNoExif: 'No EXIF metadata found',
    antiFraudFlagFileNameReused: 'File name was reused',
    antiFraudFlagGpsOutlier: 'Photo GPS is far from the other photos in this inspection',
    antiFraudGpsMapTitle: 'Photo locations',
    antiFraudGpsMapHint: 'Pins show where each photo was taken. The blue circle is the 300 m geofence around the centroid.',
    antiFraudGpsOutlier: 'One or more photos were taken outside the 300 m radius of the other photos.',
    antiFraudReanalyze: 'Re-analyze',
    antiFraudReanalyzing: 'Analyzing…',
    antiFraudVerdictGpsOutlier: 'Photo location is far from other photos in this inspection.',
    antiFraudVerdictExactDuplicate: 'Likely reused photo from previous inspection (exact file match).',
    antiFraudVerdictVisualDuplicate: 'Likely reused photo with small edits (visual duplicate detected).',
    antiFraudVerdictOldExif: 'Needs manual review: photo appears to be taken before this inspection.',
    antiFraudVerdictDeviceChanged: 'Needs manual review: device model changed from recent inspections.',
    antiFraudVerdictNoExif: 'Limited trust signal: EXIF metadata is missing.',
    antiFraudVerdictFileNameReused: 'Weak signal only: file name was reused.',
    antiFraudVerdictHighRisk: 'High risk pattern detected. Manual validation is recommended.',
    antiFraudVerdictSuspicious: 'Suspicious pattern detected. Manual validation is recommended.',
    antiFraudVerdictNeedsReview: 'Some risk indicators were detected. Please review.',
    antiFraudVerdictNoIndicators: 'No significant fraud indicators detected.',

    // Driver dashboard stats
    tripsThisMonth: 'Trips This Month',
    inspectionsPassed: 'Inspections Passed',
    openIssues: 'Open Issues',
    fuelEfficiency: 'Fuel Efficiency',
    submitRepairRequest: 'Submit repair request',
    logOutOfApp: 'Log out of app',

    // Empty states
    noDriversFound: 'No drivers found.',
    noVehiclesFound: 'No vehicles found.',
    noRepairsFound: 'No repairs found.',
    noReportsFound: 'No reports found.',
    noIssuesFound: 'No issues found.',
    issueNotFound: 'Issue not found.',
    noneAssigned: 'None assigned',
    noPhotosAttached: 'No photos attached to this issue',

    // Misc
    showing: 'Showing',
    of: 'of',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    selectLanguage: 'Select Language',
    english: 'English',
    ukrainian: 'Ukrainian',
    spanish: 'Spanish',
    french: 'French',

    // Registration
    workspaceReady: 'Your workspace is ready!',
    workspaceSetupSuccess: 'Your company workspace has been set up successfully.',
    workspaceSetupInfo: 'You can now add vehicles, invite drivers, and start managing inspections.',
    createYourAccount: 'Create Your Account',
    driverRegSubtitle: 'Create your driver account using your company invitation code.',
    uploadDriverLicensePhoto: 'Upload Driver License Photo',
    frontSide: 'Front Side',
    backSide: 'Back Side',
    iAgreeToThe: 'I agree to the',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    iConfirmAccurate: 'I confirm that all information provided is accurate.',
    askManagerForCode: 'Ask your fleet manager for the company invitation code.',
    min8Chars: 'Min 8 characters',
    repeatPassword: 'Repeat password',
    clickToUpload: 'Click to upload or drag & drop',
    pngJpgUpTo10mb: 'PNG, JPG up to 10 MB',
    jpgPng: 'JPG, PNG',

    // Landing page
    fleetOverview: 'Fleet Overview',
    preTripDone: 'Pre-Trip Done',
    allItemsPassed: 'All items passed',
    highPriority: 'High Priority',
    everythingYourFleetNeeds: 'Everything your fleet needs',
    fleetManagementSaasPlatform: 'Fleet Management SaaS Platform',
    landingSubtitle: 'Streamline pre-trip and post-trip inspections, manage your fleet, track vehicle conditions, photos, repairs, and stay compliant — all from one platform.',
    landingFeaturesIntro: 'From daily driver checklists to compliance reports, FleetCheck Pro keeps your entire fleet operation running smoothly.',
    inspectionsDaily: 'Inspections Daily',
    companies: 'Companies',
    uptime: 'Uptime',
    countries: 'Countries',
    digitalInspections: 'Digital Inspections',
    digitalInspectionsDesc: 'Pre-trip and post-trip checklists with photo capture and digital signatures.',
    fleetManagement: 'Fleet Management',
    fleetManagementDesc: 'Track all vehicles, equipment, and assets in one centralized dashboard.',
    complianceReady: 'Compliance Ready',
    complianceReadyDesc: 'DOT-compliant reports, driver logs, and exportable documentation.',
    photoEvidence: 'Photo Evidence',
    photoEvidenceDesc: 'Capture and store vehicle condition photos with duplicate detection.',
    repairTracking: 'Repair Tracking',
    repairTrackingDesc: 'Log issues and track manager-led repairs to completion.',
    analyticsReports: 'Analytics & Reports',
    analyticsReportsDesc: 'Actionable insights on fleet health, driver performance, and trends.',
    footerCopyright: '© 2026 FleetCheck Pro. All rights reserved.',

    // Industry types
    truckingCompany: 'Trucking Company',
    truckingCompanyDesc: 'Long-haul & regional trucking fleets',
    constructionEquipment: 'Construction Equipment',
    constructionEquipmentDesc: 'Excavators, bulldozers & heavy machinery',
    boomLiftRental: 'Boom Lift Rental',
    boomLiftRentalDesc: 'Aerial work platforms & lift equipment',
    deliveryFleet: 'Delivery Fleet',
    deliveryFleetDesc: 'Last-mile & courier delivery vehicles',
    taxiPassenger: 'Taxi / Passenger',
    taxiPassengerDesc: 'Ride-share & passenger transport fleets',
    serviceVehicles: 'Service Vehicles',
    serviceVehiclesDesc: 'Utility, maintenance & service fleets',
    otherFleet: 'Other',
    otherFleetDesc: 'Custom fleet type or mixed operations',
  },
  uk: {
    // App
    appName: 'FleetCheck Pro',
    tagline: 'Цифрові огляди транспортних засобів для безпечних автопарків',
    getStarted: 'Розпочати',
    companyLogin: 'Вхід для компанії',
    driverRegistration: 'Реєстрація водія',

    // Nav
    dashboard: 'Панель',
    vehicles: 'Транспорт',
    drivers: 'Водії',
    inspections: 'Огляди',
    reports: 'Звіти',
    issues: 'Проблеми',
    repairs: 'Ремонти',
    settings: 'Налаштування',
    home: 'Головна',
    inspect: 'Огляд',
    profile: 'Профіль',

    // Nav back links
    backToDrivers: 'До водіїв',
    backToFleet: 'До транспорту',
    backToLogin: 'До входу',
    backToInspection: 'До огляду',
    backToIssues: 'До проблем',
    backToRepairs: 'До ремонтів',
    backToDashboard: 'До панелі',

    // Auth
    login: 'Увійти',
    logout: 'Вийти',
    signIn: 'Увійти',
    signUp: 'Зареєструватись',
    createAccount: 'Створити акаунт',
    forgotPassword: 'Забули пароль?',
    alreadyHaveAccount: 'Вже є акаунт?',
    signInWithGoogle: 'Увійти через Google',
    signUpWithGoogle: 'Зареєструватись через Google',
    companyAccountRegistration: 'Реєстрація акаунту компанії',
    createYourCompanyAccount: 'Створіть акаунт компанії',
    signInToYourAccount: 'Увійдіть у свій акаунт',
    enterLoginCredentials: 'Введіть дані для входу.',
    or: 'або',
    atLeast8Chars: 'Мінімум 8 символів',
    passwordsDoNotMatch: 'Паролі не збігаються',
    passwordsMatch: 'Паролі збігаються',

    // Buttons
    save: 'Зберегти',
    cancel: 'Скасувати',
    submit: 'Надіслати',
    next: 'Далі',
    back: 'Назад',
    finish: 'Завершити',
    edit: 'Редагувати',
    delete: 'Видалити',
    saveChanges: 'Зберегти зміни',
    saveDriver: 'Зберегти водія',
    editDriver: 'Редагувати водія',
    addDriver: 'Додати водія',
    addVehicle: 'Додати транспорт',
    addPhoto: 'Додати фото',
    fromGallery: 'З галереї',
    removePhoto: 'Видалити фото',
    itemTitle: 'Назва пункту',
    checklistItemPlaceholder: 'Перевірте робочі гальма',
    createTemplateCategoriesFirst: 'Спочатку створіть категорії у Налаштуваннях',
    moveUp: 'Перемістити вгору',
    moveDown: 'Перемістити вниз',
    removeItem: 'Видалити пункт',
    requiredLabel: 'Обовʼязково',
    requiresPhotoLabel: 'Потрібне фото',
    driverInstructionsPlaceholder: 'Інструкція для водія щодо цього пункту.',
    uploadReferencePhoto: 'Завантажити еталонне фото',
    referencePhoto: 'Еталонне фото',
    uploading: 'Завантаження...',
    openDetails: 'Відкрити деталі',
    hideDetails: 'Сховати деталі',
    requiresPhotoBeforeSubmit: 'Для цього пункту потрібно додати щонайменше одне фото перед відправкою.',
    referencePhotoUploadFailed: 'Не вдалося завантажити еталонне фото.',
    editVehicle: 'Редагувати транспорт',
    editRepair: 'Редагувати ремонт',
    newRepairRequest: 'Новий ремонт',
    newRequest: 'Нова заявка',
    submitRequest: 'Подати заявку',
    saveReview: 'Зберегти перевірку',
    review: 'Перевірити',
    markAllOk: 'Позначити все OK',
    saveDraft: 'Зберегти чернетку',
    sendToRepair: 'Відправити в ремонт',
    rejectIssue: 'Відхилити проблему',
    blockVehicle: 'Заблокувати транспорт',
    markAsFixed: 'Позначити як виправлено',
    viewFullReport: 'Переглянути повний звіт',
    fixAndResubmit: 'Виправити та повторно надіслати',
    viewAll: 'Переглянути всі',
    openVehicleCard: 'Відкрити транспорт',
    goToLogin: 'До входу',
    backToHome: 'На головну',
    goToDashboard: 'До панелі',
    outOfService: 'Поза службою',
    restoreService: 'Відновити службу',
    signOut: 'Вийти',
    reportProblem: 'Повідомити про проблему',
    viewAllNotifications: 'Усі сповіщення',
    notifications: 'Сповіщення',
    new: 'нових',
    approveOk: 'Схвалити — OK',
    flagIssue: 'Позначити проблему',
    reviewInspection: 'Перевірити огляд',
    createDriverAccount: 'Створити акаунт водія',
    download: 'Завантажити',
    pdf: 'PDF',
    email: 'Ел. пошта',

    // Form fields
    emailField: 'Ел. пошта',
    password: 'Пароль',
    confirmPassword: 'Підтвердити пароль',
    firstName: "Ім'я",
    lastName: 'Прізвище',
    phone: 'Телефон',
    dateOfBirth: 'Дата народження',
    homeAddress: 'Домашня адреса',
    address: 'Адреса',
    companyName: 'Назва компанії',
    industryType: 'Тип галузі',
    country: 'Країна',
    stateProvince: 'Область / Провінція',
    city: 'Місто',
    licenseNumber: 'Посвідчення №',
    licenseClass: 'Клас посвідчення',
    expiryDate: 'Дата закінчення',
    medicalCardNumber: 'Медична картка №',
    medicalCardPhoto: 'Фото медичної картки',
    licensePhoto: 'Фото посвідчення',
    hireDate: 'Дата прийому',
    temporaryPassword: 'Тимчасовий пароль',
    contactName: 'Контактна особа',
    contactPhone: 'Контактний телефон',
    vehicleNumber: 'Номер ТЗ',
    type: 'Тип',
    make: 'Марка',
    model: 'Модель',
    year: 'Рік',
    plateNumber: 'Номерний знак',
    vin: 'VIN',
    odometer: 'Одометр',
    dateLabel: 'Дата',
    engineHours: 'Мотогодини',
    vehiclePhoto: 'Фото транспорту',
    repairTitle: 'Назва ремонту',
    description: 'Опис',
    issueCategory: 'Категорія проблеми',
    driver: 'Водій',
    relatedIssue: 'Пов\'язана проблема',
    startedAt: 'Розпочато',
    completedAt: 'Завершено',
    managersDecision: 'Рішення менеджера',
    managersNote: 'Примітка менеджера',
    managerNotes: 'Нотатки менеджера',
    invitationCode: 'Код запрошення',
    cardNumber: 'Картка №',
    class: 'Клас',
    language: 'Мова',
    theme: 'Тема',
    search: 'Пошук...',
    createdAt: 'Створено',
    view: 'Переглянути',
    inspectionLabel: 'Огляд',
    chooseLanguage: 'Оберіть мову відображення застосунку.',
    customizeAppearance: 'Налаштуйте вигляд FleetCheck Pro на вашому пристрої.',
    driverDashboard: 'Панель',
    checked: 'перевірено',
    okLabel: 'OK',
    issuesLabel: 'Проблеми',
    describeIssue: 'Опишіть проблему…',
    driverSignature: 'Підпис водія',
    documentsLabel: 'Документи',
    duration: 'Тривалість',
    photosTaken: 'Фото зроблено',
    fixResubmit: 'Виправити та подати',
    searchDrivers: 'Пошук водіїв...',
    searchVehicles: 'Пошук транспорту...',
    searchRepairs: 'Пошук ремонтів...',
    searchIssues: 'Пошук проблем...',
    from: 'Від',
    to: 'До',

    // Section titles
    reportsCompliance: 'Звіти',
    myReports: 'Звіти',
    fleetVehicles: 'Транспорт',
    repairRequests: 'Ремонти',
    inspectionResult: 'Деталі звіту',
    issueDetails: 'Деталі проблеми',
    driverProfile: 'Деталі водія',
    vehicleDetail: 'Деталі транспорту',
    personalInformation: 'Особисті дані',
    emergencyContact: 'Екстрений контакт',
    driverLicense: 'Водійське посвідчення',
    medicalCard: 'Медична картка',
    employment: 'Зайнятість',
    companyProfile: 'Профіль компанії',
    fleetManager: 'Менеджер автопарку',
    companyInformation: 'Інформація про компанію',
    languageSettings: 'Налаштування мови',
    appearance: 'Зовнішній вигляд',
    repairInformation: 'Інформація про ремонт',
    basicInformation: 'Основна інформація',
    issueInformation: 'Інформація про проблему',
    photos: 'Фото',
    statusHistory: 'Історія статусів',
    inspectionSummary: 'Зведення огляду',
    failedItems: 'Виявлені проблеми',
    vehiclePhotos: 'Фото транспорту',
    inspectionHistory: 'Історія оглядів',
    repairHistory: 'Історія ремонтів',
    recentInspections: 'Останні огляди',
    availableVehicles: 'Доступний транспорт',
    recentReports: 'Останні звіти',
    inspectionsPendingReview: 'Огляди на перевірку',
    inspectionsThisWeek: 'Огляди цього тижня',
    issuesByCategory: 'Проблеми за категоріями',
    repairStatus: 'Статус ремонтів',
    startInspection: 'Почати огляд',
    allowedVehicleTypes: 'Дозволені типи транспорту',

    // Table headers
    date: 'Дата',
    vehicle: 'Транспорт',
    result: 'Результат',
    reviewStatus: 'Статус перевірки',
    actions: 'Дії',
    status: 'Статус',
    priority: 'Пріоритет',
    reportedBy: 'Хто повідомив',
    signature: 'Підпис',
    severity: 'Серйозність',
    unit: 'Одиниця',
    time: 'Час',
    plate: 'Номер',
    category: 'Категорія',
    issue: 'Проблема',
    licenseHash: 'Посвідчення №',
    licExpiry: 'Посвідчення до',
    medExpiry: 'Мед. картка до',
    allowedVehicles: 'Дозволений транспорт',
    inspectionType: 'Тип огляду',
    inspectionDate: 'Дата огляду',
    issueDate: 'Дата проблеми',
    currentStatus: 'Поточний статус',

    // Statuses
    statusActive: 'Активний',
    statusPending: 'Очікує',
    statusInactive: 'Неактивний',
    statusNeedsAttention: 'Потребує уваги',
    statusBlocked: 'Заблокований',
    statusInRepair: 'В ремонті',
    statusDraft: 'Чернетка',
    statusSubmitted: 'Надіслано',
    statusOpen: 'Відкрито',
    statusInProgress: 'В процесі',
    statusCompleted: 'Завершено',
    statusCancelled: 'Скасовано',
    statusUnderReview: 'На перевірці',
    statusFixed: 'Виправлено',
    statusRejected: 'Відхилено',
    statusNeedsReview: 'Потребує перевірки',
    statusReviewedOk: 'Перевірено OK',
    statusFlagged: 'Позначено',
    statusPassed: 'Пройдено',
    statusFailed: 'Не пройдено',

    // Priority / Severity
    priorityHigh: 'Високий',
    priorityMedium: 'Середній',
    priorityLow: 'Низький',

    // Filter dropdowns
    allStatus: 'Всі статуси',
    allTypes: 'Всі типи',
    allResults: 'Всі результати',
    allPriority: 'Всі пріоритети',
    allSeverity: 'Всі ступені',
    all: 'Всі',
    fraudFlagged: 'Підозра на шахрайство',
    clean: 'Чисто',
    selectType: 'Оберіть тип',
    selectClass: 'Оберіть клас',
    selectCategory: 'Оберіть категорію',
    selectVehicle: 'Оберіть транспорт',
    none: 'Немає',
    preTrip: 'До поїздки',
    postTrip: 'Після поїздки',

    // Inspections
    preTripInspection: 'Огляд до поїздки',
    postTripInspection: 'Огляд після поїздки',
    pass: 'Пройдено',
    fail: 'Не пройдено',
    na: 'Н/Д',
    addComment: 'Додати коментар',
    signHere: 'Підписати тут',
    submitInspection: 'Надіслати огляд',
    submittingInspection: 'Надсилання...',
    previewPdf: 'Переглянути PDF',
    shareCopy: 'Поділитися копією',
    opening: 'Відкриття...',
    sharing: 'Поширення...',
    preparingPdf: 'Підготовка PDF...',
    reportPdfActionFailed: 'Не вдалося виконати дію з PDF звітом.',
    inspectionPassed: 'Огляд пройдено',
    inspectionFailed: 'Знайдено проблеми',
    vehicleReadyForOperation: 'Транспорт готовий до роботи. Усі пункти огляду пройдено.',
    issuesFoundMessage: 'проблем(и) виявлено. Потрібна перевірка менеджером перед використанням транспорту.',
    completedBeforeDeparting: 'Завершити до відправлення',
    completedAfterArriving: 'Завершити після прибуття',

    // Checklist categories
    tiresWheels: 'Шини та колеса',
    lightsSignals: 'Освітлення та сигнали',
    brakes: 'Гальма',
    fluidLevels: 'Рівень рідин',
    safetyEquipment: 'Засоби безпеки',
    documents: 'Документи',

    // Repair categories
    tires: 'Шини',
    lights: 'Освітлення',
    fluids: 'Рідини',
    engine: 'Двигун',
    exterior: 'Зовнішній вигляд',
    steering: 'Кермо',
    other: 'Інше',

    // Repair / Issue actions
    createRepairRequest: 'Створити ремонт',
    notifyManager: 'Повідомити менеджера',

    // Pending
    pendingApproval: 'Реєстрація очікує підтвердження',
    pendingMessage: 'Вашу реєстрацію подано. Очікуйте підтвердження менеджера.',
    whatHappensNext: 'Що далі?',
    managerWillReview: 'Менеджер перевірить вашу реєстрацію',
    youllReceiveEmail: 'Ви отримаєте email після схвалення',
    onceApprovedLogin: 'Після схвалення ви зможете увійти та починати огляди',

    // IssueDetail
    fraudFlaggedLabel: 'Підозра на шахрайство',
    vehicleBlockedLabel: 'Транспорт заблоковано',

    // Anti-Fraud Module (Photo Verification)
    antiFraudRisk: 'Ризик',
    antiFraudSummaryTitle: 'Антифрод-підсумок',
    antiFraudSummaryHint: 'Автоматична перевірка достовірності завантажених фото.',
    antiFraudAnalyzed: 'проаналізовано',
    inspectionReportTitle: 'Звіт інспекції',
    checklistItems: 'Чекліст',
    photosHint: 'Клікни на фото, щоб збільшити.',
    submitted: 'Надіслано',
    exifMissing: 'немає EXIF-дати',
    deviceUnknown: 'пристрій невідомий',
    gpsMissing: 'немає GPS',
    antiFraudNoRecords: 'Для цього звіту ще немає записів антифрод-перевірки.',
    antiFraudMaxRisk: 'Макс. ризик',
    antiFraudHighRisk: 'Високий ризик',
    antiFraudSuspicious: 'Підозріло',
    antiFraudNeedsReview: 'Потрібна перевірка',
    antiFraudOk: 'OK',
    antiFraudTopReasons: 'Основні причини',
    antiFraudMostSuspiciousPhotos: 'Найбільш підозрілі фото',
    antiFraudPreviousVsCurrent: 'Порівняння попереднього та поточного фото',
    antiFraudExactDuplicate: 'Точний дубль',
    antiFraudVisualDuplicate: 'Візуальний дубль',
    antiFraudPreviousPhoto: 'Попереднє фото',
    antiFraudCurrentPhoto: 'Поточне фото',
    antiFraudFlagExactDuplicate: 'Фото вже використовувалось раніше (точний збіг файлу)',
    antiFraudFlagVisualDuplicate: 'Фото візуально схоже на фото з попереднього звіту',
    antiFraudFlagOldExif: 'Дата фото старіша за поточну інспекцію',
    antiFraudFlagDeviceChanged: 'Модель пристрою змінилась порівняно з попередніми інспекціями',
    antiFraudFlagNoExif: 'Відсутні EXIF-метадані',
    antiFraudFlagFileNameReused: 'Назва файлу повторно використана',
    antiFraudFlagGpsOutlier: 'GPS фото далеко від інших фото цієї інспекції',
    antiFraudGpsMapTitle: 'Місця зйомки фото',
    antiFraudGpsMapHint: 'Маркери показують де зроблено кожне фото. Синє коло — геозона 300 м навколо центру.',
    antiFraudGpsOutlier: 'Одне або більше фото зроблено за межами радіуса 300 м від інших фото.',
    antiFraudReanalyze: 'Переаналізувати',
    antiFraudReanalyzing: 'Аналізую…',
    antiFraudVerdictGpsOutlier: 'Локація фото далеко від інших фото цієї інспекції.',
    antiFraudVerdictExactDuplicate: 'Ймовірно повторно використане фото з попередньої інспекції (точний збіг).',
    antiFraudVerdictVisualDuplicate: 'Ймовірно повторно використане фото з незначними змінами (візуальний дубль).',
    antiFraudVerdictOldExif: 'Потрібна ручна перевірка: фото, схоже, зроблене до цієї інспекції.',
    antiFraudVerdictDeviceChanged: 'Потрібна ручна перевірка: модель пристрою змінилася відносно останніх інспекцій.',
    antiFraudVerdictNoExif: 'Обмежений сигнал довіри: EXIF-метадані відсутні.',
    antiFraudVerdictFileNameReused: 'Слабкий сигнал: назва файлу повторюється.',
    antiFraudVerdictHighRisk: 'Виявлено патерн високого ризику. Рекомендується ручна валідація.',
    antiFraudVerdictSuspicious: 'Виявлено підозрілий патерн. Рекомендується ручна валідація.',
    antiFraudVerdictNeedsReview: 'Виявлено ризикові індикатори. Потрібна перевірка.',
    antiFraudVerdictNoIndicators: 'Суттєвих ознак шахрайства не виявлено.',

    // Driver dashboard stats
    tripsThisMonth: 'Поїздок цього місяця',
    inspectionsPassed: 'Оглядів пройдено',
    openIssues: 'Відкриті проблеми',
    fuelEfficiency: 'Витрата пального',
    submitRepairRequest: 'Подати заявку на ремонт',
    logOutOfApp: 'Вийти з додатку',

    // Empty states
    noDriversFound: 'Водіїв не знайдено.',
    noVehiclesFound: 'Транспорт не знайдено.',
    noRepairsFound: 'Ремонтів не знайдено.',
    noReportsFound: 'Звітів не знайдено.',
    noIssuesFound: 'Проблем не знайдено.',
    issueNotFound: 'Проблему не знайдено.',
    noneAssigned: 'Не призначено',
    noPhotosAttached: 'Фото до цієї проблеми не додано',

    // Misc
    showing: 'Показано',
    of: 'з',
    lightMode: 'Світла тема',
    darkMode: 'Темна тема',
    selectLanguage: 'Оберіть мову',
    english: 'Англійська',
    ukrainian: 'Українська',
    spanish: 'Іспанська',
    french: 'Французька',

    // Registration
    workspaceReady: 'Ваш простір готовий!',
    workspaceSetupSuccess: 'Простір вашої компанії успішно налаштовано.',
    workspaceSetupInfo: 'Тепер ви можете додавати транспорт, запрошувати водіїв та керувати оглядами.',
    createYourAccount: 'Створіть акаунт',
    driverRegSubtitle: 'Створіть акаунт водія за допомогою коду запрошення компанії.',
    uploadDriverLicensePhoto: 'Завантажте фото посвідчення водія',
    frontSide: 'Лицьова сторона',
    backSide: 'Зворотна сторона',
    iAgreeToThe: 'Я погоджуюсь з',
    termsOfService: 'Умовами використання',
    privacyPolicy: 'Політикою конфіденційності',
    iConfirmAccurate: 'Я підтверджую, що всі надані дані є точними.',
    askManagerForCode: 'Запитайте у менеджера автопарку код запрошення компанії.',
    min8Chars: 'Мін. 8 символів',
    repeatPassword: 'Повторіть пароль',
    clickToUpload: 'Натисніть або перетягніть файл',
    pngJpgUpTo10mb: 'PNG, JPG до 10 МБ',
    jpgPng: 'JPG, PNG',

    // Landing page
    fleetOverview: 'Огляд автопарку',
    preTripDone: 'Огляд виконано',
    allItemsPassed: 'Всі пункти пройдено',
    highPriority: 'Високий пріоритет',
    everythingYourFleetNeeds: 'Все, що потрібно вашому автопарку',
    fleetManagementSaasPlatform: 'SaaS-платформа для управління автопарком',
    landingSubtitle: 'Спростіть огляди до та після поїздок, керуйте автопарком, відстежуйте стан транспорту, фото, ремонти та залишайтесь відповідними — все в одній платформі.',
    landingFeaturesIntro: 'Від щоденних чеклістів водіїв до звітів про відповідність — FleetCheck Pro забезпечує безперебійну роботу всього вашого автопарку.',
    inspectionsDaily: 'Оглядів щодня',
    companies: 'Компаній',
    uptime: 'Безвідмовність',
    countries: 'Країн',
    digitalInspections: 'Цифрові огляди',
    digitalInspectionsDesc: 'Чеклісти до та після поїздок із фото та цифровими підписами.',
    fleetManagement: 'Управління автопарком',
    fleetManagementDesc: 'Відстежуйте всі транспортні засоби, обладнання та активи в одній централізованій панелі.',
    complianceReady: 'Відповідність вимогам',
    complianceReadyDesc: 'Звіти, що відповідають вимогам DOT, журнали водіїв та документація для експорту.',
    photoEvidence: 'Фотодокументація',
    photoEvidenceDesc: 'Знімайте та зберігайте фото стану транспорту з виявленням дублікатів.',
    repairTracking: 'Відстеження ремонтів',
    repairTrackingDesc: 'Фіксуйте проблеми та відстежуйте ремонти, якими керує менеджер, до завершення.',
    analyticsReports: 'Аналітика та звіти',
    analyticsReportsDesc: 'Практичні висновки про стан автопарку, продуктивність водіїв та тенденції.',
    footerCopyright: '© 2026 FleetCheck Pro. Всі права захищені.',

    // Industry types
    truckingCompany: 'Вантажні перевезення',
    truckingCompanyDesc: 'Далекобійні та регіональні вантажні автопарки',
    constructionEquipment: 'Будівельна техніка',
    constructionEquipmentDesc: 'Екскаватори, бульдозери та важка техніка',
    boomLiftRental: 'Оренда підйомників',
    boomLiftRentalDesc: 'Платформи для роботи на висоті та підйомне обладнання',
    deliveryFleet: 'Служба доставки',
    deliveryFleetDesc: 'Транспорт для доставки на останній милі та кур\'єрські служби',
    taxiPassenger: 'Таксі / Пасажирські',
    taxiPassengerDesc: 'Автопарки для таксі та пасажирських перевезень',
    serviceVehicles: 'Сервісні транспортні засоби',
    serviceVehiclesDesc: 'Комунальні, технічні та сервісні автопарки',
    otherFleet: 'Інше',
    otherFleetDesc: 'Нестандартний тип або змішані операції',
  },
  es: {
    // App
    appName: 'FleetCheck Pro',
    tagline: 'Inspecciones digitales de vehículos para flotas más seguras',
    getStarted: 'Comenzar',
    companyLogin: 'Acceso Empresa',
    driverRegistration: 'Registro de Conductor',

    // Nav
    dashboard: 'Panel',
    vehicles: 'Vehículos',
    drivers: 'Conductores',
    inspections: 'Inspecciones',
    reports: 'Reportes',
    issues: 'Problemas',
    repairs: 'Reparaciones',
    settings: 'Configuración',
    home: 'Inicio',
    inspect: 'Inspeccionar',
    profile: 'Perfil',

    // Nav back links
    backToDrivers: 'Volver a Conductores',
    backToFleet: 'Volver a Vehículos',
    backToLogin: 'Volver al Inicio de Sesión',
    backToInspection: 'Volver a Inspección',
    backToIssues: 'Volver a Problemas',
    backToRepairs: 'Volver a Reparaciones',
    backToDashboard: 'Volver al Panel',

    // Auth
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    createAccount: 'Crear Cuenta',
    forgotPassword: '¿Olvidó su contraseña?',
    alreadyHaveAccount: '¿Ya tiene una cuenta?',
    signInWithGoogle: 'Iniciar sesión con Google',
    signUpWithGoogle: 'Registrarse con Google',
    companyAccountRegistration: 'Registro de cuenta empresarial',
    createYourCompanyAccount: 'Cree su cuenta empresarial',
    signInToYourAccount: 'Inicie sesión en su cuenta',
    enterLoginCredentials: 'Ingrese sus credenciales para comenzar.',
    or: 'o',
    atLeast8Chars: 'Al menos 8 caracteres',
    passwordsDoNotMatch: 'Las contraseñas no coinciden',
    passwordsMatch: 'Las contraseñas coinciden',

    // Buttons
    save: 'Guardar',
    cancel: 'Cancelar',
    submit: 'Enviar',
    next: 'Siguiente',
    back: 'Atrás',
    finish: 'Finalizar',
    edit: 'Editar',
    delete: 'Eliminar',
    saveChanges: 'Guardar Cambios',
    saveDriver: 'Guardar Conductor',
    editDriver: 'Editar Conductor',
    addDriver: 'Agregar Conductor',
    addVehicle: 'Agregar Vehículo',
    addPhoto: 'Agregar Foto',
    fromGallery: 'Desde Galería',
    removePhoto: 'Eliminar foto',
    itemTitle: 'Titulo del elemento',
    checklistItemPlaceholder: 'Revise los frenos de servicio',
    createTemplateCategoriesFirst: 'Primero cree categorias en Configuracion',
    moveUp: 'Mover arriba',
    moveDown: 'Mover abajo',
    removeItem: 'Eliminar elemento',
    requiredLabel: 'Obligatorio',
    requiresPhotoLabel: 'Requiere foto',
    driverInstructionsPlaceholder: 'Instrucciones para el conductor para esta revision.',
    uploadReferencePhoto: 'Subir foto de referencia',
    referencePhoto: 'Foto de referencia',
    uploading: 'Subiendo...',
    openDetails: 'Abrir detalles',
    hideDetails: 'Ocultar detalles',
    requiresPhotoBeforeSubmit: 'Este elemento requiere al menos una foto antes de enviar.',
    referencePhotoUploadFailed: 'No se pudo subir la foto de referencia.',
    editVehicle: 'Editar Vehículo',
    editRepair: 'Editar Reparación',
    newRepairRequest: 'Nueva Reparación',
    newRequest: 'Nueva Solicitud',
    submitRequest: 'Enviar Solicitud',
    saveReview: 'Guardar Revisión',
    review: 'Revisar',
    markAllOk: 'Marcar todo OK',
    saveDraft: 'Guardar Borrador',
    sendToRepair: 'Enviar a Reparación',
    rejectIssue: 'Rechazar Problema',
    blockVehicle: 'Bloquear Vehículo',
    markAsFixed: 'Marcar como Reparado',
    viewFullReport: 'Ver Reporte Completo',
    fixAndResubmit: 'Corregir y Reenviar',
    viewAll: 'Ver todos',
    openVehicleCard: 'Abrir Vehículo',
    goToLogin: 'Ir al Inicio de Sesión',
    backToHome: 'Volver al Inicio',
    goToDashboard: 'Ir al Panel',
    outOfService: 'Fuera de Servicio',
    restoreService: 'Restaurar Servicio',
    signOut: 'Cerrar Sesión',
    reportProblem: 'Reportar Problema',
    viewAllNotifications: 'Ver todas las notificaciones',
    notifications: 'Notificaciones',
    new: 'nuevas',
    approveOk: 'Aprobar — OK',
    flagIssue: 'Marcar Problema',
    reviewInspection: 'Revisar Inspección',
    createDriverAccount: 'Crear Cuenta de Conductor',
    download: 'Descargar',
    pdf: 'PDF',
    email: 'Correo electrónico',

    // Form fields
    emailField: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    dateOfBirth: 'Fecha de Nacimiento',
    homeAddress: 'Dirección de Casa',
    address: 'Dirección',
    companyName: 'Nombre de la Empresa',
    industryType: 'Tipo de Industria',
    country: 'País',
    stateProvince: 'Estado / Provincia',
    city: 'Ciudad',
    licenseNumber: 'Licencia №',
    licenseClass: 'Clase de Licencia',
    expiryDate: 'Fecha de Vencimiento',
    medicalCardNumber: 'Tarjeta Médica №',
    medicalCardPhoto: 'Foto de Tarjeta Médica',
    licensePhoto: 'Foto de Licencia',
    hireDate: 'Fecha de Contratación',
    temporaryPassword: 'Contraseña Temporal',
    contactName: 'Nombre de Contacto',
    contactPhone: 'Teléfono de Contacto',
    vehicleNumber: 'Número de Vehículo',
    type: 'Tipo',
    make: 'Marca',
    model: 'Modelo',
    year: 'Año',
    plateNumber: 'Número de Placa',
    vin: 'VIN',
    odometer: 'Odómetro',
    dateLabel: 'Fecha',
    engineHours: 'Horas de Motor',
    vehiclePhoto: 'Foto del Vehículo',
    repairTitle: 'Título de Reparación',
    description: 'Descripción',
    issueCategory: 'Categoría del Problema',
    driver: 'Conductor',
    relatedIssue: 'Problema Relacionado',
    startedAt: 'Iniciado En',
    completedAt: 'Completado En',
    managersDecision: 'Decisión del Gerente',
    managersNote: 'Nota del Gerente',
    managerNotes: 'Notas del Gerente',
    invitationCode: 'Código de Invitación',
    cardNumber: 'Tarjeta №',
    class: 'Clase',
    language: 'Idioma',
    theme: 'Tema',
    search: 'Buscar...',
    createdAt: 'Creado El',
    view: 'Ver',
    inspectionLabel: 'Inspección',
    chooseLanguage: 'Elige el idioma de visualización de la aplicación.',
    customizeAppearance: 'Personaliza cómo se ve FleetCheck Pro en tu dispositivo.',
    driverDashboard: 'Panel',
    checked: 'verificados',
    okLabel: 'OK',
    issuesLabel: 'Problemas',
    describeIssue: 'Describe el problema…',
    driverSignature: 'Firma del Conductor',
    documentsLabel: 'Documentos',
    duration: 'Duración',
    photosTaken: 'Fotos tomadas',
    fixResubmit: 'Corregir y Reenviar',
    searchDrivers: 'Buscar conductores...',
    searchVehicles: 'Buscar vehículos...',
    searchRepairs: 'Buscar reparaciones...',
    searchIssues: 'Buscar problemas...',
    from: 'Desde',
    to: 'Hasta',

    // Section titles
    reportsCompliance: 'Reportes',
    myReports: 'Reportes',
    fleetVehicles: 'Vehículos',
    repairRequests: 'Reparaciones',
    inspectionResult: 'Detalles del Reporte',
    issueDetails: 'Detalles del Problema',
    driverProfile: 'Detalles del Conductor',
    vehicleDetail: 'Detalles del Vehículo',
    personalInformation: 'Información Personal',
    emergencyContact: 'Contacto de Emergencia',
    driverLicense: 'Licencia de Conducir',
    medicalCard: 'Tarjeta Médica',
    employment: 'Empleo',
    companyProfile: 'Perfil de la Empresa',
    fleetManager: 'Gerente de Flota',
    companyInformation: 'Información de la Empresa',
    languageSettings: 'Configuración de Idioma',
    appearance: 'Apariencia',
    repairInformation: 'Información de Reparación',
    basicInformation: 'Información Básica',
    issueInformation: 'Información del Problema',
    photos: 'Fotos',
    statusHistory: 'Historial de Estado',
    inspectionSummary: 'Resumen de Inspección',
    failedItems: 'Elementos Fallidos',
    vehiclePhotos: 'Fotos del Vehículo',
    inspectionHistory: 'Historial de Inspecciones',
    repairHistory: 'Historial de Reparaciones',
    recentInspections: 'Inspecciones Recientes',
    availableVehicles: 'Vehículos Disponibles',
    recentReports: 'Reportes Recientes',
    inspectionsPendingReview: 'Inspecciones Pendientes de Revisión',
    inspectionsThisWeek: 'Inspecciones Esta Semana',
    issuesByCategory: 'Problemas por Categoría',
    repairStatus: 'Estado de Reparaciones',
    startInspection: 'Iniciar Inspección',
    allowedVehicleTypes: 'Tipos de Vehículos Permitidos',

    // Table headers
    date: 'Fecha',
    vehicle: 'Vehículo',
    result: 'Resultado',
    reviewStatus: 'Estado de Revisión',
    actions: 'Acciones',
    status: 'Estado',
    priority: 'Prioridad',
    reportedBy: 'Reportado Por',
    signature: 'Firma',
    severity: 'Severidad',
    unit: 'Unidad',
    time: 'Hora',
    plate: 'Placa',
    category: 'Categoría',
    issue: 'Problema',
    licenseHash: 'Licencia №',
    licExpiry: 'Venc. Licencia',
    medExpiry: 'Venc. Médico',
    allowedVehicles: 'Vehículos Permitidos',
    inspectionType: 'Tipo de Inspección',
    inspectionDate: 'Fecha de Inspección',
    issueDate: 'Fecha del Problema',
    currentStatus: 'Estado Actual',

    // Statuses
    statusActive: 'Activo',
    statusPending: 'Pendiente',
    statusInactive: 'Inactivo',
    statusNeedsAttention: 'Necesita Atención',
    statusBlocked: 'Bloqueado',
    statusInRepair: 'En Reparación',
    statusDraft: 'Borrador',
    statusSubmitted: 'Enviado',
    statusOpen: 'Abierto',
    statusInProgress: 'En Progreso',
    statusCompleted: 'Completado',
    statusCancelled: 'Cancelado',
    statusUnderReview: 'En Revisión',
    statusFixed: 'Reparado',
    statusRejected: 'Rechazado',
    statusNeedsReview: 'Necesita Revisión',
    statusReviewedOk: 'Revisado OK',
    statusFlagged: 'Marcado',
    statusPassed: 'Aprobado',
    statusFailed: 'Fallido',

    // Priority / Severity
    priorityHigh: 'Alto',
    priorityMedium: 'Medio',
    priorityLow: 'Bajo',

    // Filter dropdowns
    allStatus: 'Todos los Estados',
    allTypes: 'Todos los Tipos',
    allResults: 'Todos los Resultados',
    allPriority: 'Todas las Prioridades',
    allSeverity: 'Todas las Severidades',
    all: 'Todos',
    fraudFlagged: 'Fraude Marcado',
    clean: 'Limpio',
    selectType: 'Seleccionar tipo',
    selectClass: 'Seleccionar clase',
    selectCategory: 'Seleccionar categoría',
    selectVehicle: 'Seleccionar vehículo',
    none: 'Ninguno',
    preTrip: 'Pre-Viaje',
    postTrip: 'Post-Viaje',

    // Inspections
    preTripInspection: 'Inspección Pre-Viaje',
    postTripInspection: 'Inspección Post-Viaje',
    pass: 'Aprobado',
    fail: 'Fallido',
    na: 'N/A',
    addComment: 'Agregar Comentario',
    signHere: 'Firmar aquí',
    submitInspection: 'Enviar Inspección',
    submittingInspection: 'Enviando...',
    previewPdf: 'Vista previa PDF',
    shareCopy: 'Compartir copia',
    opening: 'Abriendo...',
    sharing: 'Compartiendo...',
    preparingPdf: 'Preparando PDF...',
    reportPdfActionFailed: 'No se pudo completar la accion del PDF del informe.',
    inspectionPassed: 'Inspección Aprobada',
    inspectionFailed: 'Problemas Encontrados',
    vehicleReadyForOperation: 'El vehículo está listo para operar. Todos los elementos de inspección aprobados.',
    issuesFoundMessage: 'problema(s) encontrado(s). Se requiere revisión del gerente antes de operar este vehículo.',
    completedBeforeDeparting: 'Completar antes de salir',
    completedAfterArriving: 'Completar al llegar',

    // Checklist categories
    tiresWheels: 'Neumáticos y Ruedas',
    lightsSignals: 'Luces y Señales',
    brakes: 'Frenos',
    fluidLevels: 'Niveles de Fluidos',
    safetyEquipment: 'Equipo de Seguridad',
    documents: 'Documentos',

    // Repair categories
    tires: 'Neumáticos',
    lights: 'Luces',
    fluids: 'Fluidos',
    engine: 'Motor',
    exterior: 'Exterior',
    steering: 'Dirección',
    other: 'Otro',

    // Repair / Issue actions
    createRepairRequest: 'Crear Reparación',
    notifyManager: 'Notificar al Gerente',

    // Pending
    pendingApproval: 'Registro Pendiente de Aprobación',
    pendingMessage: 'Su registro ha sido enviado. Espere la aprobación del gerente.',
    whatHappensNext: '¿Qué sigue?',
    managerWillReview: 'Su gerente revisará su registro',
    youllReceiveEmail: 'Recibirá un correo cuando sea aprobado',
    onceApprovedLogin: 'Una vez aprobado, puede iniciar sesión y comenzar inspecciones',

    // IssueDetail
    fraudFlaggedLabel: 'Fraude Marcado',
    vehicleBlockedLabel: 'Vehículo Bloqueado',

    // Anti-Fraud Module (Photo Verification)
    antiFraudRisk: 'Riesgo',
    antiFraudSummaryTitle: 'Resumen Anti-Fraude',
    antiFraudSummaryHint: 'Verificaciones automáticas de autenticidad para fotos cargadas.',
    antiFraudAnalyzed: 'analizadas',
    inspectionReportTitle: 'Informe de Inspección',
    checklistItems: 'Lista de Verificación',
    photosHint: 'Haz clic en una foto para ampliarla.',
    submitted: 'Enviado',
    exifMissing: 'sin fecha EXIF',
    deviceUnknown: 'dispositivo desconocido',
    gpsMissing: 'sin GPS',
    antiFraudNoRecords: 'Aún no hay registros anti-fraude para este reporte.',
    antiFraudMaxRisk: 'Riesgo máximo',
    antiFraudHighRisk: 'Alto Riesgo',
    antiFraudSuspicious: 'Sospechoso',
    antiFraudNeedsReview: 'Necesita Revisión',
    antiFraudOk: 'OK',
    antiFraudTopReasons: 'Principales razones',
    antiFraudMostSuspiciousPhotos: 'Fotos más sospechosas',
    antiFraudPreviousVsCurrent: 'Comparación de foto anterior vs actual',
    antiFraudExactDuplicate: 'Duplicado exacto',
    antiFraudVisualDuplicate: 'Duplicado visual',
    antiFraudPreviousPhoto: 'Foto anterior',
    antiFraudCurrentPhoto: 'Foto actual',
    antiFraudFlagExactDuplicate: 'La foto ya fue usada antes (coincidencia exacta)',
    antiFraudFlagVisualDuplicate: 'La foto es visualmente similar a un reporte anterior',
    antiFraudFlagOldExif: 'La fecha de la foto es anterior a la inspección actual',
    antiFraudFlagDeviceChanged: 'El modelo del dispositivo cambió respecto a inspecciones anteriores',
    antiFraudFlagNoExif: 'No se encontraron metadatos EXIF',
    antiFraudFlagFileNameReused: 'El nombre del archivo fue reutilizado',
    antiFraudFlagGpsOutlier: 'El GPS de la foto está lejos de las demás fotos de esta inspección',
    antiFraudGpsMapTitle: 'Ubicaciones de las fotos',
    antiFraudGpsMapHint: 'Los marcadores muestran dónde se tomó cada foto. El círculo azul es la geocerca de 300 m alrededor del centro.',
    antiFraudGpsOutlier: 'Una o más fotos se tomaron fuera del radio de 300 m respecto a las demás.',
    antiFraudReanalyze: 'Reanalizar',
    antiFraudReanalyzing: 'Analizando…',
    antiFraudVerdictGpsOutlier: 'La ubicación de la foto está lejos de las otras fotos de esta inspección.',
    antiFraudVerdictExactDuplicate: 'Probable reutilización de foto de una inspección anterior (coincidencia exacta).',
    antiFraudVerdictVisualDuplicate: 'Probable reutilización de foto con pequeñas ediciones (duplicado visual).',
    antiFraudVerdictOldExif: 'Requiere revisión manual: la foto parece tomada antes de esta inspección.',
    antiFraudVerdictDeviceChanged: 'Requiere revisión manual: el modelo del dispositivo cambió respecto a inspecciones recientes.',
    antiFraudVerdictNoExif: 'Señal de confianza limitada: faltan metadatos EXIF.',
    antiFraudVerdictFileNameReused: 'Señal débil: el nombre del archivo fue reutilizado.',
    antiFraudVerdictHighRisk: 'Se detectó un patrón de alto riesgo. Se recomienda validación manual.',
    antiFraudVerdictSuspicious: 'Se detectó un patrón sospechoso. Se recomienda validación manual.',
    antiFraudVerdictNeedsReview: 'Se detectaron indicadores de riesgo. Revise manualmente.',
    antiFraudVerdictNoIndicators: 'No se detectaron indicadores significativos de fraude.',

    // Driver dashboard stats
    tripsThisMonth: 'Viajes Este Mes',
    inspectionsPassed: 'Inspecciones Aprobadas',
    openIssues: 'Problemas Abiertos',
    fuelEfficiency: 'Eficiencia de Combustible',
    submitRepairRequest: 'Enviar solicitud de reparación',
    logOutOfApp: 'Cerrar sesión de la app',

    // Empty states
    noDriversFound: 'No se encontraron conductores.',
    noVehiclesFound: 'No se encontraron vehículos.',
    noRepairsFound: 'No se encontraron reparaciones.',
    noReportsFound: 'No se encontraron reportes.',
    noIssuesFound: 'No se encontraron problemas.',
    issueNotFound: 'Problema no encontrado.',
    noneAssigned: 'Ninguno asignado',
    noPhotosAttached: 'No hay fotos adjuntas a este problema',

    // Misc
    showing: 'Mostrando',
    of: 'de',
    lightMode: 'Modo Claro',
    darkMode: 'Modo Oscuro',
    selectLanguage: 'Seleccionar idioma',
    english: 'Inglés',
    ukrainian: 'Ucraniano',
    spanish: 'Español',
    french: 'Francés',

    // Registration
    workspaceReady: '¡Su espacio está listo!',
    workspaceSetupSuccess: 'Su espacio empresarial ha sido configurado exitosamente.',
    workspaceSetupInfo: 'Ahora puede agregar vehículos, invitar conductores y comenzar a gestionar inspecciones.',
    createYourAccount: 'Cree Su Cuenta',
    driverRegSubtitle: 'Cree su cuenta de conductor usando el código de invitación de su empresa.',
    uploadDriverLicensePhoto: 'Subir Foto de Licencia de Conducir',
    frontSide: 'Lado Frontal',
    backSide: 'Lado Trasero',
    iAgreeToThe: 'Acepto los',
    termsOfService: 'Términos de Servicio',
    privacyPolicy: 'Política de Privacidad',
    iConfirmAccurate: 'Confirmo que toda la información proporcionada es precisa.',
    askManagerForCode: 'Solicite a su gerente de flota el código de invitación de la empresa.',
    min8Chars: 'Mín. 8 caracteres',
    repeatPassword: 'Repetir contraseña',
    clickToUpload: 'Haga clic para subir o arrastre y suelte',
    pngJpgUpTo10mb: 'PNG, JPG hasta 10 MB',
    jpgPng: 'JPG, PNG',

    // Landing page
    fleetOverview: 'Resumen de Flota',
    preTripDone: 'Pre-Viaje Completado',
    allItemsPassed: 'Todos los elementos aprobados',
    highPriority: 'Alta Prioridad',
    everythingYourFleetNeeds: 'Todo lo que su flota necesita',
    fleetManagementSaasPlatform: 'Plataforma SaaS de Gestión de Flotas',
    landingSubtitle: 'Simplifique las inspecciones pre y post viaje, gestione su flota, rastree condiciones de vehículos, fotos, reparaciones y manténgase en cumplimiento — todo en una plataforma.',
    landingFeaturesIntro: 'Desde listas de verificación diarias de conductores hasta informes de cumplimiento, FleetCheck Pro mantiene toda su operación de flota funcionando sin problemas.',
    inspectionsDaily: 'Inspecciones Diarias',
    companies: 'Empresas',
    uptime: 'Disponibilidad',
    countries: 'Países',
    digitalInspections: 'Inspecciones Digitales',
    digitalInspectionsDesc: 'Listas de verificación pre y post viaje con captura de fotos y firmas digitales.',
    fleetManagement: 'Gestión de Flota',
    fleetManagementDesc: 'Rastree todos los vehículos, equipos y activos en un panel centralizado.',
    complianceReady: 'Listo para el Cumplimiento',
    complianceReadyDesc: 'Reportes conformes con DOT, registros de conductores y documentación exportable.',
    photoEvidence: 'Evidencia Fotográfica',
    photoEvidenceDesc: 'Capture y almacene fotos del estado del vehículo con detección de duplicados.',
    repairTracking: 'Seguimiento de Reparaciones',
    repairTrackingDesc: 'Registre problemas y rastree reparaciones gestionadas por gerentes hasta su finalización.',
    analyticsReports: 'Analítica e Informes',
    analyticsReportsDesc: 'Información procesable sobre la salud de la flota, rendimiento de conductores y tendencias.',
    footerCopyright: '© 2026 FleetCheck Pro. Todos los derechos reservados.',

    // Industry types
    truckingCompany: 'Empresa de Transporte',
    truckingCompanyDesc: 'Flotas de camiones de larga distancia y regionales',
    constructionEquipment: 'Equipo de Construcción',
    constructionEquipmentDesc: 'Excavadoras, bulldozers y maquinaria pesada',
    boomLiftRental: 'Alquiler de Elevadores',
    boomLiftRentalDesc: 'Plataformas de trabajo aéreo y equipos de elevación',
    deliveryFleet: 'Flota de Entregas',
    deliveryFleetDesc: 'Vehículos de entrega de última milla y servicio de mensajería',
    taxiPassenger: 'Taxi / Pasajeros',
    taxiPassengerDesc: 'Flotas de transporte compartido y de pasajeros',
    serviceVehicles: 'Vehículos de Servicio',
    serviceVehiclesDesc: 'Flotas utilitarias, de mantenimiento y servicio',
    otherFleet: 'Otro',
    otherFleetDesc: 'Tipo de flota personalizado u operaciones mixtas',
  },
  fr: {
    // App
    appName: 'FleetCheck Pro',
    tagline: 'Inspections numériques de véhicules pour des flottes plus sûres',
    getStarted: 'Commencer',
    companyLogin: 'Connexion Entreprise',
    driverRegistration: 'Inscription Conducteur',

    // Nav
    dashboard: 'Tableau de bord',
    vehicles: 'Véhicules',
    drivers: 'Conducteurs',
    inspections: 'Inspections',
    reports: 'Rapports',
    issues: 'Problèmes',
    repairs: 'Réparations',
    settings: 'Paramètres',
    home: 'Accueil',
    inspect: 'Inspecter',
    profile: 'Profil',

    // Nav back links
    backToDrivers: 'Retour aux Conducteurs',
    backToFleet: 'Retour aux Véhicules',
    backToLogin: 'Retour à la Connexion',
    backToInspection: "Retour à l'Inspection",
    backToIssues: 'Retour aux Problèmes',
    backToRepairs: 'Retour aux Réparations',
    backToDashboard: 'Retour au Tableau de bord',

    // Auth
    login: 'Connexion',
    logout: 'Déconnexion',
    signIn: 'Se connecter',
    signUp: "S'inscrire",
    createAccount: 'Créer un Compte',
    forgotPassword: 'Mot de passe oublié?',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    signInWithGoogle: 'Se connecter avec Google',
    signUpWithGoogle: "S'inscrire avec Google",
    companyAccountRegistration: 'Inscription compte entreprise',
    createYourCompanyAccount: 'Créez votre compte entreprise',
    signInToYourAccount: 'Connectez-vous à votre compte',
    enterLoginCredentials: 'Entrez vos identifiants pour commencer.',
    or: 'ou',
    atLeast8Chars: 'Au moins 8 caractères',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    passwordsMatch: 'Les mots de passe correspondent',

    // Buttons
    save: 'Enregistrer',
    cancel: 'Annuler',
    submit: 'Soumettre',
    next: 'Suivant',
    back: 'Retour',
    finish: 'Terminer',
    edit: 'Modifier',
    delete: 'Supprimer',
    saveChanges: 'Enregistrer les Modifications',
    saveDriver: 'Enregistrer le Conducteur',
    editDriver: 'Modifier le Conducteur',
    addDriver: 'Ajouter un Conducteur',
    addVehicle: 'Ajouter un Véhicule',
    addPhoto: 'Ajouter une Photo',
    fromGallery: 'Depuis la galerie',
    removePhoto: 'Supprimer la photo',
    itemTitle: 'Titre de l element',
    checklistItemPlaceholder: 'Verifier les freins de service',
    createTemplateCategoriesFirst: 'Creez d abord des categories dans Parametres',
    moveUp: 'Monter',
    moveDown: 'Descendre',
    removeItem: 'Supprimer l element',
    requiredLabel: 'Obligatoire',
    requiresPhotoLabel: 'Photo requise',
    driverInstructionsPlaceholder: 'Instructions au conducteur pour ce controle.',
    uploadReferencePhoto: 'Televerser une photo de reference',
    referencePhoto: 'Photo de reference',
    uploading: 'Televersement...',
    openDetails: 'Ouvrir les details',
    hideDetails: 'Masquer les details',
    requiresPhotoBeforeSubmit: 'Cet element necessite au moins une photo avant soumission.',
    referencePhotoUploadFailed: 'Echec du televersement de la photo de reference.',
    editVehicle: 'Modifier le Véhicule',
    editRepair: 'Modifier la Réparation',
    newRepairRequest: 'Nouvelle Réparation',
    newRequest: 'Nouvelle Demande',
    submitRequest: 'Soumettre la Demande',
    saveReview: 'Enregistrer la Révision',
    review: 'Réviser',
    markAllOk: 'Tout marquer OK',
    saveDraft: 'Enregistrer le Brouillon',
    sendToRepair: 'Envoyer en Réparation',
    rejectIssue: 'Rejeter le Problème',
    blockVehicle: 'Bloquer le Véhicule',
    markAsFixed: 'Marquer comme Réparé',
    viewFullReport: 'Voir le Rapport Complet',
    fixAndResubmit: 'Corriger et Resoumettre',
    viewAll: 'Voir tout',
    openVehicleCard: 'Ouvrir le Véhicule',
    goToLogin: 'Aller à la Connexion',
    backToHome: "Retour à l'Accueil",
    goToDashboard: 'Aller au Tableau de bord',
    outOfService: 'Hors Service',
    restoreService: 'Restaurer le Service',
    signOut: 'Se Déconnecter',
    reportProblem: 'Signaler un Problème',
    viewAllNotifications: 'Voir toutes les notifications',
    notifications: 'Notifications',
    new: 'nouvelles',
    approveOk: 'Approuver — OK',
    flagIssue: 'Signaler le Problème',
    reviewInspection: "Réviser l'Inspection",
    createDriverAccount: 'Créer un Compte Conducteur',
    download: 'Télécharger',
    pdf: 'PDF',
    email: 'E-mail',

    // Form fields
    emailField: 'E-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le Mot de passe',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    phone: 'Téléphone',
    dateOfBirth: 'Date de Naissance',
    homeAddress: 'Adresse du Domicile',
    address: 'Adresse',
    companyName: "Nom de l'Entreprise",
    industryType: "Type d'Industrie",
    country: 'Pays',
    stateProvince: 'État / Province',
    city: 'Ville',
    licenseNumber: 'Permis №',
    licenseClass: 'Classe de Permis',
    expiryDate: "Date d'Expiration",
    medicalCardNumber: 'Carte Médicale №',
    medicalCardPhoto: 'Photo de Carte Médicale',
    licensePhoto: 'Photo du Permis',
    hireDate: "Date d'Embauche",
    temporaryPassword: 'Mot de passe Temporaire',
    contactName: 'Nom du Contact',
    contactPhone: 'Téléphone du Contact',
    vehicleNumber: 'Numéro du Véhicule',
    type: 'Type',
    make: 'Marque',
    model: 'Modèle',
    year: 'Année',
    plateNumber: "Numéro d'Immatriculation",
    vin: 'NIV',
    odometer: 'Odomètre',
    dateLabel: 'Date',
    engineHours: 'Heures Moteur',
    vehiclePhoto: 'Photo du Véhicule',
    repairTitle: 'Titre de la Réparation',
    description: 'Description',
    issueCategory: 'Catégorie du Problème',
    driver: 'Conducteur',
    relatedIssue: 'Problème Associé',
    startedAt: 'Commencé le',
    completedAt: 'Terminé le',
    managersDecision: 'Décision du Gestionnaire',
    managersNote: 'Note du Gestionnaire',
    managerNotes: 'Notes du Gestionnaire',
    invitationCode: "Code d'Invitation",
    cardNumber: 'Carte №',
    class: 'Classe',
    language: 'Langue',
    theme: 'Thème',
    search: 'Rechercher...',
    createdAt: 'Créé le',
    view: 'Voir',
    inspectionLabel: 'Inspection',
    chooseLanguage: "Choisissez la langue d'affichage de l'application.",
    customizeAppearance: "Personnalisez l'apparence de FleetCheck Pro sur votre appareil.",
    driverDashboard: 'Tableau de bord',
    checked: 'vérifiés',
    okLabel: 'OK',
    issuesLabel: 'Problèmes',
    describeIssue: 'Décrivez le problème…',
    driverSignature: 'Signature du Conducteur',
    documentsLabel: 'Documents',
    duration: 'Durée',
    photosTaken: 'Photos prises',
    fixResubmit: 'Corriger et Soumettre',
    searchDrivers: 'Rechercher des conducteurs...',
    searchVehicles: 'Rechercher des véhicules...',
    searchRepairs: 'Rechercher des réparations...',
    searchIssues: 'Rechercher des problèmes...',
    from: 'De',
    to: 'À',

    // Section titles
    reportsCompliance: 'Rapports',
    myReports: 'Rapports',
    fleetVehicles: 'Véhicules',
    repairRequests: 'Réparations',
    inspectionResult: 'Détails du Rapport',
    issueDetails: 'Détails du Problème',
    driverProfile: 'Détails du Conducteur',
    vehicleDetail: 'Détails du Véhicule',
    personalInformation: 'Informations Personnelles',
    emergencyContact: "Contact d'Urgence",
    driverLicense: 'Permis de Conduire',
    medicalCard: 'Carte Médicale',
    employment: 'Emploi',
    companyProfile: "Profil de l'Entreprise",
    fleetManager: 'Gestionnaire de Flotte',
    companyInformation: "Informations sur l'Entreprise",
    languageSettings: 'Paramètres de Langue',
    appearance: 'Apparence',
    repairInformation: 'Informations sur la Réparation',
    basicInformation: 'Informations de Base',
    issueInformation: 'Informations sur le Problème',
    photos: 'Photos',
    statusHistory: 'Historique des Statuts',
    inspectionSummary: "Résumé de l'Inspection",
    failedItems: 'Éléments Échoués',
    vehiclePhotos: 'Photos du Véhicule',
    inspectionHistory: 'Historique des Inspections',
    repairHistory: 'Historique des Réparations',
    recentInspections: 'Inspections Récentes',
    availableVehicles: 'Véhicules Disponibles',
    recentReports: 'Rapports Récents',
    inspectionsPendingReview: 'Inspections en Attente de Révision',
    inspectionsThisWeek: 'Inspections Cette Semaine',
    issuesByCategory: 'Problèmes par Catégorie',
    repairStatus: 'État des Réparations',
    startInspection: "Démarrer l'Inspection",
    allowedVehicleTypes: 'Types de Véhicules Autorisés',

    // Table headers
    date: 'Date',
    vehicle: 'Véhicule',
    result: 'Résultat',
    reviewStatus: 'Statut de Révision',
    actions: 'Actions',
    status: 'Statut',
    priority: 'Priorité',
    reportedBy: 'Signalé Par',
    signature: 'Signature',
    severity: 'Gravité',
    unit: 'Unité',
    time: 'Heure',
    plate: 'Plaque',
    category: 'Catégorie',
    issue: 'Problème',
    licenseHash: 'Permis №',
    licExpiry: 'Exp. Permis',
    medExpiry: 'Exp. Médical',
    allowedVehicles: 'Véhicules Autorisés',
    inspectionType: "Type d'Inspection",
    inspectionDate: "Date d'Inspection",
    issueDate: 'Date du Problème',
    currentStatus: 'Statut Actuel',

    // Statuses
    statusActive: 'Actif',
    statusPending: 'En Attente',
    statusInactive: 'Inactif',
    statusNeedsAttention: "Besoin d'Attention",
    statusBlocked: 'Bloqué',
    statusInRepair: 'En Réparation',
    statusDraft: 'Brouillon',
    statusSubmitted: 'Soumis',
    statusOpen: 'Ouvert',
    statusInProgress: 'En Cours',
    statusCompleted: 'Terminé',
    statusCancelled: 'Annulé',
    statusUnderReview: 'En Révision',
    statusFixed: 'Réparé',
    statusRejected: 'Rejeté',
    statusNeedsReview: 'Révision Requise',
    statusReviewedOk: 'Révisé OK',
    statusFlagged: 'Signalé',
    statusPassed: 'Réussi',
    statusFailed: 'Échoué',

    // Priority / Severity
    priorityHigh: 'Élevé',
    priorityMedium: 'Moyen',
    priorityLow: 'Faible',

    // Filter dropdowns
    allStatus: 'Tous les Statuts',
    allTypes: 'Tous les Types',
    allResults: 'Tous les Résultats',
    allPriority: 'Toutes les Priorités',
    allSeverity: 'Toutes les Gravités',
    all: 'Tous',
    fraudFlagged: 'Fraude Signalée',
    clean: 'Propre',
    selectType: 'Sélectionner le type',
    selectClass: 'Sélectionner la classe',
    selectCategory: 'Sélectionner la catégorie',
    selectVehicle: 'Sélectionner le véhicule',
    none: 'Aucun',
    preTrip: 'Pré-Voyage',
    postTrip: 'Post-Voyage',

    // Inspections
    preTripInspection: 'Inspection Pré-Voyage',
    postTripInspection: 'Inspection Post-Voyage',
    pass: 'Réussi',
    fail: 'Échoué',
    na: 'N/A',
    addComment: 'Ajouter un Commentaire',
    signHere: 'Signer ici',
    submitInspection: "Soumettre l'Inspection",
    submittingInspection: 'Envoi en cours...',
    previewPdf: 'Apercu PDF',
    shareCopy: 'Partager une copie',
    opening: 'Ouverture...',
    sharing: 'Partage...',
    preparingPdf: 'Preparation du PDF...',
    reportPdfActionFailed: 'Echec de l action PDF du rapport.',
    inspectionPassed: 'Inspection Réussie',
    inspectionFailed: 'Problèmes Trouvés',
    vehicleReadyForOperation: "Le véhicule est prêt pour l'opération. Tous les éléments d'inspection ont réussi.",
    issuesFoundMessage: "problème(s) trouvé(s). Révision du gestionnaire requise avant d'opérer ce véhicule.",
    completedBeforeDeparting: 'À compléter avant le départ',
    completedAfterArriving: "À compléter à l'arrivée",

    // Checklist categories
    tiresWheels: 'Pneus et Roues',
    lightsSignals: 'Lumières et Signaux',
    brakes: 'Freins',
    fluidLevels: 'Niveaux de Fluides',
    safetyEquipment: 'Équipement de Sécurité',
    documents: 'Documents',

    // Repair categories
    tires: 'Pneus',
    lights: 'Lumières',
    fluids: 'Fluides',
    engine: 'Moteur',
    exterior: 'Extérieur',
    steering: 'Direction',
    other: 'Autre',

    // Repair / Issue actions
    createRepairRequest: 'Créer une Réparation',
    notifyManager: 'Notifier le Gestionnaire',

    // Pending
    pendingApproval: "Inscription en attente d'approbation",
    pendingMessage: "Votre inscription a été soumise. Veuillez attendre l'approbation du gestionnaire.",
    whatHappensNext: 'Que se passe-t-il ensuite?',
    managerWillReview: 'Votre gestionnaire examinera votre inscription',
    youllReceiveEmail: 'Vous recevrez un e-mail lors de votre approbation',
    onceApprovedLogin: 'Une fois approuvé, vous pouvez vous connecter et commencer les inspections',

    // IssueDetail
    fraudFlaggedLabel: 'Fraude Signalée',
    vehicleBlockedLabel: 'Véhicule Bloqué',

    // Anti-Fraud Module (Photo Verification)
    antiFraudRisk: 'Risque',
    antiFraudSummaryTitle: 'Résumé Anti-Fraude',
    antiFraudSummaryHint: "Contrôles automatiques d'authenticité pour les photos téléchargées.",
    antiFraudAnalyzed: 'analysées',
    inspectionReportTitle: "Rapport d'Inspection",
    checklistItems: 'Liste de Vérification',
    photosHint: "Cliquez sur une photo pour l'agrandir.",
    submitted: 'Soumis',
    exifMissing: 'pas de date EXIF',
    deviceUnknown: 'appareil inconnu',
    gpsMissing: 'pas de GPS',
    antiFraudNoRecords: "Aucun enregistrement anti-fraude pour ce rapport pour le moment.",
    antiFraudMaxRisk: 'Risque max',
    antiFraudHighRisk: 'Risque Élevé',
    antiFraudSuspicious: 'Suspect',
    antiFraudNeedsReview: 'Révision Requise',
    antiFraudOk: 'OK',
    antiFraudTopReasons: 'Principales raisons',
    antiFraudMostSuspiciousPhotos: 'Photos les plus suspectes',
    antiFraudPreviousVsCurrent: 'Comparaison photo précédente vs actuelle',
    antiFraudExactDuplicate: 'Doublon exact',
    antiFraudVisualDuplicate: 'Doublon visuel',
    antiFraudPreviousPhoto: 'Photo précédente',
    antiFraudCurrentPhoto: 'Photo actuelle',
    antiFraudFlagExactDuplicate: 'La photo a déjà été utilisée (correspondance exacte)',
    antiFraudFlagVisualDuplicate: 'La photo est visuellement similaire à un rapport précédent',
    antiFraudFlagOldExif: "La date de la photo est antérieure à l'inspection actuelle",
    antiFraudFlagDeviceChanged: "Le modèle d'appareil a changé par rapport aux inspections précédentes",
    antiFraudFlagNoExif: 'Aucune métadonnée EXIF trouvée',
    antiFraudFlagFileNameReused: 'Le nom du fichier a été réutilisé',
    antiFraudFlagGpsOutlier: 'Le GPS de la photo est éloigné des autres photos de cette inspection',
    antiFraudGpsMapTitle: 'Emplacements des photos',
    antiFraudGpsMapHint: 'Les marqueurs indiquent où chaque photo a été prise. Le cercle bleu correspond à la géo-zone de 300 m autour du centre.',
    antiFraudGpsOutlier: "Une ou plusieurs photos ont été prises hors du rayon de 300 m par rapport aux autres photos.",
    antiFraudReanalyze: 'Réanalyser',
    antiFraudReanalyzing: 'Analyse…',
    antiFraudVerdictGpsOutlier: "L'emplacement de la photo est éloigné des autres photos de cette inspection.",
    antiFraudVerdictExactDuplicate: "Photo probablement réutilisée depuis une inspection précédente (correspondance exacte).",
    antiFraudVerdictVisualDuplicate: "Photo probablement réutilisée avec de légères modifications (doublon visuel).",
    antiFraudVerdictOldExif: "Révision manuelle requise : la photo semble antérieure à cette inspection.",
    antiFraudVerdictDeviceChanged: "Révision manuelle requise : le modèle d'appareil a changé par rapport aux inspections récentes.",
    antiFraudVerdictNoExif: 'Signal de confiance limité : métadonnées EXIF absentes.',
    antiFraudVerdictFileNameReused: 'Signal faible : le nom de fichier a été réutilisé.',
    antiFraudVerdictHighRisk: 'Un schéma à haut risque a été détecté. Validation manuelle recommandée.',
    antiFraudVerdictSuspicious: 'Un schéma suspect a été détecté. Validation manuelle recommandée.',
    antiFraudVerdictNeedsReview: 'Des indicateurs de risque ont été détectés. Merci de vérifier.',
    antiFraudVerdictNoIndicators: "Aucun indicateur significatif de fraude détecté.",

    // Driver dashboard stats
    tripsThisMonth: 'Voyages Ce Mois',
    inspectionsPassed: 'Inspections Réussies',
    openIssues: 'Problèmes Ouverts',
    fuelEfficiency: 'Efficacité Carburant',
    submitRepairRequest: 'Soumettre une demande de réparation',
    logOutOfApp: "Se déconnecter de l'application",

    // Empty states
    noDriversFound: 'Aucun conducteur trouvé.',
    noVehiclesFound: 'Aucun véhicule trouvé.',
    noRepairsFound: 'Aucune réparation trouvée.',
    noReportsFound: 'Aucun rapport trouvé.',
    noIssuesFound: 'Aucun problème trouvé.',
    issueNotFound: 'Problème non trouvé.',
    noneAssigned: 'Aucun assigné',
    noPhotosAttached: 'Aucune photo jointe à ce problème',

    // Misc
    showing: 'Affichage',
    of: 'de',
    lightMode: 'Mode Clair',
    darkMode: 'Mode Sombre',
    selectLanguage: 'Sélectionner la langue',
    english: 'Anglais',
    ukrainian: 'Ukrainien',
    spanish: 'Espagnol',
    french: 'Français',

    // Registration
    workspaceReady: 'Votre espace est prêt!',
    workspaceSetupSuccess: 'Votre espace entreprise a été configuré avec succès.',
    workspaceSetupInfo: "Vous pouvez maintenant ajouter des véhicules, inviter des conducteurs et commencer à gérer les inspections.",
    createYourAccount: 'Créez Votre Compte',
    driverRegSubtitle: "Créez votre compte conducteur en utilisant le code d'invitation de votre entreprise.",
    uploadDriverLicensePhoto: 'Télécharger la Photo du Permis de Conduire',
    frontSide: 'Face Avant',
    backSide: 'Face Arrière',
    iAgreeToThe: "J'accepte les",
    termsOfService: "Conditions d'Utilisation",
    privacyPolicy: 'Politique de Confidentialité',
    iConfirmAccurate: 'Je confirme que toutes les informations fournies sont exactes.',
    askManagerForCode: "Demandez à votre gestionnaire de flotte le code d'invitation de l'entreprise.",
    min8Chars: 'Min. 8 caractères',
    repeatPassword: 'Répéter le mot de passe',
    clickToUpload: 'Cliquez pour télécharger ou glisser-déposer',
    pngJpgUpTo10mb: 'PNG, JPG jusqu\'à 10 Mo',
    jpgPng: 'JPG, PNG',

    // Landing page
    fleetOverview: 'Aperçu de la Flotte',
    preTripDone: 'Pré-Voyage Terminé',
    allItemsPassed: 'Tous les éléments réussis',
    highPriority: 'Haute Priorité',
    everythingYourFleetNeeds: 'Tout ce dont votre flotte a besoin',
    fleetManagementSaasPlatform: 'Plateforme SaaS de Gestion de Flotte',
    landingSubtitle: 'Simplifiez les inspections pré et post-voyage, gérez votre flotte, suivez les conditions des véhicules, photos, réparations et restez conforme — tout sur une seule plateforme.',
    landingFeaturesIntro: 'Des listes de contrôle quotidiennes des conducteurs aux rapports de conformité, FleetCheck Pro maintient toute votre opération de flotte en bon état de fonctionnement.',
    inspectionsDaily: 'Inspections Quotidiennes',
    companies: 'Entreprises',
    uptime: 'Disponibilité',
    countries: 'Pays',
    digitalInspections: 'Inspections Numériques',
    digitalInspectionsDesc: 'Listes de contrôle pré et post-voyage avec capture photo et signatures numériques.',
    fleetManagement: 'Gestion de Flotte',
    fleetManagementDesc: 'Suivez tous les véhicules, équipements et actifs dans un tableau de bord centralisé.',
    complianceReady: 'Prêt pour la Conformité',
    complianceReadyDesc: 'Rapports conformes DOT, journaux de bord des conducteurs et documentation exportable.',
    photoEvidence: 'Preuves Photographiques',
    photoEvidenceDesc: "Capturez et stockez des photos de l'état du véhicule avec détection des doublons.",
    repairTracking: 'Suivi des Réparations',
    repairTrackingDesc: "Enregistrez les problèmes et suivez les réparations gérées par les responsables jusqu'à leur achèvement.",
    analyticsReports: 'Analytique et Rapports',
    analyticsReportsDesc: "Informations exploitables sur la santé de la flotte, la performance des conducteurs et les tendances.",
    footerCopyright: '© 2026 FleetCheck Pro. Tous droits réservés.',

    // Industry types
    truckingCompany: 'Entreprise de Transport',
    truckingCompanyDesc: 'Flottes de camions longue distance et régionales',
    constructionEquipment: 'Équipement de Construction',
    constructionEquipmentDesc: 'Excavatrices, bulldozers et machinerie lourde',
    boomLiftRental: 'Location de Nacelles',
    boomLiftRentalDesc: "Plateformes de travail aérien et équipements de levage",
    deliveryFleet: 'Flotte de Livraison',
    deliveryFleetDesc: 'Véhicules de livraison du dernier kilomètre et service de messagerie',
    taxiPassenger: 'Taxi / Passagers',
    taxiPassengerDesc: 'Flottes de covoiturage et de transport de passagers',
    serviceVehicles: 'Véhicules de Service',
    serviceVehiclesDesc: 'Flottes utilitaires, de maintenance et de service',
    otherFleet: 'Autre',
    otherFleetDesc: 'Type de flotte personnalisé ou opérations mixtes',
  },
}

export const useAppStore = defineStore('app', () => {
  const savedTheme = localStorage.getItem('theme') as 'light' | 'dark' | null
  const prefDark = window.matchMedia('(prefers-color-scheme: dark)').matches
  const theme = ref<'light' | 'dark'>(savedTheme ?? (prefDark ? 'dark' : 'light'))
  const language = ref<Language>(normalizeLanguage(localStorage.getItem('lang')))
  const role = ref<Role>(null)
  const inspectionResult = ref<'pass' | 'fail' | null>(null)

  watch(theme, (val) => {
    const root = document.documentElement
    if (val === 'dark') root.classList.add('dark')
    else root.classList.remove('dark')
    localStorage.setItem('theme', val)
  }, { immediate: true })

  watch(language, (val) => {
    localStorage.setItem('lang', normalizeLanguage(val))
  })

  function toggleTheme() {
    theme.value = theme.value === 'light' ? 'dark' : 'light'
  }

  function setLanguage(lang: Language) {
    language.value = normalizeLanguage(lang)
  }

  function setRole(r: Role) {
    role.value = r
  }

  function setInspectionResult(r: 'pass' | 'fail') {
    inspectionResult.value = r
  }

  function t(key: string): string {
    const currentLanguage = normalizeLanguage(language.value)
    return translations[currentLanguage][key] ?? translations.en[key] ?? key
  }

  return { theme, language, role, inspectionResult, toggleTheme, setLanguage, setRole, setInspectionResult, t }
})
