import { formatDateTime } from '@/lib/dateFormat'
import { normalizePhotoUrls, resolvePhotoUrl } from '@/lib/photoUrls'
import { readSignatureFallback, readSignatureFallbackFromDb } from '@/lib/signatureFallback'
import { supabase } from '@/lib/supabase'

type Language = 'en' | 'uk' | 'es' | 'fr'
type ReportResult = 'pass' | 'fail' | 'draft'

type Dict = {
  appName: string
  reportTitle: string
  reportId: string
  generated: string
  generatedBy: string
  page: string
  vehicleSummary: string
  result: string
  review: string
  unit: string
  plate: string
  vin: string
  driver: string
  inspectionType: string
  submitted: string
  preTrip: string
  postTrip: string
  passed: string
  failed: string
  notApplicable: string
  issues: string
  photos: string
  driverSignature: string
  noSignature: string
  signedBy: string
  signedAt: string
  checklistItems: string
  noChecklist: string
  checklistFallback: string
  photoRequired: string
  notes: string
  photoReferenceAttached: string
  photoReferencesAttached: string
  issuesSection: string
  noIssues: string
  issueFallback: string
  severityLow: string
  severityMedium: string
  severityHigh: string
  repairPrefix: string
  underReview: string
  inRepair: string
  fixed: string
  rejected: string
  noReviewRequired: string
  draft: string
  notAnswered: string
  popupBlocked: string
  reportLoadFailed: string
  shareText: string
  noPhoto: string
  shareUnavailable: string
}

const DICT: Record<Language, Dict> = {
  en: {
    appName: 'FleetCheck',
    reportTitle: 'Inspection Report',
    reportId: 'Report ID',
    generated: 'Generated',
    generatedBy: 'Generated by FleetCheck',
    page: 'Page',
    vehicleSummary: 'Vehicle Summary',
    result: 'Result',
    review: 'Review',
    unit: 'Unit',
    plate: 'Plate',
    vin: 'VIN',
    driver: 'Driver',
    inspectionType: 'Inspection type',
    submitted: 'Submitted',
    preTrip: 'Pre-trip',
    postTrip: 'Post-trip',
    passed: 'Passed',
    failed: 'Failed',
    notApplicable: 'N/A',
    issues: 'Issues',
    photos: 'Photos',
    driverSignature: 'Driver Signature',
    noSignature: 'No signature was attached to this inspection.',
    signedBy: 'Signed by',
    signedAt: 'Signed at',
    checklistItems: 'Checklist Items',
    noChecklist: 'No checklist items were recorded for this inspection.',
    checklistFallback: 'Checklist item',
    photoRequired: 'Photo required',
    notes: 'Notes',
    photoReferenceAttached: 'photo reference attached',
    photoReferencesAttached: 'photo references attached',
    issuesSection: 'Issues',
    noIssues: 'No issues were generated for this inspection.',
    issueFallback: 'Inspection issue',
    severityLow: 'Low',
    severityMedium: 'Medium',
    severityHigh: 'High',
    repairPrefix: 'Repair',
    underReview: 'Under Review',
    inRepair: 'In Repair',
    fixed: 'Fixed',
    rejected: 'Rejected',
    noReviewRequired: 'No review required',
    draft: 'Draft',
    notAnswered: 'Not answered',
    popupBlocked: 'Popup blocked. Allow popups to preview the PDF.',
    shareText: 'Inspection report PDF',
    reportLoadFailed: 'Report could not be loaded.',
    noPhoto: 'No photo',
    shareUnavailable: 'Share is not available on this device. The PDF will be downloaded instead.',
  },
  uk: {
    appName: 'FleetCheck',
    reportTitle: 'Звіт інспекції',
    reportId: 'ID звіту',
    generated: 'Згенеровано',
    generatedBy: 'Згенеровано FleetCheck',
    page: 'Сторінка',
    vehicleSummary: 'Інформація про транспорт',
    result: 'Результат',
    review: 'Перевірка',
    unit: 'Юніт',
    plate: 'Номер',
    vin: 'VIN',
    driver: 'Водій',
    inspectionType: 'Тип інспекції',
    submitted: 'Надіслано',
    preTrip: 'Перед рейсом',
    postTrip: 'Після рейсу',
    passed: 'Пройдено',
    failed: 'Не пройдено',
    notApplicable: 'Н/З',
    issues: 'Проблеми',
    photos: 'Фото',
    driverSignature: 'Підпис водія',
    noSignature: 'Підпис не було додано до цієї інспекції.',
    signedBy: 'Підписав',
    signedAt: 'Час підпису',
    checklistItems: 'Пункти чекліста',
    noChecklist: 'Для цієї інспекції немає пунктів чекліста.',
    checklistFallback: 'Пункт чекліста',
    photoRequired: 'Потрібне фото',
    notes: 'Примітки',
    photoReferenceAttached: 'посилання на фото додано',
    photoReferencesAttached: 'посилання на фото додано',
    issuesSection: 'Проблеми',
    noIssues: 'У цій інспекції проблем не виявлено.',
    issueFallback: 'Проблемний пункт',
    severityLow: 'Низький',
    severityMedium: 'Середній',
    severityHigh: 'Високий',
    repairPrefix: 'Ремонт',
    underReview: 'На перевірці',
    inRepair: 'В ремонті',
    fixed: 'Виправлено',
    rejected: 'Відхилено',
    noReviewRequired: 'Перевірка не потрібна',
    draft: 'Чернетка',
    notAnswered: 'Без відповіді',
    popupBlocked: 'Popup заблоковано. Дозвольте popup для перегляду PDF.',
    shareText: 'PDF звіт інспекції',
    reportLoadFailed: 'Не вдалося завантажити звіт.',
    noPhoto: 'Немає фото',
    shareUnavailable: 'Поширення недоступне на цьому пристрої. PDF буде завантажено.',
  },
  es: {
    appName: 'FleetCheck',
    reportTitle: 'Informe de inspeccion',
    reportId: 'ID del informe',
    generated: 'Generado',
    generatedBy: 'Generado por FleetCheck',
    page: 'Pagina',
    vehicleSummary: 'Resumen del vehiculo',
    result: 'Resultado',
    review: 'Revision',
    unit: 'Unidad',
    plate: 'Placa',
    vin: 'VIN',
    driver: 'Conductor',
    inspectionType: 'Inspeccion',
    submitted: 'Enviado',
    preTrip: 'Pre-viaje',
    postTrip: 'Post-viaje',
    passed: 'Aprobado',
    failed: 'Fallado',
    notApplicable: 'N/A',
    issues: 'Problemas',
    photos: 'Fotos',
    driverSignature: 'Firma del conductor',
    noSignature: 'No se adjunto firma a esta inspeccion.',
    signedBy: 'Firmado por',
    signedAt: 'Firmado el',
    checklistItems: 'Items de checklist',
    noChecklist: 'No se registraron items de checklist para esta inspeccion.',
    checklistFallback: 'Item de checklist',
    photoRequired: 'Foto requerida',
    notes: 'Notas',
    photoReferenceAttached: 'referencia de foto adjunta',
    photoReferencesAttached: 'referencias de foto adjuntas',
    issuesSection: 'Problemas',
    noIssues: 'No se generaron problemas para esta inspeccion.',
    issueFallback: 'Problema de inspeccion',
    severityLow: 'Baja',
    severityMedium: 'Media',
    severityHigh: 'Alta',
    repairPrefix: 'Reparacion',
    underReview: 'En revision',
    inRepair: 'En reparacion',
    fixed: 'Solucionado',
    rejected: 'Rechazado',
    noReviewRequired: 'No requiere revision',
    draft: 'Borrador',
    notAnswered: 'Sin respuesta',
    popupBlocked: 'Popup bloqueado. Permite popups para previsualizar el PDF.',
    shareText: 'PDF del informe de inspeccion',
    reportLoadFailed: 'No se pudo cargar el informe.',
    noPhoto: 'Sin foto',
    shareUnavailable: 'Compartir no esta disponible en este dispositivo. Se descargara el PDF.',
  },
  fr: {
    appName: 'FleetCheck',
    reportTitle: 'Rapport d inspection',
    reportId: 'ID du rapport',
    generated: 'Genere',
    generatedBy: 'Genere par FleetCheck',
    page: 'Page',
    vehicleSummary: 'Resume du vehicule',
    result: 'Resultat',
    review: 'Revision',
    unit: 'Unite',
    plate: 'Plaque',
    vin: 'VIN',
    driver: 'Conducteur',
    inspectionType: 'Inspection',
    submitted: 'Soumis',
    preTrip: 'Pre-trajet',
    postTrip: 'Post-trajet',
    passed: 'Reussi',
    failed: 'Echoue',
    notApplicable: 'N/A',
    issues: 'Problemes',
    photos: 'Photos',
    driverSignature: 'Signature du conducteur',
    noSignature: 'Aucune signature n a ete ajoutee a cette inspection.',
    signedBy: 'Signe par',
    signedAt: 'Signe le',
    checklistItems: 'Elements de checklist',
    noChecklist: 'Aucun element de checklist enregistre pour cette inspection.',
    checklistFallback: 'Element de checklist',
    photoRequired: 'Photo requise',
    notes: 'Notes',
    photoReferenceAttached: 'reference photo jointe',
    photoReferencesAttached: 'references photo jointes',
    issuesSection: 'Problemes',
    noIssues: 'Aucun probleme n a ete genere pour cette inspection.',
    issueFallback: 'Probleme d inspection',
    severityLow: 'Faible',
    severityMedium: 'Moyenne',
    severityHigh: 'Elevee',
    repairPrefix: 'Reparation',
    underReview: 'En revision',
    inRepair: 'En reparation',
    fixed: 'Corrige',
    rejected: 'Rejete',
    noReviewRequired: 'Aucune revision requise',
    draft: 'Brouillon',
    notAnswered: 'Sans reponse',
    popupBlocked: 'Popup bloquee. Autorisez les popups pour previsualiser le PDF.',
    shareText: 'PDF du rapport d inspection',
    reportLoadFailed: 'Impossible de charger le rapport.',
    noPhoto: 'Pas de photo',
    shareUnavailable: 'Le partage n est pas disponible sur cet appareil. Le PDF sera telecharge.',
  },
}

function normalizeLanguage(language: string): Language {
  if (language === 'uk' || language === 'es' || language === 'fr') return language
  return 'en'
}

function dictFor(language: string): Dict {
  return DICT[normalizeLanguage(language)]
}

function looksLikeVfs(value: unknown): value is Record<string, string> {
  if (!value || typeof value !== 'object') return false
  const keys = Object.keys(value as Record<string, unknown>)
  if (keys.length === 0) return false
  const sample = (value as Record<string, unknown>)[keys[0]]
  return typeof sample === 'string' && sample.length > 100
}

let pdfMakeCache: any = null
let pdfMakePromise: Promise<any> | null = null

async function getPdfMake(): Promise<any> {
  if (pdfMakeCache && looksLikeVfs(pdfMakeCache.vfs)) return pdfMakeCache
  if (pdfMakePromise) return pdfMakePromise

  pdfMakePromise = (async () => {
    const pdfMakeModule: any = await import('pdfmake/build/pdfmake.js')
    const pdfMake: any = pdfMakeModule?.default || pdfMakeModule

    // vfs_fonts.js IIFE tries `_global.pdfMake.addVirtualFileSystem(vfs)`.
    // Make pdfMake available on window BEFORE importing vfs_fonts.
    if (typeof window !== 'undefined') {
      ;(window as any).pdfMake = pdfMake
    }

    const fontsModule: any = await import('pdfmake/build/vfs_fonts.js')
    const candidates = [
      pdfMake.vfs,
      fontsModule?.default,
      fontsModule?.pdfMake?.vfs,
      fontsModule?.default?.pdfMake?.vfs,
      fontsModule?.vfs,
      fontsModule?.default?.vfs,
      fontsModule,
    ]

    for (const candidate of candidates) {
      if (looksLikeVfs(candidate)) {
        pdfMake.vfs = candidate
        break
      }
    }

    if (!looksLikeVfs(pdfMake.vfs)) {
      console.error('[reportPdf] pdfmake vfs not initialized', {
        pdfMakeKeys: Object.keys(pdfMake || {}),
        fontsKeys: fontsModule && typeof fontsModule === 'object' ? Object.keys(fontsModule) : null,
        defaultKeys:
          fontsModule?.default && typeof fontsModule.default === 'object'
            ? Object.keys(fontsModule.default)
            : null,
      })
      throw new Error('pdfmake fonts (vfs) could not be initialized.')
    }

    pdfMakeCache = pdfMake
    return pdfMake
  })()

  try {
    return await pdfMakePromise
  } catch (error) {
    pdfMakePromise = null
    throw error
  }
}

function relation<T = any>(value: T | T[] | null | undefined): T | null {
  if (!value) return null
  return Array.isArray(value) ? value[0] || null : value
}

function relationArray<T = any>(value: T | T[] | null | undefined): T[] {
  if (!value) return []
  return Array.isArray(value) ? value : [value]
}

function text(value: unknown, fallback = '-'): string {
  if (value === null || value === undefined || value === '') return fallback
  return String(value)
}

function fileSafe(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function vehicleName(vehicle: any): string {
  return `${vehicle?.make || ''} ${vehicle?.model || ''}`.trim() || 'Vehicle'
}

function reportResult(status: string, results: any[]): ReportResult {
  if (status === 'draft') return 'draft'
  return results.some((row) => row.result === 'fail') ? 'fail' : 'pass'
}

function localizedResult(result: string | null | undefined, dict: Dict): string {
  if (result === 'pass') return dict.passed
  if (result === 'fail') return dict.failed
  if (result === 'not_applicable') return dict.notApplicable
  if (result === 'draft') return dict.draft
  return dict.notAnswered
}

function localizedSeverity(severity: string | null | undefined, dict: Dict): string {
  if (severity === 'low') return dict.severityLow
  if (severity === 'high') return dict.severityHigh
  return dict.severityMedium
}

function localizedReviewStatus(issues: any[], dict: Dict): string {
  if (!issues.length) return dict.noReviewRequired
  if (issues.some((issue) => issue.status === 'under-review')) return dict.underReview
  if (issues.some((issue) => issue.status === 'in-repair')) return dict.inRepair
  if (issues.every((issue) => issue.status === 'fixed')) return dict.fixed
  if (issues.every((issue) => issue.status === 'rejected')) return dict.rejected
  return issues.map((issue) => issue.status).filter(Boolean).join(', ') || '-'
}

function inspectionTypeLabel(type: string | null | undefined, dict: Dict): string {
  return type === 'post-trip' ? dict.postTrip : dict.preTrip
}

function isMissingSignatureColumnsError(message?: string | null) {
  const value = String(message || '').toLowerCase()
  return (
    value.includes('signature_data_url') ||
    value.includes('signed_at') ||
    value.includes('signed_by_driver_id')
  )
}

function badgeColor(label: string) {
  const normalized = label.toLowerCase()
  if (/(pass|reussi|aprob|пройд)/.test(normalized)) return { fg: '#166534', bg: '#dcfce7' }
  if (/(fail|rech|echou|не пройд|відх)/.test(normalized)) return { fg: '#991b1b', bg: '#fee2e2' }
  if (/(review|repair|draft|ревіз|перевір|чернет)/.test(normalized)) return { fg: '#92400e', bg: '#fef3c7' }
  return { fg: '#374151', bg: '#f3f4f6' }
}

function badge(textValue: string) {
  const palette = badgeColor(textValue)
  return {
    text: textValue,
    color: palette.fg,
    fillColor: palette.bg,
    bold: true,
    fontSize: 9,
    alignment: 'center' as const,
    margin: [0, 2, 0, 2],
  }
}

function parseStorageSource(source: string): { bucket: string; path: string } | null {
  const trimmed = source.trim()
  if (!trimmed) return null

  const normalized = trimmed.replace(/^\/+/, '')
  const directParts = normalized.split('/').filter(Boolean)

  if (directParts.length >= 2) {
    const [candidateBucket, ...rest] = directParts
    if (candidateBucket && !candidateBucket.includes('.') && !candidateBucket.includes(':')) {
      return {
        bucket: candidateBucket,
        path: rest.join('/'),
      }
    }
  }

  try {
    const url = new URL(trimmed)
    const match = url.pathname.match(/\/storage\/v1\/object\/(?:public|authenticated|sign)\/([^/]+)\/(.+)$/)
    if (match) {
      return {
        bucket: decodeURIComponent(match[1] || ''),
        path: decodeURIComponent(match[2] || ''),
      }
    }
  } catch {
    return null
  }

  return null
}


async function storageSourceToBlob(source: string): Promise<Blob | null> {
  const parsed = parseStorageSource(source)
  if (!parsed?.bucket || !parsed.path) return null

  const { data, error } = await supabase.storage
    .from(parsed.bucket)
    .download(parsed.path)

  if (error || !data) return null
  return data
}

async function imageToJpegDataUrl(image: HTMLImageElement, maxSide: number, quality: number): Promise<string | null> {
  try {
    const scale = Math.min(1, maxSide / Math.max(image.naturalWidth, image.naturalHeight))
    const canvas = document.createElement('canvas')
    canvas.width = Math.max(1, Math.round(image.naturalWidth * scale))
    canvas.height = Math.max(1, Math.round(image.naturalHeight * scale))
    const context = canvas.getContext('2d')
    if (!context) return null

    context.fillStyle = '#ffffff'
    context.fillRect(0, 0, canvas.width, canvas.height)
    context.drawImage(image, 0, 0, canvas.width, canvas.height)
    return canvas.toDataURL('image/jpeg', quality)
  } catch (error) {
    console.warn('[reportPdf] canvas encode failed', error)
    return null
  }
}

function loadHtmlImage(src: string, crossOrigin: boolean): Promise<HTMLImageElement | null> {
  return new Promise((resolve) => {
    const image = new Image()
    if (crossOrigin) image.crossOrigin = 'anonymous'
    image.onload = () => resolve(image)
    image.onerror = () => resolve(null)
    image.src = src
  })
}

async function loadImageDataUrl(url: string | null | undefined, maxSide = 420, quality = 0.84): Promise<string | null> {
  if (!url) return null

  // 1) Inline data URL: re-encode via canvas to guarantee image/jpeg for pdfmake.
  if (url.startsWith('data:')) {
    const image = await loadHtmlImage(url, false)
    if (!image) {
      console.warn('[reportPdf] data URL is not a valid image', url.slice(0, 64))
      return null
    }
    return imageToJpegDataUrl(image, maxSide, quality)
  }

  // 2) Supabase Storage source (URL or bucket/path): download via SDK, encode via canvas.
  const storageBlob = await storageSourceToBlob(url)
  if (storageBlob) {
    const objectUrl = URL.createObjectURL(storageBlob)
    try {
      const image = await loadHtmlImage(objectUrl, false)
      if (image) {
        const encoded = await imageToJpegDataUrl(image, maxSide, quality)
        if (encoded) return encoded
      }
    } finally {
      URL.revokeObjectURL(objectUrl)
    }
  }

  // 3) Remote URL: try with CORS, then without (for same-origin or proxied images).
  for (const crossOrigin of [true, false]) {
    const image = await loadHtmlImage(url, crossOrigin)
    if (!image) continue
    const encoded = await imageToJpegDataUrl(image, maxSide, quality)
    if (encoded) return encoded
  }

  console.warn('[reportPdf] image could not be loaded for PDF', url)
  return null
}

function toBlob(pdfDoc: any): Promise<Blob> {
  return new Promise((resolve, reject) => {
    try {
      pdfDoc.getBlob((blob: Blob) => resolve(blob))
    } catch (error) {
      reject(error)
    }
  })
}

function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 20000)
}

function previewBlob(blob: Blob, previewWindow: Window) {
  const url = URL.createObjectURL(blob)
  previewWindow.document.open()
  previewWindow.document.write(`<!doctype html><html><head><title>PDF Preview</title><style>html,body,iframe{height:100%;width:100%;margin:0;border:0;background:#111;}</style></head><body><iframe src="${url}"></iframe></body></html>`)
  previewWindow.document.close()
  window.setTimeout(() => URL.revokeObjectURL(url), 20000)
}

function previewBlobInCurrentTab(blob: Blob) {
  const url = URL.createObjectURL(blob)
  window.location.assign(url)
  window.setTimeout(() => URL.revokeObjectURL(url), 60000)
}

async function shareBlob(blob: Blob, fileName: string, dict: Dict) {
  const file = new File([blob], fileName, { type: 'application/pdf' })
  const canShareFiles = typeof navigator.canShare === 'function'
    ? navigator.canShare({ files: [file] })
    : true

  if (typeof navigator.share === 'function' && canShareFiles) {
    try {
      await navigator.share({ title: fileName, text: dict.shareText, files: [file] })
      return
    } catch (error: any) {
      if (error?.name === 'AbortError') return
    }
  }

  downloadBlob(blob, fileName)
}

function ensureBlobHasContent(blob: Blob, dict: Dict) {
  if (!blob || blob.size === 0) {
    throw new Error(dict.reportLoadFailed)
  }
}

async function loadInspectionData(inspectionId: string, dict: Dict) {
  let { data, error } = await supabase
    .from('inspections')
    .select(`
      id,
      type,
      status,
      created_at,
      submitted_at,
      signature_data_url,
      signed_at,
      vehicle_id,
      driver_id,
      vehicles (
        unit,
        make,
        model,
        plate,
        vin,
        status,
        photo_url
      ),
      drivers!inspections_driver_id_fkey (
        name,
        email
      ),
      inspection_results (
        id,
        result,
        comment,
        photo_urls,
        inspection_template_items (
          title,
          description,
          category_id,
          inspection_item_categories (
            id,
            name,
            severity
          ),
          is_required,
          requires_photo,
          sort_order
        )
      ),
      issues (
        id,
        title,
        description,
        severity,
        status,
        photo_urls,
        inspection_result_id
      )
    `)
    .eq('id', inspectionId)
    .single()

  if (error && isMissingSignatureColumnsError(error.message)) {
    const retry = await supabase
      .from('inspections')
      .select(`
        id,
        type,
        status,
        created_at,
        submitted_at,
        vehicle_id,
        driver_id,
        vehicles (
          unit,
          make,
          model,
          plate,
          vin,
          status,
          photo_url
        ),
        drivers!inspections_driver_id_fkey (
          name,
          email
        ),
        inspection_results (
          id,
          result,
          comment,
          photo_urls,
          inspection_template_items (
            title,
            description,
            category_id,
            inspection_item_categories (
              id,
              name,
              severity
            ),
            is_required,
            requires_photo,
            sort_order
          )
        ),
        issues (
          id,
          title,
          description,
          severity,
          status,
          photo_urls,
          inspection_result_id
        )
      `)
      .eq('id', inspectionId)
      .single()

    data = retry.data as any
    error = retry.error
  }

  if (error || !data) {
    throw new Error(error?.message || dict.reportLoadFailed)
  }

  const inspection = data as any
  const localFallbackSignature = readSignatureFallback(inspectionId)
  const fallbackSignature = localFallbackSignature || (await readSignatureFallbackFromDb(inspectionId))

  inspection.signature_data_url = inspection.signature_data_url || fallbackSignature?.dataUrl || null
  inspection.signed_at = inspection.signed_at || fallbackSignature?.signedAt || null

  return inspection
}

function metricCard(label: string, value: number, color: string) {
  return {
    table: {
      widths: ['*'],
      body: [
        [{ fillColor: color, text: '', border: [false, false, false, false], margin: [0, 0, 0, 0], minHeight: 3 }],
        [{
          margin: [8, 8, 8, 10],
          stack: [
            { text: String(value), fontSize: 20, bold: true, color, margin: [0, 0, 0, 2] },
            { text: label.toUpperCase(), fontSize: 7, color: '#6b7280', bold: true, characterSpacing: 0.4 },
          ],
          border: [true, false, true, true],
        }],
      ],
    },
    layout: {
      hLineColor: () => '#e5e7eb',
      vLineColor: () => '#e5e7eb',
      hLineWidth: (i: number) => (i === 0 ? 0 : 0.5),
      vLineWidth: () => 0.5,
      paddingLeft: () => 0,
      paddingRight: () => 0,
      paddingTop: () => 0,
      paddingBottom: () => 0,
    },
  }
}

function sectionTitle(textValue: string) {
  return {
    table: {
      widths: ['*'],
      body: [[{
        text: textValue.toUpperCase(),
        fontSize: 10,
        bold: true,
        color: '#1f2937',
        characterSpacing: 0.6,
        margin: [0, 0, 0, 4],
        border: [false, false, false, true],
      }]],
    },
    layout: {
      hLineColor: () => '#2563eb',
      hLineWidth: (i: number, node: any) => (i === node.table.body.length ? 1.5 : 0),
      paddingLeft: () => 0,
      paddingRight: () => 0,
      paddingTop: () => 0,
      paddingBottom: () => 0,
    },
    margin: [0, 14, 0, 8],
  }
}

async function buildInspectionReportPdf(inspectionId: string, language: string) {
  const pdfMake = await getPdfMake()
  const dict = dictFor(language)
  const inspection = await loadInspectionData(inspectionId, dict)

  const vehicle = relation(inspection.vehicles)
  const driver = relation(inspection.drivers)
  const results = relationArray(inspection.inspection_results).sort(
    (a: any, b: any) => (a.inspection_template_items?.sort_order || 0) - (b.inspection_template_items?.sort_order || 0)
  )
  const issues = relationArray(inspection.issues)

  const photoEntries: Array<{ url: string; title: string; result: string | null }> = []
  results.forEach((row: any) => {
    const urls = normalizePhotoUrls(row.photo_urls)
    const itemTitle = row.inspection_template_items?.title || dict.checklistFallback
    urls.forEach((url: string) => {
      photoEntries.push({ url, title: itemTitle, result: row.result })
    })
  })
  issues.forEach((issue: any) => {
    const urls = normalizePhotoUrls(issue.photo_urls)
    urls.forEach((url: string) => {
      photoEntries.push({ url, title: text(issue.title, dict.issueFallback), result: null })
    })
  })

  const photos = photoEntries.map((entry) => entry.url)

  const { data: repairs } = issues.length
    ? await supabase
        .from('repairs')
        .select('id, issue_id, status, notes, description, priority')
        .in('issue_id', issues.map((issue: any) => issue.id))
    : { data: [] as any[] }

  const repairsByIssueId = new Map(
    relationArray(repairs).map((repair: any) => [repair.issue_id, repair])
  )

  const [vehiclePhoto, signatureImage, ...photoImages] = await Promise.all([
    loadImageDataUrl(resolvePhotoUrl(vehicle?.photo_url), 320, 0.86),
    loadImageDataUrl(resolvePhotoUrl(inspection.signature_data_url), 900, 0.95),
    ...photos.slice(0, 12).map((url: string) => loadImageDataUrl(url, 520, 0.85)),
  ])

  const generatedAt = formatDateTime(new Date().toISOString(), language as any, '-')
  const submittedAt = formatDateTime(inspection.submitted_at || inspection.created_at, language as any, '-')
  const signedAt = formatDateTime(inspection.signed_at || inspection.submitted_at || inspection.created_at, language as any, '-')

  const resultValue = reportResult(inspection.status, results)
  const resultLabel = localizedResult(resultValue, dict)
  const reviewLabel = localizedReviewStatus(issues, dict)

  const passedCount = results.filter((row: any) => row.result === 'pass').length
  const failedCount = results.filter((row: any) => row.result === 'fail').length
  const naCount = results.filter((row: any) => row.result === 'not_applicable').length

  const content: any[] = []

  content.push({
    table: {
      widths: ['*'],
      body: [[{
        fillColor: '#1d4ed8',
        margin: [16, 14, 16, 14],
        stack: [
          {
            columns: [
              {
                width: '*',
                stack: [
                  { text: dict.appName.toUpperCase(), fontSize: 9, bold: true, color: '#bfdbfe', characterSpacing: 1.2 },
                  { text: dict.reportTitle, fontSize: 22, bold: true, color: '#ffffff', margin: [0, 4, 0, 0] },
                ],
              },
              {
                width: 'auto',
                stack: [
                  { text: dict.generated.toUpperCase(), fontSize: 7, bold: true, color: '#bfdbfe', alignment: 'right', characterSpacing: 0.8 },
                  { text: generatedAt, fontSize: 10, color: '#ffffff', alignment: 'right', margin: [0, 2, 0, 0] },
                ],
              },
            ],
          },
          {
            text: `${dict.reportId}: ${inspection.id}`,
            fontSize: 8,
            color: '#dbeafe',
            margin: [0, 8, 0, 0],
          },
        ],
      }]],
    },
    layout: 'noBorders',
    margin: [0, 0, 0, 14],
  })

  content.push(sectionTitle(dict.vehicleSummary))

  content.push({
    table: {
      widths: [110, '*', 130],
      body: [[
        {
          fillColor: '#f9fafb',
          margin: [8, 8, 8, 8],
          stack: vehiclePhoto
            ? [{ image: vehiclePhoto, fit: [94, 74], alignment: 'center' }]
            : [{ text: dict.noPhoto, color: '#9ca3af', alignment: 'center', fontSize: 8, margin: [0, 30, 0, 0] }],
        },
        {
          margin: [10, 10, 10, 10],
          stack: [
            { text: vehicleName(vehicle), fontSize: 15, bold: true, color: '#111827' },
            {
              columns: [
                { text: `${dict.unit}: ${text(vehicle?.unit)}`, fontSize: 9, color: '#374151', width: 'auto' },
                { text: `${dict.plate}: ${text(vehicle?.plate)}`, fontSize: 9, color: '#374151', width: 'auto', margin: [10, 0, 0, 0] },
              ],
              margin: [0, 5, 0, 2],
            },
            { text: `${dict.vin}: ${text(vehicle?.vin)}`, fontSize: 9, color: '#6b7280' },
            { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 240, y2: 0, lineWidth: 0.5, lineColor: '#e5e7eb' }], margin: [0, 6, 0, 6] },
            { text: `${dict.inspectionType}: ${inspectionTypeLabel(inspection.type, dict)}`, fontSize: 9, color: '#374151' },
            { text: `${dict.submitted}: ${submittedAt}`, fontSize: 9, color: '#374151', margin: [0, 2, 0, 0] },
            { text: `${dict.driver}: ${text(driver?.name || driver?.email, '-')}`, fontSize: 9, color: '#374151', margin: [0, 2, 0, 0] },
          ],
        },
        {
          margin: [10, 12, 10, 10],
          stack: [
            { text: dict.result.toUpperCase(), fontSize: 7, bold: true, color: '#6b7280', characterSpacing: 0.6, margin: [0, 0, 0, 4] },
            badge(resultLabel),
            { text: dict.review.toUpperCase(), fontSize: 7, bold: true, color: '#6b7280', characterSpacing: 0.6, margin: [0, 10, 0, 4] },
            badge(reviewLabel),
          ],
        },
      ]],
    },
    layout: {
      hLineColor: () => '#e5e7eb',
      vLineColor: () => '#e5e7eb',
      hLineWidth: () => 0.5,
      vLineWidth: () => 0.5,
    },
    margin: [0, 0, 0, 12],
  })

  content.push({
    columns: [
      metricCard(dict.passed, passedCount, '#16a34a'),
      metricCard(dict.failed, failedCount, '#dc2626'),
      metricCard(dict.notApplicable, naCount, '#6b7280'),
      metricCard(dict.issues, issues.length, '#d97706'),
      metricCard(dict.photos, photos.length, '#2563eb'),
    ],
    columnGap: 8,
    margin: [0, 0, 0, 8],
  })

  content.push(sectionTitle(dict.driverSignature))

  if (!signatureImage) {
    content.push({
      table: {
        widths: ['*'],
        body: [[{ text: dict.noSignature, color: '#6b7280', margin: [10, 12, 10, 12] }]],
      },
      layout: {
        fillColor: () => '#f9fafb',
        hLineColor: () => '#d1d5db',
        vLineColor: () => '#d1d5db',
      },
      margin: [0, 0, 0, 4],
    })
  } else {
    content.push({
      table: {
        widths: [240, '*'],
        body: [[
          { image: signatureImage, fit: [220, 70], margin: [10, 10, 10, 10] },
          {
            stack: [
              { text: `${dict.signedBy}: ${text(driver?.name || driver?.email, '-')}`, margin: [0, 22, 0, 4], color: '#374151' },
              { text: `${dict.signedAt}: ${signedAt}`, fontSize: 9, color: '#6b7280' },
            ],
            margin: [0, 10, 10, 10],
          },
        ]],
      },
      layout: {
        fillColor: () => '#f9fafb',
        hLineColor: () => '#d1d5db',
        vLineColor: () => '#d1d5db',
      },
      margin: [0, 0, 0, 4],
    })
  }

  content.push(sectionTitle(dict.checklistItems))

  if (!results.length) {
    content.push({ text: dict.noChecklist, color: '#6b7280', margin: [0, 0, 0, 8] })
  } else {
    results.forEach((row: any, index: number) => {
      const item = row.inspection_template_items || {}
      const category = item.inspection_item_categories?.name || dict.checklistFallback
      const photoCount = row.photo_urls?.length || 0
      const accent = row.result === 'pass' ? '#16a34a' : row.result === 'fail' ? '#dc2626' : row.result === 'not_applicable' ? '#9ca3af' : '#d97706'

      const stack: any[] = [
        {
          columns: [
            { text: `${index + 1}.`, width: 18, fontSize: 11, bold: true, color: '#6b7280' },
            { text: text(item.title, dict.checklistFallback), fontSize: 11, bold: true, color: '#111827' },
            { width: 'auto', ...badge(localizedResult(row.result, dict)) },
          ],
          columnGap: 4,
        },
        { text: category, fontSize: 8, color: '#6b7280', margin: [18, 3, 0, 0] },
      ]

      const meta: any[] = []
      if (item.requires_photo) meta.push({ text: dict.photoRequired, fontSize: 8, color: '#d97706', bold: true })
      if (photoCount) meta.push({ text: photoCount === 1 ? `1 ${dict.photoReferenceAttached}` : `${photoCount} ${dict.photoReferencesAttached}`, fontSize: 8, color: '#2563eb', bold: true })

      if (meta.length) {
        stack.push({
          columns: meta.map((m) => ({ ...m, width: 'auto' })),
          columnGap: 10,
          margin: [18, 3, 0, 0],
        })
      }

      if (row.comment) {
        stack.push({ text: `${dict.notes}: ${row.comment}`, fontSize: 9, color: '#374151', margin: [18, 4, 0, 0], italics: true })
      }

      content.push({
        table: {
          widths: [3, '*'],
          body: [[
            { fillColor: accent, text: '', border: [false, false, false, false] },
            { stack, margin: [10, 8, 10, 8], border: [false, false, false, false] },
          ]],
        },
        layout: {
          paddingLeft: () => 0,
          paddingRight: () => 0,
          paddingTop: () => 0,
          paddingBottom: () => 0,
          hLineColor: () => '#e5e7eb',
          vLineColor: () => '#e5e7eb',
          hLineWidth: (i: number, node: any) => (i === 0 || i === node.table.body.length ? 0.5 : 0),
          vLineWidth: (i: number, node: any) => (i === node.table.widths.length ? 0.5 : 0),
        },
        margin: [0, 0, 0, 5],
      })
    })
  }

  content.push(sectionTitle(dict.issuesSection))

  if (!issues.length) {
    content.push({
      table: {
        widths: ['*'],
        body: [[{ text: dict.noIssues, color: '#166534', bold: true, margin: [10, 10, 10, 10] }]],
      },
      layout: {
        fillColor: () => '#dcfce7',
        hLineColor: () => '#d1d5db',
        vLineColor: () => '#d1d5db',
      },
      margin: [0, 0, 0, 6],
    })
  } else {
    issues.forEach((issue: any, index: number) => {
      const repair = repairsByIssueId.get(issue.id)
      const notes = [issue.description, repair?.notes && repair.notes !== issue.description ? repair.notes : '']
        .filter(Boolean)
        .join(' - ')

      content.push({
        table: {
          widths: ['*'],
          body: [[{
            margin: [12, 10, 12, 8],
            stack: [
              { text: `${index + 1}. ${text(issue.title, dict.issueFallback)}`, fontSize: 11, bold: true, color: '#111827' },
              {
                columns: [
                  { width: 'auto', ...badge(localizedSeverity(issue.severity, dict)) },
                  { width: 'auto', ...badge(localizedReviewStatus([issue], dict)) },
                  ...(repair?.status ? [{ width: 'auto', ...badge(`${dict.repairPrefix}: ${repair.status}`) }] : []),
                ],
                columnGap: 6,
                margin: [0, 6, 0, 2],
              },
              ...(notes ? [{ text: `${dict.notes}: ${notes}`, fontSize: 9, color: '#374151', margin: [0, 3, 0, 0] }] : []),
            ],
          }]],
        },
        layout: {
          fillColor: () => '#fffbeb',
          hLineColor: () => '#d1d5db',
          vLineColor: () => '#d1d5db',
        },
        margin: [0, 0, 0, 6],
      })
    })
  }

  const photoCards = photoImages
    .map((image, idx) => ({ image, entry: photoEntries[idx] }))
    .filter((p) => Boolean(p.image))

  if (photoCards.length) {
    content.push({ ...sectionTitle(dict.photos), pageBreak: 'before' })

    for (let index = 0; index < photoCards.length; index += 2) {
      const slice = photoCards.slice(index, index + 2)
      const cells = slice.map(({ image, entry }) => ({
        stack: [
          { image, fit: [240, 180], alignment: 'center' },
          {
            stack: [
              { text: entry?.title || '', fontSize: 9, bold: true, color: '#111827', margin: [0, 6, 0, 2] },
              ...(entry?.result ? [{ ...badge(localizedResult(entry.result, dict)), alignment: 'left' as const }] : []),
            ],
            margin: [4, 0, 4, 0],
          },
        ],
        margin: [0, 0, 0, 14],
      }))
      while (cells.length < 2) cells.push({ stack: [], margin: [0, 0, 0, 0] } as any)
      content.push({ columns: cells, columnGap: 12 })
    }
  }

  const docDefinition: any = {
    pageSize: 'A4',
    pageMargins: [32, 30, 32, 36],
    defaultStyle: {
      font: 'Roboto',
      fontSize: 10,
      color: '#111827',
    },
    footer: (currentPage: number, pageCount: number) => ({
      columns: [
        { text: `${dict.generatedBy} - ${generatedAt}`, color: '#6b7280', margin: [32, 0, 0, 0], fontSize: 8 },
        { text: `${dict.page} ${currentPage} / ${pageCount}`, color: '#6b7280', alignment: 'right', margin: [0, 0, 32, 0], fontSize: 8 },
      ],
    }),
    content,
  }

  const pdfDoc = pdfMake.createPdf(docDefinition)
  const blob = await toBlob(pdfDoc)
  ensureBlobHasContent(blob, dict)

  const dateValue = inspection.submitted_at || inspection.created_at
  const datePart = dateValue ? String(dateValue).slice(0, 10) : 'report'
  const unit = fileSafe(text(vehicle?.unit, 'vehicle'))
  const fileName = unit
    ? `vehicle-${unit}-report-${datePart}.pdf`
    : `report-${inspection.id}.pdf`

  return { blob, fileName, dict }
}

export async function downloadInspectionReportPdf(inspectionId: string, language: string) {
  try {
    const { blob, fileName } = await buildInspectionReportPdf(inspectionId, language)
    downloadBlob(blob, fileName)
  } catch (error) {
    console.error('[reportPdf] downloadInspectionReportPdf failed', error)
    throw error
  }
}

export async function previewInspectionReportPdf(
  inspectionId: string,
  language: string,
  previewWindow?: Window | null
) {
  try {
    const { blob } = await buildInspectionReportPdf(inspectionId, language)

    if (previewWindow && !previewWindow.closed) {
      previewBlob(blob, previewWindow)
      return
    }

    const url = URL.createObjectURL(blob)
    const openedWindow = window.open(url, '_blank', 'noopener,noreferrer')

    if (openedWindow) {
      window.setTimeout(() => URL.revokeObjectURL(url), 20000)
      return
    }

    // Popup blockers may reject new tabs; open preview in the same tab instead.
    previewBlobInCurrentTab(blob)
  } catch (error) {
    console.error('[reportPdf] previewInspectionReportPdf failed', error)
    throw error
  }
}

export async function shareInspectionReportPdf(inspectionId: string, language: string) {
  try {
    const { blob, fileName, dict } = await buildInspectionReportPdf(inspectionId, language)
    await shareBlob(blob, fileName, dict)
  } catch (error) {
    console.error('[reportPdf] shareInspectionReportPdf failed', error)
    throw error
  }
}
