import pdfMake from 'pdfmake/build/pdfmake'
import pdfFonts from 'pdfmake/build/vfs_fonts'

import { formatDateTime } from '@/lib/dateFormat'
import { normalizePhotoUrls, resolvePhotoUrl } from '@/lib/photoUrls'
import { readSignatureFallback, readSignatureFallbackFromDb } from '@/lib/signatureFallback'
import { supabase } from '@/lib/supabase'

type Language = 'en' | 'uk' | 'es' | 'fr'
type ReportResult = 'pass' | 'fail' | 'draft'

type Dict = {
  appName: string
  reportTitle: string
  reportId: string
  generated: string
  generatedBy: string
  page: string
  vehicleSummary: string
  result: string
  review: string
  unit: string
  plate: string
  vin: string
  driver: string
  inspectionType: string
  submitted: string
  preTrip: string
  postTrip: string
  passed: string
  failed: string
  notApplicable: string
  issues: string
  photos: string
  driverSignature: string
  noSignature: string
  signedBy: string
  signedAt: string
  checklistItems: string
  noChecklist: string
  checklistFallback: string
  photoRequired: string
  notes: string
  photoReferenceAttached: string
  photoReferencesAttached: string
  issuesSection: string
  noIssues: string
  issueFallback: string
  severityLow: string
  severityMedium: string
  severityHigh: string
  repairPrefix: string
  underReview: string
  inRepair: string
  fixed: string
  rejected: string
  noReviewRequired: string
  draft: string
  notAnswered: string
  popupBlocked: string
  reportLoadFailed: string
  shareText: string
  noPhoto: string
  shareUnavailable: string
}

const DICT: Record<Language, Dict> = {
  en: {
    appName: 'FleetCheck',
    reportTitle: 'Inspection Report',
    reportId: 'Report ID',
    generated: 'Generated',
    generatedBy: 'Generated by FleetCheck',
    page: 'Page',
    vehicleSummary: 'Vehicle Summary',
    result: 'Result',
    review: 'Review',
    unit: 'Unit',
    plate: 'Plate',
    vin: 'VIN',
    driver: 'Driver',
    inspectionType: 'Inspection type',
    submitted: 'Submitted',
    preTrip: 'Pre-trip',
    postTrip: 'Post-trip',
    passed: 'Passed',
    failed: 'Failed',
    notApplicable: 'N/A',
    issues: 'Issues',
    photos: 'Photos',
    driverSignature: 'Driver Signature',
    noSignature: 'No signature was attached to this inspection.',
    signedBy: 'Signed by',
    signedAt: 'Signed at',
    checklistItems: 'Checklist Items',
    noChecklist: 'No checklist items were recorded for this inspection.',
    checklistFallback: 'Checklist item',
    photoRequired: 'Photo required',
    notes: 'Notes',
    photoReferenceAttached: 'photo reference attached',
    photoReferencesAttached: 'photo references attached',
    issuesSection: 'Issues',
    noIssues: 'No issues were generated for this inspection.',
    issueFallback: 'Inspection issue',
    severityLow: 'Low',
    severityMedium: 'Medium',
    severityHigh: 'High',
    repairPrefix: 'Repair',
    underReview: 'Under Review',
    inRepair: 'In Repair',
    fixed: 'Fixed',
    rejected: 'Rejected',
    noReviewRequired: 'No review required',
    draft: 'Draft',
    notAnswered: 'Not answered',
    popupBlocked: 'Popup blocked. Allow popups to preview the PDF.',
    shareText: 'Inspection report PDF',
    reportLoadFailed: 'Report could not be loaded.',
    noPhoto: 'No photo',
    shareUnavailable: 'Share is not available on this device. The PDF will be downloaded instead.',
  },
  uk: {
    appName: 'FleetCheck',
    reportTitle: 'Звіт інспекції',
    reportId: 'ID звіту',
    generated: 'Згенеровано',
    generatedBy: 'Згенеровано FleetCheck',
    page: 'Сторінка',
    vehicleSummary: 'Інформація про транспорт',
    result: 'Результат',
    review: 'Перевірка',
    unit: 'Юніт',
    plate: 'Номер',
    vin: 'VIN',
    driver: 'Водій',
    inspectionType: 'Тип інспекції',
    submitted: 'Надіслано',
    preTrip: 'Перед рейсом',
    postTrip: 'Після рейсу',
    passed: 'Пройдено',
    failed: 'Не пройдено',
    notApplicable: 'Н/З',
    issues: 'Проблеми',
    photos: 'Фото',
    driverSignature: 'Підпис водія',
    noSignature: 'Підпис не було додано до цієї інспекції.',
    signedBy: 'Підписав',
    signedAt: 'Час підпису',
    checklistItems: 'Пункти чекліста',
    noChecklist: 'Для цієї інспекції немає пунктів чекліста.',
    checklistFallback: 'Пункт чекліста',
    photoRequired: 'Потрібне фото',
    notes: 'Примітки',
    photoReferenceAttached: 'посилання на фото додано',
    photoReferencesAttached: 'посилання на фото додано',
    issuesSection: 'Проблеми',
    noIssues: 'У цій інспекції проблем не виявлено.',
    issueFallback: 'Проблемний пункт',
    severityLow: 'Низький',
    severityMedium: 'Середній',
    severityHigh: 'Високий',
    repairPrefix: 'Ремонт',
    underReview: 'На перевірці',
    inRepair: 'В ремонті',
    fixed: 'Виправлено',
    rejected: 'Відхилено',
    noReviewRequired: 'Перевірка не потрібна',
    draft: 'Чернетка',
    notAnswered: 'Без відповіді',
    popupBlocked: 'Popup заблоковано. Дозвольте popup для перегляду PDF.',
    shareText: 'PDF звіт інспекції',
    reportLoadFailed: 'Не вдалося завантажити звіт.',
    noPhoto: 'Немає фото',
    shareUnavailable: 'Поширення недоступне на цьому пристрої. PDF буде завантажено.',
  },
  es: {
    appName: 'FleetCheck',
    reportTitle: 'Informe de inspeccion',
    reportId: 'ID del informe',
    generated: 'Generado',
    generatedBy: 'Generado por FleetCheck',
    page: 'Pagina',
    vehicleSummary: 'Resumen del vehiculo',
    result: 'Resultado',
    review: 'Revision',
    unit: 'Unidad',
    plate: 'Placa',
    vin: 'VIN',
    driver: 'Conductor',
    inspectionType: 'Inspeccion',
    submitted: 'Enviado',
    preTrip: 'Pre-viaje',
    postTrip: 'Post-viaje',
    passed: 'Aprobado',
    failed: 'Fallado',
    notApplicable: 'N/A',
    issues: 'Problemas',
    photos: 'Fotos',
    driverSignature: 'Firma del conductor',
    noSignature: 'No se adjunto firma a esta inspeccion.',
    signedBy: 'Firmado por',
    signedAt: 'Firmado el',
    checklistItems: 'Items de checklist',
    noChecklist: 'No se registraron items de checklist para esta inspeccion.',
    checklistFallback: 'Item de checklist',
    photoRequired: 'Foto requerida',
    notes: 'Notas',
    photoReferenceAttached: 'referencia de foto adjunta',
    photoReferencesAttached: 'referencias de foto adjuntas',
    issuesSection: 'Problemas',
    noIssues: 'No se generaron problemas para esta inspeccion.',
    issueFallback: 'Problema de inspeccion',
    severityLow: 'Baja',
    severityMedium: 'Media',
    severityHigh: 'Alta',
    repairPrefix: 'Reparacion',
    underReview: 'En revision',
    inRepair: 'En reparacion',
    fixed: 'Solucionado',
    rejected: 'Rechazado',
    noReviewRequired: 'No requiere revision',
    draft: 'Borrador',
    notAnswered: 'Sin respuesta',
    popupBlocked: 'Popup bloqueado. Permite popups para previsualizar el PDF.',
    shareText: 'PDF del informe de inspeccion',
    reportLoadFailed: 'No se pudo cargar el informe.',
    noPhoto: 'Sin foto',
    shareUnavailable: 'Compartir no esta disponible en este dispositivo. Se descargara el PDF.',
  },
  fr: {
    appName: 'FleetCheck',
    reportTitle: 'Rapport d inspection',
    reportId: 'ID du rapport',
    generated: 'Genere',
    generatedBy: 'Genere par FleetCheck',
    page: 'Page',
    vehicleSummary: 'Resume du vehicule',
    result: 'Resultat',
    review: 'Revision',
    unit: 'Unite',
    plate: 'Plaque',
    vin: 'VIN',
    driver: 'Conducteur',
    inspectionType: 'Inspection',
    submitted: 'Soumis',
    preTrip: 'Pre-trajet',
    postTrip: 'Post-trajet',
    passed: 'Reussi',
    failed: 'Echoue',
    notApplicable: 'N/A',
    issues: 'Problemes',
    photos: 'Photos',
    driverSignature: 'Signature du conducteur',
    noSignature: 'Aucune signature n a ete ajoutee a cette inspection.',
    signedBy: 'Signe par',
    signedAt: 'Signe le',
    checklistItems: 'Elements de checklist',
    noChecklist: 'Aucun element de checklist enregistre pour cette inspection.',
    checklistFallback: 'Element de checklist',
    photoRequired: 'Photo requise',
    notes: 'Notes',
    photoReferenceAttached: 'reference photo jointe',
    photoReferencesAttached: 'references photo jointes',
    issuesSection: 'Problemes',
    noIssues: 'Aucun probleme n a ete genere pour cette inspection.',
    issueFallback: 'Probleme d inspection',
    severityLow: 'Faible',
    severityMedium: 'Moyenne',
    severityHigh: 'Elevee',
    repairPrefix: 'Reparation',
    underReview: 'En revision',
    inRepair: 'En reparation',
    fixed: 'Corrige',
    rejected: 'Rejete',
    noReviewRequired: 'Aucune revision requise',
    draft: 'Brouillon',
    notAnswered: 'Sans reponse',
    popupBlocked: 'Popup bloquee. Autorisez les popups pour previsualiser le PDF.',
    shareText: 'PDF du rapport d inspection',
    reportLoadFailed: 'Impossible de charger le rapport.',
    noPhoto: 'Pas de photo',
    shareUnavailable: 'Le partage n est pas disponible sur cet appareil. Le PDF sera telecharge.',
  },
}

function normalizeLanguage(language: string): Language {
  if (language === 'uk' || language === 'es' || language === 'fr') return language
  return 'en'
}

function dictFor(language: string): Dict {
  return DICT[normalizeLanguage(language)]
}

function ensurePdfFonts() {
  const make = pdfMake as any
  const fonts = pdfFonts as any

  if (!make.vfs) {
    make.vfs = fonts?.pdfMake?.vfs || fonts?.vfs || fonts?.default?.pdfMake?.vfs || {}
  }
}

function relation<T = any>(value: T | T[] | null | undefined): T | null {
  if (!value) return null
  return Array.isArray(value) ? value[0] || null : value
}

function relationArray<T = any>(value: T | T[] | null | undefined): T[] {
  if (!value) return []
  return Array.isArray(value) ? value : [value]
}

function text(value: unknown, fallback = '-'): string {
  if (value === null || value === undefined || value === '') return fallback
  return String(value)
}

function fileSafe(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function vehicleName(vehicle: any): string {
  return `${vehicle?.make || ''} ${vehicle?.model || ''}`.trim() || 'Vehicle'
}

function reportResult(status: string, results: any[]): ReportResult {
  if (status === 'draft') return 'draft'
  return results.some((row) => row.result === 'fail') ? 'fail' : 'pass'
}

function localizedResult(result: string | null | undefined, dict: Dict): string {
  if (result === 'pass') return dict.passed
  if (result === 'fail') return dict.failed
  if (result === 'not_applicable') return dict.notApplicable
  if (result === 'draft') return dict.draft
  return dict.notAnswered
}

function localizedSeverity(severity: string | null | undefined, dict: Dict): string {
  if (severity === 'low') return dict.severityLow
  if (severity === 'high') return dict.severityHigh
  return dict.severityMedium
}

function localizedReviewStatus(issues: any[], dict: Dict): string {
  if (!issues.length) return dict.noReviewRequired
  if (issues.some((issue) => issue.status === 'under-review')) return dict.underReview
  if (issues.some((issue) => issue.status === 'in-repair')) return dict.inRepair
  if (issues.every((issue) => issue.status === 'fixed')) return dict.fixed
  if (issues.every((issue) => issue.status === 'rejected')) return dict.rejected
  return issues.map((issue) => issue.status).filter(Boolean).join(', ') || '-'
}

function inspectionTypeLabel(type: string | null | undefined, dict: Dict): string {
  return type === 'post-trip' ? dict.postTrip : dict.preTrip
}

function isMissingSignatureColumnsError(message?: string | null) {
  const value = String(message || '').toLowerCase()
  return (
    value.includes('signature_data_url') ||
    value.includes('signed_at') ||
    value.includes('signed_by_driver_id')
  )
}

function badgeColor(label: string) {
  const normalized = label.toLowerCase()
  if (/(pass|reussi|aprob|пройд)/.test(normalized)) return { fg: '#166534', bg: '#dcfce7' }
  if (/(fail|rech|echou|не пройд|відх)/.test(normalized)) return { fg: '#991b1b', bg: '#fee2e2' }
  if (/(review|repair|draft|ревіз|перевір|чернет)/.test(normalized)) return { fg: '#92400e', bg: '#fef3c7' }
  return { fg: '#374151', bg: '#f3f4f6' }
}

function badge(textValue: string) {
  const palette = badgeColor(textValue)
  return {
    text: textValue,
    color: palette.fg,
    fillColor: palette.bg,
    bold: true,
    fontSize: 9,
    alignment: 'center' as const,
    margin: [0, 2, 0, 2],
  }
}

async function loadImageDataUrl(url: string | null | undefined, maxSide = 420, quality = 0.84): Promise<string | null> {
  if (!url) return null
  if (url.startsWith('data:image/')) return url

  return new Promise((resolve) => {
    const image = new Image()
    image.crossOrigin = 'anonymous'
    image.onload = () => {
      try {
        const scale = Math.min(1, maxSide / Math.max(image.naturalWidth, image.naturalHeight))
        const canvas = document.createElement('canvas')
        canvas.width = Math.max(1, Math.round(image.naturalWidth * scale))
        canvas.height = Math.max(1, Math.round(image.naturalHeight * scale))
        const context = canvas.getContext('2d')

        if (!context) {
          resolve(null)
          return
        }

        context.fillStyle = '#ffffff'
        context.fillRect(0, 0, canvas.width, canvas.height)
        context.drawImage(image, 0, 0, canvas.width, canvas.height)
        resolve(canvas.toDataURL('image/jpeg', quality))
      } catch {
        resolve(null)
      }
    }
    image.onerror = () => resolve(null)
    image.src = url
  })
}

function toBlob(pdfDoc: any): Promise<Blob> {
  return new Promise((resolve, reject) => {
    try {
      pdfDoc.getBlob((blob: Blob) => resolve(blob))
    } catch (error) {
      reject(error)
    }
  })
}

function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 20000)
}

function previewBlob(blob: Blob, previewWindow: Window) {
  const url = URL.createObjectURL(blob)
  previewWindow.document.open()
  previewWindow.document.write(`<!doctype html><html><head><title>PDF Preview</title><style>html,body,iframe{height:100%;width:100%;margin:0;border:0;background:#111;}</style></head><body><iframe src="${url}"></iframe></body></html>`)
  previewWindow.document.close()
  window.setTimeout(() => URL.revokeObjectURL(url), 20000)
}

async function shareBlob(blob: Blob, fileName: string, dict: Dict) {
  const file = new File([blob], fileName, { type: 'application/pdf' })
  const canShareFiles = typeof navigator.canShare === 'function'
    ? navigator.canShare({ files: [file] })
    : true

  if (typeof navigator.share === 'function' && canShareFiles) {
    try {
      await navigator.share({ title: fileName, text: dict.shareText, files: [file] })
      return
    } catch (error: any) {
      if (error?.name === 'AbortError') return
    }
  }

  downloadBlob(blob, fileName)
}

function ensureBlobHasContent(blob: Blob, dict: Dict) {
  if (!blob || blob.size === 0) {
    throw new Error(dict.reportLoadFailed)
  }
}

async function loadInspectionData(inspectionId: string, dict: Dict) {
  let { data, error } = await supabase
    .from('inspections')
    .select(`
      id,
      type,
      status,
      created_at,
      submitted_at,
      signature_data_url,
      signed_at,
      vehicle_id,
      driver_id,
      vehicles (
        unit,
        make,
        model,
        plate,
        vin,
        status,
        photo_url
      ),
      drivers!inspections_driver_id_fkey (
        name,
        email
      ),
      inspection_results (
        id,
        result,
        comment,
        photo_urls,
        inspection_template_items (
          title,
          description,
          category_id,
          inspection_item_categories (
            id,
            name,
            severity
          ),
          is_required,
          requires_photo,
          sort_order
        )
      ),
      issues (
        id,
        title,
        description,
        severity,
        status,
        photo_urls,
        inspection_result_id
      )
    `)
    .eq('id', inspectionId)
    .single()

  if (error && isMissingSignatureColumnsError(error.message)) {
    const retry = await supabase
      .from('inspections')
      .select(`
        id,
        type,
        status,
        created_at,
        submitted_at,
        vehicle_id,
        driver_id,
        vehicles (
          unit,
          make,
          model,
          plate,
          vin,
          status,
          photo_url
        ),
        drivers!inspections_driver_id_fkey (
          name,
          email
        ),
        inspection_results (
          id,
          result,
          comment,
          photo_urls,
          inspection_template_items (
            title,
            description,
            category_id,
            inspection_item_categories (
              id,
              name,
              severity
            ),
            is_required,
            requires_photo,
            sort_order
          )
        ),
        issues (
          id,
          title,
          description,
          severity,
          status,
          photo_urls,
          inspection_result_id
        )
      `)
      .eq('id', inspectionId)
      .single()

    data = retry.data as any
    error = retry.error
  }

  if (error || !data) {
    throw new Error(error?.message || dict.reportLoadFailed)
  }

  const inspection = data as any
  const localFallbackSignature = readSignatureFallback(inspectionId)
  const fallbackSignature = localFallbackSignature || (await readSignatureFallbackFromDb(inspectionId))

  inspection.signature_data_url = inspection.signature_data_url || fallbackSignature?.dataUrl || null
  inspection.signed_at = inspection.signed_at || fallbackSignature?.signedAt || null

  return inspection
}

function metricCard(label: string, value: number, color: string) {
  return {
    table: {
      widths: ['*'],
      body: [[{
        margin: [8, 8, 8, 8],
        stack: [
          { text: String(value), fontSize: 16, bold: true, color, margin: [0, 0, 0, 2] },
          { text: label, fontSize: 8, color: '#6b7280', bold: true },
        ],
      }]],
    },
    layout: {
      hLineColor: () => '#d1d5db',
      vLineColor: () => '#d1d5db',
    },
  }
}

function sectionTitle(textValue: string) {
  return {
    text: textValue,
    fontSize: 14,
    bold: true,
    color: '#111827',
    margin: [0, 14, 0, 8],
  }
}

async function buildInspectionReportPdf(inspectionId: string, language: string) {
  ensurePdfFonts()
  const dict = dictFor(language)
  const inspection = await loadInspectionData(inspectionId, dict)

  const vehicle = relation(inspection.vehicles)
  const driver = relation(inspection.drivers)
  const results = relationArray(inspection.inspection_results).sort(
    (a: any, b: any) => (a.inspection_template_items?.sort_order || 0) - (b.inspection_template_items?.sort_order || 0)
  )
  const issues = relationArray(inspection.issues)

  const photos = [
    ...results.flatMap((row: any) => normalizePhotoUrls(row.photo_urls)),
    ...issues.flatMap((issue: any) => normalizePhotoUrls(issue.photo_urls)),
  ]

  const { data: repairs } = issues.length
    ? await supabase
        .from('repairs')
        .select('id, issue_id, status, notes, description, priority')
        .in('issue_id', issues.map((issue: any) => issue.id))
    : { data: [] as any[] }

  const repairsByIssueId = new Map(
    relationArray(repairs).map((repair: any) => [repair.issue_id, repair])
  )

  const [vehiclePhoto, signatureImage, ...photoImages] = await Promise.all([
    loadImageDataUrl(resolvePhotoUrl(vehicle?.photo_url), 320, 0.86),
    loadImageDataUrl(resolvePhotoUrl(inspection.signature_data_url), 900, 0.95),
    ...photos.slice(0, 12).map((url: string) => loadImageDataUrl(url, 420, 0.82)),
  ])

  const generatedAt = formatDateTime(new Date().toISOString(), language as any, '-')
  const submittedAt = formatDateTime(inspection.submitted_at || inspection.created_at, language as any, '-')
  const signedAt = formatDateTime(inspection.signed_at || inspection.submitted_at || inspection.created_at, language as any, '-')

  const resultValue = reportResult(inspection.status, results)
  const resultLabel = localizedResult(resultValue, dict)
  const reviewLabel = localizedReviewStatus(issues, dict)

  const passedCount = results.filter((row: any) => row.result === 'pass').length
  const failedCount = results.filter((row: any) => row.result === 'fail').length
  const naCount = results.filter((row: any) => row.result === 'not_applicable').length

  const content: any[] = []

  content.push({
    table: {
      widths: ['*'],
      body: [[{
        fillColor: '#2563eb',
        margin: [12, 10, 12, 10],
        stack: [
          { text: dict.appName, fontSize: 18, bold: true, color: '#ffffff' },
          { text: dict.reportTitle, fontSize: 24, bold: true, color: '#ffffff', margin: [0, 3, 0, 0] },
          {
            columns: [
              { text: `${dict.reportId}: ${inspection.id}`, fontSize: 9, color: '#dbeafe' },
              { text: `${dict.generated}: ${generatedAt}`, fontSize: 9, color: '#dbeafe', alignment: 'right' },
            ],
            margin: [0, 6, 0, 0],
          },
        ],
      }]],
    },
    layout: 'noBorders',
    margin: [0, 0, 0, 12],
  })

  content.push(sectionTitle(dict.vehicleSummary))

  content.push({
    table: {
      widths: [110, '*', 140],
      body: [[
        {
          margin: [8, 8, 8, 8],
          stack: vehiclePhoto
            ? [{ image: vehiclePhoto, fit: [94, 74], alignment: 'center' }]
            : [{ text: dict.noPhoto, color: '#6b7280', alignment: 'center', margin: [0, 26, 0, 0] }],
        },
        {
          margin: [4, 8, 8, 8],
          stack: [
            { text: vehicleName(vehicle), fontSize: 16, bold: true, color: '#111827' },
            { text: `${dict.unit} ${text(vehicle?.unit)} - ${dict.plate} ${text(vehicle?.plate)} - ${dict.vin} ${text(vehicle?.vin)}`, fontSize: 9, color: '#6b7280', margin: [0, 4, 0, 0] },
            { text: `${dict.inspectionType}: ${inspectionTypeLabel(inspection.type, dict)}`, fontSize: 10, color: '#374151', margin: [0, 4, 0, 0] },
            { text: `${dict.submitted}: ${submittedAt}`, fontSize: 10, color: '#374151', margin: [0, 2, 0, 0] },
            { text: `${dict.driver}: ${text(driver?.name || driver?.email, '-')}`, fontSize: 10, color: '#374151', margin: [0, 2, 0, 0] },
          ],
        },
        {
          margin: [0, 10, 8, 8],
          stack: [
            { text: dict.result, fontSize: 8, bold: true, color: '#6b7280', margin: [0, 0, 0, 4] },
            badge(resultLabel),
            { text: dict.review, fontSize: 8, bold: true, color: '#6b7280', margin: [0, 10, 0, 4] },
            badge(reviewLabel),
          ],
        },
      ]],
    },
    layout: {
      hLineColor: () => '#d1d5db',
      vLineColor: () => '#d1d5db',
      hLineWidth: () => 1,
      vLineWidth: () => 1,
    },
    margin: [0, 0, 0, 12],
  })

  content.push({
    columns: [
      metricCard(dict.passed, passedCount, '#16a34a'),
      metricCard(dict.failed, failedCount, '#dc2626'),
      metricCard(dict.notApplicable, naCount, '#6b7280'),
      metricCard(dict.issues, issues.length, '#d97706'),
      metricCard(dict.photos, photos.length, '#2563eb'),
    ],
    columnGap: 8,
    margin: [0, 0, 0, 8],
  })

  content.push(sectionTitle(dict.driverSignature))

  if (!signatureImage) {
    content.push({
      table: {
        widths: ['*'],
        body: [[{ text: dict.noSignature, color: '#6b7280', margin: [10, 12, 10, 12] }]],
      },
      layout: {
        fillColor: () => '#f9fafb',
        hLineColor: () => '#d1d5db',
        vLineColor: () => '#d1d5db',
      },
      margin: [0, 0, 0, 4],
    })
  } else {
    content.push({
      table: {
        widths: [240, '*'],
        body: [[
          { image: signatureImage, fit: [220, 70], margin: [10, 10, 10, 10] },
          {
            stack: [
              { text: `${dict.signedBy}: ${text(driver?.name || driver?.email, '-')}`, margin: [0, 22, 0, 4], color: '#374151' },
              { text: `${dict.signedAt}: ${signedAt}`, fontSize: 9, color: '#6b7280' },
            ],
            margin: [0, 10, 10, 10],
          },
        ]],
      },
      layout: {
        fillColor: () => '#f9fafb',
        hLineColor: () => '#d1d5db',
        vLineColor: () => '#d1d5db',
      },
      margin: [0, 0, 0, 4],
    })
  }

  content.push(sectionTitle(dict.checklistItems))

  if (!results.length) {
    content.push({ text: dict.noChecklist, color: '#6b7280', margin: [0, 0, 0, 8] })
  } else {
    results.forEach((row: any, index: number) => {
      const item = row.inspection_template_items || {}
      const category = item.inspection_item_categories?.name || dict.checklistFallback
      const photoCount = row.photo_urls?.length || 0

      const stack: any[] = [
        { text: `${index + 1}. ${text(item.title, dict.checklistFallback)}`, fontSize: 11, bold: true, color: '#111827' },
        { text: category, fontSize: 8, bold: true, color: '#6b7280', margin: [0, 3, 0, 4] },
        {
          columns: [
            ...(item.requires_photo ? [{ width: 'auto', ...badge(dict.photoRequired) }] : []),
            { width: 'auto', ...badge(localizedResult(row.result, dict)) },
          ],
          columnGap: 6,
          margin: [0, 0, 0, 4],
        },
      ]

      if (row.comment) {
        stack.push({ text: `${dict.notes}: ${row.comment}`, fontSize: 9, color: '#374151', margin: [0, 3, 0, 2] })
      }

      if (photoCount) {
        stack.push({
          text: photoCount === 1
            ? `1 ${dict.photoReferenceAttached}`
            : `${photoCount} ${dict.photoReferencesAttached}`,
          fontSize: 8,
          bold: true,
          color: '#2563eb',
          margin: [0, 2, 0, 0],
        })
      }

      content.push({
        table: { widths: ['*'], body: [[{ stack, margin: [12, 10, 12, 8] }]] },
        layout: {
          hLineColor: () => '#d1d5db',
          vLineColor: () => '#d1d5db',
        },
        margin: [0, 0, 0, 6],
      })
    })
  }

  content.push(sectionTitle(dict.issuesSection))

  if (!issues.length) {
    content.push({
      table: {
        widths: ['*'],
        body: [[{ text: dict.noIssues, color: '#166534', bold: true, margin: [10, 10, 10, 10] }]],
      },
      layout: {
        fillColor: () => '#dcfce7',
        hLineColor: () => '#d1d5db',
        vLineColor: () => '#d1d5db',
      },
      margin: [0, 0, 0, 6],
    })
  } else {
    issues.forEach((issue: any, index: number) => {
      const repair = repairsByIssueId.get(issue.id)
      const notes = [issue.description, repair?.notes && repair.notes !== issue.description ? repair.notes : '']
        .filter(Boolean)
        .join(' - ')

      content.push({
        table: {
          widths: ['*'],
          body: [[{
            margin: [12, 10, 12, 8],
            stack: [
              { text: `${index + 1}. ${text(issue.title, dict.issueFallback)}`, fontSize: 11, bold: true, color: '#111827' },
              {
                columns: [
                  { width: 'auto', ...badge(localizedSeverity(issue.severity, dict)) },
                  { width: 'auto', ...badge(localizedReviewStatus([issue], dict)) },
                  ...(repair?.status ? [{ width: 'auto', ...badge(`${dict.repairPrefix}: ${repair.status}`) }] : []),
                ],
                columnGap: 6,
                margin: [0, 6, 0, 2],
              },
              ...(notes ? [{ text: `${dict.notes}: ${notes}`, fontSize: 9, color: '#374151', margin: [0, 3, 0, 0] }] : []),
            ],
          }]],
        },
        layout: {
          fillColor: () => '#fffbeb',
          hLineColor: () => '#d1d5db',
          vLineColor: () => '#d1d5db',
        },
        margin: [0, 0, 0, 6],
      })
    })
  }

  const filteredPhotoImages = photoImages.filter(Boolean) as string[]
  if (filteredPhotoImages.length) {
    content.push({ ...sectionTitle(dict.photos), pageBreak: 'before' })

    for (let index = 0; index < filteredPhotoImages.length; index += 3) {
      const row = filteredPhotoImages.slice(index, index + 3).map((image) => ({ image, fit: [160, 110], margin: [0, 4, 0, 4] }))
      while (row.length < 3) row.push({ text: '' })
      content.push({ columns: row, columnGap: 8 })
    }
  }

  const docDefinition: any = {
    pageSize: 'A4',
    pageMargins: [32, 30, 32, 36],
    defaultStyle: {
      font: 'Roboto',
      fontSize: 10,
      color: '#111827',
    },
    footer: (currentPage: number, pageCount: number) => ({
      columns: [
        { text: `${dict.generatedBy} - ${generatedAt}`, color: '#6b7280', margin: [32, 0, 0, 0], fontSize: 8 },
        { text: `${dict.page} ${currentPage} / ${pageCount}`, color: '#6b7280', alignment: 'right', margin: [0, 0, 32, 0], fontSize: 8 },
      ],
    }),
    content,
  }

  const pdfDoc = (pdfMake as any).createPdf(docDefinition)
  const blob = await toBlob(pdfDoc)
  ensureBlobHasContent(blob, dict)

  const dateValue = inspection.submitted_at || inspection.created_at
  const datePart = dateValue ? String(dateValue).slice(0, 10) : 'report'
  const unit = fileSafe(text(vehicle?.unit, 'vehicle'))
  const fileName = unit
    ? `vehicle-${unit}-report-${datePart}.pdf`
    : `report-${inspection.id}.pdf`

  return { blob, fileName, dict }
}

export async function downloadInspectionReportPdf(inspectionId: string, language: string) {
  const { blob, fileName } = await buildInspectionReportPdf(inspectionId, language)
  downloadBlob(blob, fileName)
}

export async function previewInspectionReportPdf(
  inspectionId: string,
  language: string,
  previewWindow?: Window | null
) {
  const dict = dictFor(language)
  const targetWindow = previewWindow || window.open('', '_blank', 'noopener,noreferrer')

  if (!targetWindow) {
    throw new Error(dict.popupBlocked)
  }

  const { blob } = await buildInspectionReportPdf(inspectionId, language)
  previewBlob(blob, targetWindow)
}

export async function shareInspectionReportPdf(inspectionId: string, language: string) {
  const { blob, fileName, dict } = await buildInspectionReportPdf(inspectionId, language)
  await shareBlob(blob, fileName, dict)
}
